### ISSUE TITLE
KeyError 'table.head' when running `validator.head()`

### ISSUE THREAD

**Issue by matthiasgomolka** [great-expectations/great_expectations#10007]
**Describe the bug**
When I create a validator and run `validator.head()` afterwards, I get the following error:

> KeyError: ('table.head', 'batch_id=my_batch_id', 'd3dccd4afc8415bdf36b6279ee0a8929')

**To Reproduce**
```python
import great_expectations as gx

connect_url_impala_ldap = "impala://$USERNAME:$PW@my.server.de:8443/my_db"
connect_args_impala_ldap = {
    "use_ssl": True,
    "auth_mechanism": "LDAP",
    "use_http_transport": True,
    "http_path": "my/gateway/impala",
}

context = gx.get_context()

datasource = context.sources.add_or_update_sql(
    name="my_ds",
    connection_string=connect_url_impala_ldap,
    kwargs={"connect_args": connect_args_impala_ldap},
)

asset_name = "bilanzen"

if asset_name not in datasource.get_asset_names():
    datasource.add_table_asset(
        name=asset_name,
        table_name="bilanzen",
        schema_name="my_schema_name"
    )

validator = context.get_validator(
    data_asset_name=asset_name,
    datasource_name="my_ds",
    expectation_suite_name="my_expectation_suite"
)

validator.head()
```

**Expected behavior**
I would expect to see a preview of the data source. A couple weeks ago this worked with the identical code. I tried going back to the older GX version, but had no success. The only difference is that I only have reading permission this time.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version:0.18.15
 - Data Source: generic SQL (connecting to Impala)
 - Cloud environment: on-premise Impala

**Additional context**
Seems similar to #5478

**Comment by molliemarie** [comment]
Hello @matthiasgomolka. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
