### ISSUE TITLE
row_condition error in great_expectations for spark 

### ISSUE THREAD

**Issue by raman0453** [great-expectations/great_expectations#10058]
"exception_message": "TypeError: SparkDFDataset.expect_column_values_to_be_in_set() got an unexpected keyword argument 'row_condition'". row_condition is working for pandas but not with spark. In the documentation it is mentioned that 'condition_parser': "great_expectations__experimental__" can solve the issue but not working

**Comment by vasilijyaromenka** [comment]
'condition_parser': "spark" 
works in my case

**Comment by kujaska** [comment]
and when using 'condition_parser': "spark" you use regular SQL syntax, correct?
like this:
fld1 = 5 OR fld2 <>90 AND fld3 >8

**Comment by vasilicommify** [comment]
@kujaska , no I use '==' instead of '=' but the the rest of operators are the same

```
    {
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column":"check_compound_bool",
        "condition_parser": "spark",
        "row_condition": "not is_disabled AND col2 IS NULL  AND col3>0 AND sum_col == a + b  "
      },
      "meta": {
        "notes": "check 3 conditions"
      }
    }
```

your condition would be

`fld1 == 5 OR fld2 != 90 AND fld3 >8`

**Comment by molliemarie** [comment]
Hello @raman0453. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
