### ISSUE TITLE
Add the ability to specify ExternalId and Tags in the boto3_options of TupleS3StoreBackend

### ISSUE THREAD

**Issue by rosspb3** [great-expectations/great_expectations#10074]
**Is your feature request related to a problem? Please describe.**

Inability to run Great Expectation with a TupleS3StoreBackend in a cross-account scenario where the role assumed has an AWS policy that restricts role access by ExternalId and Tags.

**Describe the solution you'd like**
The ability to specify an ExternalId and Tags when the role is assumed.

**Describe alternatives you've considered**
A less restrictive policy for assuming the role, or running Great Expectation within the same account.  However, corporate security makes those changes difficult.

**Comment by molliemarie** [comment]
Hello @rosspb3. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
