### ISSUE TITLE
Query containing CTE is not working anymore in get_validator. WITH clause is getting replaced with SELECT

### ISSUE THREAD

**Issue by yashkasat96** [great-expectations/great_expectations#10132]
**Describe the bug**
I had a validation implemented for comparing two different tables in a SQL query using CTE expression. With version 0.17.9 everything was working but when I updated the great expectation version to 0.18.17, I started getting issues of incorrect SQL query.

> InvalidRequestException: An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 2:24: mismatched input '('. Expecting: <identifier>

Reason for the above failure was because the sql query is getting modified now. The first 6 character of the SQL query is getting modified to SELECT. This is making the query which starts with WITH clause to fail.

The issue is happening in the get_validator function, where we are passing the sql query in the batch_request.

I observed that the above issue is happening because of using selectable in get_batch_data_and_markers function in sqlalchemy_execution_engine.py module.
![Screenshot 2024-07-22 at 5 31 37 PM](https://github.com/user-attachments/assets/13974681-e30f-4948-8d92-921e69e29fa4)

If the same query which is written using CTE expression is written using subquery, then the code runs without any issue.

**To Reproduce**
I cannot provide the file but if there is some more information needed to understand the above issue. I will share more details.

**Expected behavior**
I am just curious to know if this is an expected behavior or a bug, I mean do we expect some complex query in the get_validator or just a plain select statement.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations 0.18.17
 - Data Source: Athena
 - Cloud environment: AWS

**Additional context**

**Comment by molliemarie** [comment]
Hello @yashkasat96. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
