### ISSUE TITLE
How to check partial_unexpected_index_list while working with spark_dataframe 

### ISSUE THREAD

**Issue by Vector303** [great-expectations/great_expectations#10143]
Using this 
validator.expect_column_values_to_not_be_null(
    column="Age",result_format="COMPLETE", include_unexpected_rows=True)
the above outputs as follows
{
  "success": false,
  "result": {
    "element_count": 1002,
    "unexpected_count": 102,
    "unexpected_percent": 10.179640718562874,
    "partial_unexpected_list": [
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null,
      null
    ],
    "partial_unexpected_counts": [
      {
        "value": null,
        "count": 102
      }
      
      But doesn't give us the index names, to further filter out validated data

**Comment by molliemarie** [comment]
Hello @Vector303. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
