### ISSUE TITLE
Bigquery Table validation based on user managed client connections

### ISSUE THREAD

**Issue by viditjain88** [great-expectations/great_expectations#10153]
**Is your feature request related to a problem? Please describe.**
I have to perform bigquery table validation using sqlachemy and sqlachemy_bigquery using custion client connection to connect to bigquery api

**Describe the solution you'd like**
I have different compute project that needs to run the validation on bigquery table which is stored in in different project.
**Describe alternatives you've considered**
trying to pass before code but it didn't work still the  auto generated validation query still trying to run where data stored.
  bigquery_datasource = "my_bigquery_datasource"
  example_yaml = f"""
  name: {bigquery_datasource}
  class_name: Datasource
  execution_engine:
    class_name: SqlAlchemyExecutionEngine
    connection_string: {connection_string}
    query_project: {compute_project}
**Additional context**
Add any other context, screenshots, or code samples about the feature request here.

**Comment by molliemarie** [comment]
Hello @viditjain88. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
