### ISSUE TITLE
GX folder created in the project/context directory when instantiating a Data context based on existing great_expectations.yml

### ISSUE THREAD

**Issue by aya-elmobayad** [great-expectations/great_expectations#10161]
I'm working with a setup where we need to have multiple GX context directories for different usecases. 

<pre>
└── great_expectations
    └── use_case_1
        └── great_expectations.yml
    └── use_case_1
        └── great_expectations.yml
</pre>

Because we need maximum configurability, I write the data configs in the great_expectations.yml via a script and rely on `DataContext(context_root_dir=context_dir)` or `gx.get_context(context_root_dir=context_dir)` to instantiate the data context. 
However, I’ve been noticing lately (after switching from version 0.15.50 to 0.18.10) that doing so creates yet another directory named "gx", which isn't actually used as an active data context since all the artifacts are created the respective directories we have set up. 

I don’t understand why this is occurring, any guidance would be appreciated.

**Comment by molliemarie** [comment]
Hello @aya-elmobayad. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
