### ISSUE TITLE
Documentation "Use Great Expectations with Amazon Web Services using Athena" example has wrong Python syntax

### ISSUE THREAD

**Issue by avazhnov-twilio** [great-expectations/great_expectations#10162]
**Describe the bug**

This Python code example has wrong syntax:

```python
athena_source: SQLDatasource = context.sources.add_or_update_sql(
    "my_awsathena_datasource", connection_string=connection_string
)
athena_table = athena_source.add_table_asset("taxitable", table_name="taxitable")


batch_request = athena_table.build_batch_request()
```

> E0602: Undefined variable 'SQLDatasource' (undefined-variable)

URL: https://docs.greatexpectations.io/docs/oss/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_athena/#connect-to-data

**Comment by molliemarie** [comment]
Hello @avazhnov-twilio. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
