### ISSUE TITLE
Dev container - You'll need a new app to open this vscode-remote link

### ISSUE THREAD

**Issue by ai-learner-00** [great-expectations/great_expectations#10233]
**Describe the bug**
I am having the same issue as #8590. The line `context.view_validation_result(checkpoint_result)` from the quickstart doesn't work on Windows. I tried creating a dev container, but I am not able to open the link.

![image](https://github.com/user-attachments/assets/e34798d4-2814-41cd-868d-11b9a0b8d293)

**To Reproduce**
[quickstart.zip](https://github.com/user-attachments/files/16662236/quickstart.zip)
I am running the code from the [Quickstart](https://docs.greatexpectations.io/docs/oss/tutorials/quickstart/) inside a dev container. I attached above the files needed to create the container. 
1. Open the folder in vscode
2. Reopen in dev container (docker needs to be installed)
3. Run the `_experiments/docs/quickstart.ipynb` file

**Expected behavior**
I was expecting the link to be opened. In the context of servers, I know that vscode automatically forwards the port, but maybe it is different for static files. 

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.18.19
 - Data Source: Pandas
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]

**Additional context**
I am developing on Windows and I am wondering how to make great_expectations work.

**Comment by molliemarie** [comment]
Hello @ai-learner-00. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
