### ISSUE TITLE
Expectations execute more than once, result is slow in airflow and unusual errror about env variable which is present

### ISSUE THREAD

**Issue by cedric-ejara** [great-expectations/great_expectations#10231]
**Describe the bug**
Great expectation executives more than once, and getting the results takes like forever, I limited my data row to 10 and it's still takes a good amount of time to execute the second time and return the result.

**To Reproduce**
I created a class to configure gx called GreatExpectation on airflow and run custom expectations.
![Screenshot from 2024-08-19 13-36-22](https://github.com/user-attachments/assets/8c06ab34-9f97-4737-b0aa-96173690b869)
![Screenshot from 2024-08-19 13-37-03](https://github.com/user-attachments/assets/a298bdc3-b83b-4683-ab71-49800d163549)
![Screenshot from 2024-08-19 13-36-47](https://github.com/user-attachments/assets/48ee320f-f968-427c-b252-f22f412453ff)

And other class for the adding datasources and doing the test call QualityTest
![Screenshot from 2024-08-19 13-38-55](https://github.com/user-attachments/assets/2500d906-468e-4a7a-8b18-4d009dd53eaf)
![Screenshot from 2024-08-19 13-39-16](https://github.com/user-attachments/assets/d8d684d1-7f2f-401e-9ef5-9affeb395b71)
![Screenshot from 2024-08-19 13-39-40](https://github.com/user-attachments/assets/19da5d27-1493-49c2-982f-817ed71cb66a)

With a python operator
![Screenshot from 2024-08-19 13-43-34](https://github.com/user-attachments/assets/6724c8e4-897f-470f-ba74-05d3e6fe216c)

**Here is the output**
![Screenshot from 2024-08-19 13-45-37](https://github.com/user-attachments/assets/39038cc2-af6f-40ff-a3e8-ec22a8ea96f8)

**From time to time I get this error (No seeing my config variable in the config_variable.yml file which that value is present, sometimes it works other times it doesn't)**
![Screenshot from 2024-08-19 13-46-44](https://github.com/user-attachments/assets/0ccad65c-90b7-4374-9057-581b49a662f7)

**Expected behavior**
How can I make the gx execute faster and once and stop this error from occurring with it shouldn't in the 1st place

**Environment (please complete the following information):**
 - Operating System: [Linux]
 - Great Expectations Version: [0.18.8]
 - Data Source: [Pandas, and Snowflake(Snowpark)]
 - Cloud environment: [Airflow 2.9.0]

**Comment by cedric-ejara** [comment]
**Environment:**

Operating System: [Linux]
Great Expectations Version: [0.18.8]
Data Source: [Pandas, and Snowflake(Snowpark)]
Airflow: [2.9.0]

**Comment by molliemarie** [comment]
Hello @cedric-ejara. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
