### ISSUE TITLE
BaseDataContext is not available in the new release 1.0.0

### ISSUE THREAD

**Issue by liqi6811** [great-expectations/great_expectations#10264]
**Describe the bug**
Our current code is using BaseDataContext, however, we got import error after this morning release of 1.0.0 version. I tried to use other datacontext, such as AbstractDataContext and getcontext(), but since we are using below two methods within previous BaseDataContext, the new datacontext does not work. 

context = BaseDataContext(project_config=MyConfig)
context.test_yaml_config(MySparkDSConfig)
context.add_datasource(**yaml.load(MySparkDSConfig), verbose=False)

**To Reproduce**
from great_expectations.data_context import BaseDataContext

**Expected behavior**
Hope to find out if BaseDataContext is still available in the new version, if yes, where to import. If no, how to test yaml config for spark datasource and add datasource

**Comment by AndrewNelis** [comment]
I think this only happens on Python 3.8.

I've worked around this for now by installing "great-expectations<1.0" until this is fixed.

**Comment by adeola-ak** [comment]
BaseDataContext is no longer available. There are a number of other breaking changes in 1.0, largely around simplifying the interface, so I'd recommend checking out our newest documentation for [connecting with spark](https://docs.greatexpectations.io/docs/core/connect_to_data/dataframes/?execution_engine=spark). 

I'm going to close this issue out for now as this behavior is expected. We do plan to get a 1.0 migration guide out soon to help with the transition. As the previous commenter suggested, you can always pin 0.18 for now and migrate when you can

**Comment by adeola-ak** [comment]
hi @AndrewNelis this behavior is expected as we have removed `BaseDataContext ` in 1.0, which also introduced a few other breaking changes for simplification. As 0.18 will not be supported in the future, I recommend following our documentation to migrate to 1.0 at your earliest convenience.
