### ISSUE TITLE
DataContext Issue

### ISSUE THREAD

**Issue by JCristinaJSalas** [great-expectations/great_expectations#10296]
Expected behavior I expected to be able to import DataContext from great_expectations.data_context without encountering an ImportError, allowing me to configure and use Great Expectations within Databricks.

Environment (please complete the following information):

Operating System: Windows 11
Great Expectations Version: 1.0.0
Data Source: PySpark
Cloud environment: Databricks
Additional context The issue occurs when trying to set up Great Expectations in a Databricks notebook. I have followed the installation and setup instructions, but the import error persists. As well, I cannot find anymore the documentation online :(

**Comment by adeola-ak** [comment]
hi there, here is the documentation for getting started with [Databricks](https://docs.greatexpectations.io/docs/core/set_up_a_gx_environment/install_gx?install-location=hosted)

and here is a snippet of how you can get started:
<img width="579" alt="Screenshot 2024-08-28 at 2 25 38 PM" src="https://github.com/user-attachments/assets/46344f77-37e9-4ae5-8ffd-f2cef5734c06">

you will need to run `context = gx.get_context(context_root_dir=context_root_dir)` to instantiate your Data Context

**Comment by snabbasi** [comment]
https://docs.greatexpectations.io/docs/0.18/oss/get_started/get_started_with_gx_and_databricks/
Following methods don't exists in my version of 1.2.5 on databricks
context.add_or_update_expectation_suite
Also, I'm unable to import DataContext
from great_expectations.data_context import DataContext

**Comment by adeola-ak** [comment]
> https://docs.greatexpectations.io/docs/0.18/oss/get_started/get_started_with_gx_and_databricks/ Following methods don't exists in my version of 1.2.5 on databricks context.add_or_update_expectation_suite Also, I'm unable to import DataContext from great_expectations.data_context import DataContext

@snabbasi Our documentation is versioned, and you're currently viewing the docs for version 0.18. The [v1 documentation](https://docs.greatexpectations.io/docs/core/set_up_a_gx_environment/install_gx?hosted-type=databricks-notebook) is available here. You can switch between documentation versions using the dropdown menu in the top left corner.
