### ISSUE TITLE
Get Started link is broken

### ISSUE THREAD

**Issue by Stuzanna** [great-expectations/great_expectations#10321]
**Describe the bug**
On the README of the repo, the Get Started link is to an old page, 404.

**To Reproduce**
Click the link on the README.

**Expected behavior**
Takes you to the best get started resource

**Environment (please complete the following information):**
N/A
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]
 - Data Source: [e.g. Pandas, Snowflake]
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]

**Additional context**

**Comment by adeola-ak** [comment]
the fix will be merged soon, thank you!
