### ISSUE TITLE
[BUG] Incorrect representation of value_set in expectation

### ISSUE THREAD

**Issue by Terma1** [great-expectations/great_expectations#10343]
**Describe the bug**
When writing code 
`expectation = gx.expectations.ExpectColumnValuesToBeInSet( column="letters", value_set = ['AB','BB','BC','AS','AD'])`
value_set stored in to expectation as a dictionary. 
`ExpectColumnValuesToBeInSet(id=None, meta=None, notes=None, result_format=<ResultFormat.BASIC: 'BASIC'>, catch_exceptions=True, rendered_content=None, batch_id=None, row_condition=None, condition_parser=None, column='letters', mostly=1.0, value_set={'A': 'D', 'B': 'C'})`

**value_set={'A': 'D', 'B': 'C'})**

This always happend when the list components consist of two elements

**Expected behavior**

Value_set is stored as a list. **value_set={'AB','BB','BC','AS','AD'}**

**Environment:**
Databricks and spark DataFrame

**Comment by adeola-ak** [comment]
hi @Terma1 are you on 1.0?

**Comment by Terma1** [comment]
Hi! With the new version 1.0.2 the problem was solved. Thank you!
