### ISSUE TITLE
[DOCS] 'PandasFilesystemDatasource' object has no attribute 'add_directory_csv_asset'

### ISSUE THREAD

**Issue by HuhtaLauri** [great-expectations/great_expectations#10352]
**Describe the bug**
This [page](https://docs.greatexpectations.io/docs/core/connect_to_data/filesystem_data/) in the docs, when taking the "Directory Data Asset" path tells you to create the asset with `data_source.add_directory_csv_asset()` but that method does not exist anymore.

**Environment (please complete the following information):**
 - Great Expectations Version: 1.0.2
 - Data Source: Pandas

Sidenote: There has been so many issues with the docs since the 1.0.0 release. Please go through them thoroughly.

**Comment by adeola-ak** [comment]
thank you for bringing this to our attention, @Itzblend. I will get this updated. Were you able to figure out the correct method or do you still need help with that?

**Comment by HuhtaLauri** [comment]
Well it's unclear to me if Directory Data Asset is supposed to exist

**Comment by adeola-ak** [comment]
looks like it is not supposed to exist for pandas. I see how the code snippet might be a little misleading, but on the same docs page above the snippet we have text that says this:

_Spark Filesystem Data Sources support Directory Data Assets for all supported Filesystem environments. However, pandas Filesystem Data Sources do not support Directory Data Assets at all._

**Comment by HuhtaLauri** [comment]
Ah my bad. I tend to skip parts of the docs as they repeat alot of stuff already done

**Comment by adeola-ak** [comment]
no problem! i understand. i'll go ahead and close this issue but let us know if anything else comes up, thanks!
