### ISSUE TITLE
Column Expectations on Druid datasource

### ISSUE THREAD

**Issue by Frigus007** [great-expectations/great_expectations#10368]
When using Great Expectations (GE) to add validation checks on a Druid datasource, two expectations were applied to columns p1 and p2. However, the SQL query generated by GE includes duplicate column names, which Druid does not support. Specifically, the query contains two columns named "column_values.nonnull.unexpected_count", which causes Druid to fail in returning data. The issue arises because the same column name is assigned to different expressions in the SQL query.

**To Reproduce**

Add expectations on the p1 and p2 columns of a Druid datasource.

Run the validation with the following expectations:
{
      "expectation_type": "expect_column_values_to_not_be_null",
      "kwargs": {
        "column": "p1",
         "mostly":0.66
      }
    },
    {
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "p2",
        "value_set": [
          "0",
          "1",
          "2",
          "3",
          "4",
          "5",
          "6",
          "7",
          "unknown"
        ],
         "mostly":0.661
      }
    }
This generates a query similar to:
SELECT sum(CASE WHEN ("p1" IS NOT NULL AND ("p1" NOT IN ('0', '1', '2', '3', '4', '5', '6', '7'))) THEN 1 ELSE 0 END) AS "column_values.in_set.unexpected_count", 
sum(CASE WHEN ("p2" IS NULL) THEN 1 ELSE 0 END) AS "column_values.nonnull.unexpected_count", 
sum(CASE WHEN ("p1" IS NULL) THEN 1 ELSE 0 END) AS "column_values.nonnull.unexpected_count" 
FROM (SELECT * FROM t WHERE __time >= timestamp '2024-09-04 00:00:00' and __time <= timestamp '2024-09-04 23:59:59') AS "anon_1";
Druid fails to return data due to the duplicate column names.

**Expected behaviour** 
The query should generate unique column names for each expectation, allowing Druid to process and return the validation results successfully.

The issue likely occurs because the same alias "column_values.nonnull.unexpected_count" is assigned to both null checks for p1 and p2. This needs to be fixed so that column names in the SQL query are distinct.

**Comment by adeola-ak** [comment]
hey there - unfortunately, we do not support a direct connection to Druid as a datasource in Great Expectations. as an alternative, you might consider exporting your data from Druid into a format that is supported, such as a CSV file or a Pandas DataFrame, and then run your validations using those formats.

I'll be closing this issue as druid is not a supported data source so we can't guarantee full compatibility, but please let us know if you have any further questions or if there's anything else i can assist with.

**Comment by Frigus007** [comment]
@adeola-ak Thanks for your response.
But Great Expectations supports all SQLAlchemy dialects pydruid is one of them.
Also, it is not standard to use the same alias name for multiple columns in a single query.
