### ISSUE TITLE
Unable to convert Checkpoint results to serialized json format

### ISSUE THREAD

**Issue by PDebasish** [great-expectations/great_expectations#10367]
**Describe the bug**
I am trying to convert the results obtained from checkpoint to a json normalized format and read into a pyspark dataframe.  Appreciate your help on the same.
[Environment Set up.txt](https://github.com/user-attachments/files/16939992/Environment.Set.up.txt)

**To Reproduce**
I have included the code in the attachment.

**Expected behavior**
A normalized json format which can be read to a pyspark dataframe.

**Environment (please complete the following information):**
 - Operating System: NA
 - Great Expectations Version: 1.0.2
 - Data Source: Pandas dataframe(using Fabric lakehouse files)
 - Cloud environment: Microsoft Fabric

**Additional context**

**Comment by PDebasish** [comment]
I am trying to convert the checkpoint results to serialized json format using the below code:

Code: 
df=checkpoint_results.to_json_dict()
display(df)

Error:
AttributeError: 'CheckpointResult' object has no attribute 'to_json_dict'

**Comment by adeola-ak** [comment]
hi, this behavior is expected. the `to_json_dict()` attribute does not exist on CheckpointResult however it does look like it exists on ExpectationValidationResult

**Comment by PDebasish** [comment]
Thanks @adeola-ak for the response. Can you please advise how can I de-serialize the checkpoint results and read it in a tabular format in a pyspark dataframe. As we plan to store it in a delta table in lakehouse.

**Comment by adeola-ak** [comment]
The CheckpointResult has a [describe()](https://github.com/great-expectations/great_expectations/blob/8b2840e6ed9ac2131eddb233fd5cd5c871e721f7/great_expectations/checkpoint/checkpoint.py#L375) method that returns a JSON string description of the result. You can convert this as needed. Beyond this, Great Expectations doesn't offer any built-in solutions, so you would need to implement a custom approach.

**Comment by adeola-ak** [comment]
I will be closing this issue - I hope the above advice helps. Thank you!
