### ISSUE TITLE
[Bug]  Notifiy MS team

### ISSUE THREAD

**Issue by superbeer** [great-expectations/great_expectations#10361]
**Describe the bug**

**To Reproduce**
Please include your great_expectations.yml config, the code you’re executing that causes the issue, and the full stack trace of any error(s).

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]
 - Data Source: [e.g. Pandas, Snowflake]
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]

**Additional context**

**Comment by adeola-ak** [comment]
as no bug or behavior has been outlined in the template, i will be closing this issue. please be sure to include details of any issues you are facing so we can help!
