### ISSUE TITLE
[BUG] Fluent data sources not updated in in-memory data context

### ISSUE THREAD

**Issue by jschra** [great-expectations/great_expectations#10370]
**Describe the bug**
Whenever I run logic to create a new data source, in my example a pandas data source, it does not get added/updated in the in-memory data-context, whereas I would expect it to be added/updated in the fluent_datasources section of the in-memory data-context.

NOTE: if using a file data-context, that file counterpart of the in-memory data context does get updated.

**To Reproduce**
The script below can be run to reproduce. The script itself creates a fresh great_expectations.yml, so no need to attach one. I will again add the test data for easy repro on your part.

If you run the script in its entirety, what you will see is that the fluent data source is added to the great_expectations.yml file, but it is not in the in-memory counterpart. Only if you re-run get_context, does it now appear in-memory. I would expect it to be updated in both places simultaneously.

Note that the example includes a file data context, but the same happens for an ephemeral data context: no fluent data sources are added in-memory.

```python
import great_expectations as gx
import pandas as pd

# -- Set GX constants for artifact creation
NAME_DATA_SOURCE = "pandas"
NAME_DATA_ASSET = "tutorial_data"
NAME_BATCH_DEF = "pandas_tutorial"
NAME_EXPECTATION_SUITE = "tutorial"
NAME_VALIDATION_DEF = "pandas-validation"
NAME_CHECKPOINT = "pandas"

# -- Load data for configuration
FILE_CONFIGURE = "data/yellow_tripdata_2021-11.csv"
df_configure = pd.read_csv(FILE_CONFIGURE)

# -- 1. Initialize GX for configuration
context = gx.get_context(mode="file")

data_source = context.data_sources.add_pandas(name=NAME_DATA_SOURCE)
data_asset = data_source.add_dataframe_asset(name=NAME_DATA_ASSET)
batch_definition = data_asset.add_batch_definition_whole_dataframe(NAME_BATCH_DEF)

# -- 2. Configure expectation suite to be called over runtime data later
expectation_suite = gx.ExpectationSuite(name=NAME_EXPECTATION_SUITE)
expectation_suite = context.suites.add(expectation_suite)

# -- 2.1. Define table level expectations
columns = list(df_configure.columns)
expectation = gx.expectations.ExpectTableColumnsToMatchSet(column_set=columns)
expectation_suite.add_expectation(expectation)

# -- 2.2. Define column level expectations
expectation = gx.expectations.ExpectColumnValuesToNotBeNull(column="VendorID")
expectation_suite.add_expectation(expectation)

expected_values = [1, 2]
expectation = gx.expectations.ExpectColumnValuesToBeInSet(
    column="VendorID", value_set=expected_values
)
expectation_suite.add_expectation(expectation)

# -- 2.3. Evaluate results on test dataset
batch_parameters = {"dataframe": df_configure}
batch = batch_definition.get_batch(batch_parameters=batch_parameters)
validation_results = batch.validate(expectation_suite)

# -- 3. Bundle suite and batch into validation definition and checkpoint w/ bundled
# --    actions for easy execution later
validation_definition = gx.ValidationDefinition(
    data=batch_definition, suite=expectation_suite, name=NAME_VALIDATION_DEF
)
validation_definition = context.validation_definitions.add(validation_definition)

action_list = [
    gx.checkpoint.UpdateDataDocsAction(
        name="update_all_data_docs",
    ),
]
checkpoint = gx.Checkpoint(
    name=NAME_CHECKPOINT,
    validation_definitions=[validation_definition],
    actions=action_list,
    result_format={
        "result_format": "COMPLETE",
    },
)
context.checkpoints.add(checkpoint)

# -- 4. Run checkpoint to validate if everything works properly
runid = gx.RunIdentifier(run_name="Configuration run")
results = checkpoint.run(batch_parameters=batch_parameters, run_id=runid)
```

**Expected behavior**
When adding fluent data sources, I would expect these to be added both to the in-memory data context and its file counterpart (if running a file based data context).

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 1.0.2
 - Data Source: Pandas
 - Cloud environment: N/A

**Additional context**
Follow-up from AMA

**Comment by adeola-ak** [comment]
hey @jschra, just a heads up that im looking into this! thanks for the descriptive repro steps and write up.

**Comment by adeola-ak** [comment]
hi there. so i'm not sure what you see as the problem or what it is that you are trying to do. are you getting an error somewhere or unable to do something? can you clarify what it is that your are expecting to see? with a file context, you would not have an in memory context. you would not have both.

**Comment by jschra** [comment]
So this comes from my usage of ephemeral contexts and the workflow wherein we define and build these up and then materialize them into a file, to be loaded back into an ephemeral context at runtime.

Given that setup, it is important that the context object always completely resembles your setup and I noticed that whenever I create an ephemeral context and then define a data source, data asset and batch definition, that these do net get updated in the context object. I validate this by simply directly running the context object (which shows I believe a dict like representation of the great_expectations yaml). In that, the fluent_datasources section remains empty. Unlike eg the stores section, which do get updated if I call methods to set stores.

Since I already had a mock setup for a file based context, I also tried it there and experienced the same: the fluent data sources section of the context object remains empty after running logic wherein I define a fluent data source. In its file counterpart however (great_expectations.yml) the fluent data source does get added, which seems weird to me! Upon rerunning get_context, I see that now the fluent data sources actually have been populated in the context object.

So to me that seems like a bug. I’d expect that whoever I call logic on the context object (eg context.data_sources.add_pandas), you would always see it updated in said object. My workflow depends on that since I materialize the context object into a file, that’s why I found it out.

And you can see all this if you run the script above. Do so on a clean project with 1.0.2 and you’ll see that if you check the ‘context’ object, the fluent data sources are empty whereas they were just defined and used. They do, however, get added to the great_expectations yaml file.

So it is not unique to the type of context used: fluent data sources just appear to not be updated in the context object. 

Hope this helps!

**Comment by Kilo59** [comment]
- I believe this is also related to this issue https://github.com/great-expectations/great_expectations/issues/9283

**Comment by adeola-ak** [comment]
hi @jschra okay thanks for the details. I understand what you're saying now. looks like this is on our radar already since earlier this month, i'll follow up with an estimation on when we might get to this when i have one

**Comment by adeola-ak** [comment]
We likely won’t be able to address this until next month, but it’s in our queue. thanks for the thorough repro steps! you’re welcome to check back on the issue for any updates

**Comment by adeola-ak** [comment]
@jschra hi there, ive linked the related PR that has recently been merged and closes this issue, thanks again for bringing this to our attention
