### ISSUE TITLE
[BUG-CheckpointRelatedResourcesFreshnessError] Checkpoint fails when "send notification to Teams channel" is present in the Action list 

### ISSUE THREAD

**Issue by Erua-chijioke** [great-expectations/great_expectations#10398]
Describe the bug
Using Great expectations version 1.0.3, I created an action inside a checkpoint to send a notification to a teams channel through a webhook but when I run the checkpoint It displays this error below:

Note: I tried running the checkpoint without this particular action in the action list and everything works just fine. I only get this error when MicrosoftTeamsNotificationAction is used in the action list.

To Reproduce:

**create data source, asset, batch definition and expectation suite**
dataframe = spark.sql("SELECT * FROM xxx")
context = gx.get_context(project_root_dir="/dbfs/xxx")

data_source_name = "my_data_source"
data_asset_name = "my_dataframe_data_asset"
batch_definition_name = "my_batch_definition"
data_source = context.data_sources.add_or_update_spark(name=data_source_name)
data_asset=data_source.add_dataframe_asset(name=data_asset_name)
batch_definition = data_asset.add_batch_definition_whole_dataframe(batch_definition_name)

suite_name = "my_expectation_suite"
suite = gx.ExpectationSuite(name=suite_name)
suite = context.suites.add(suite)

table_row_count=dataframe.count()
table_row_count_expectationn = gxe.ExpectTableRowCountToEqual(value=table_row_count)
suite.add_expectation(table_row_count_expectationn)

**Retrieve the expectation suite and create validation definition**
expectation_suite_name = "my_expectation_suite"
expectation_suite = context.suites.get(name=expectation_suite_name)

definition_name = "my_validation_definition"
validation_definition = gx.ValidationDefinition(
        data=batch_definition, suite=expectation_suite, name=definition_name)
validation_definition = context.validation_definitions.add(validation_definition)

 validation_definitions = [
    context.validation_definitions.get("my_validation_definition")]

validation_notification_microsoft_teams_webhook = "xxx"

**create an action list**
action_list = [
    # This Action sends a Team Notification if an Expectation fails.
    gx.checkpoint.MicrosoftTeamsNotificationAction(
        name="send_microsoft_teams_notification_on_validation_result",
        teams_webhook= validation_notification_microsoft_teams_webhook,
        notify_on= "all",
    ),
    # This Action updates the Data Docs static website with the Validation
    #   Results after the Checkpoint is run.
    gx.checkpoint.UpdateDataDocsAction(
        name="update_all_data_docs",
    ),
]

**create a checkpoint**
checkpoint_name = "my_checkpoint"
    checkpoint = gx.Checkpoint(
        name=checkpoint_name,
        validation_definitions=validation_definitions,
        actions=action_list,
        result_format={"result_format": "COMPLETE"},
    )
    context.checkpoints.add(checkpoint)

def get_validation_result(checkpoint: Checkpoint, batch_definition: str, batch_parameters: Dict):

    run_id = gx.RunIdentifier(run_name=f"validation_checkpoint_for_{batch_definition}", run_time=datetime.now())

    validation_result = checkpoint.run(batch_parameters, run_id=run_id)

    if not validation_result.success:
        print("Validation failed! Notification has been sent.")
    return validation_result

batch_parameters = {"dataframe": dataframe}

validation_result = get_validation_result(checkpoint=checkpoint, batch_definition='xxx', batch_parameters=batch_parameters)

**Below is the error message

CheckpointRelatedResourcesFreshnessError: 
	Checkpoint 'my_checkpoint' has changed since it has last been saved. Please update with `<CHECKPOINT_OBJECT>.save()`, then try your action again.
---------------------------------------------------------------------------
CheckpointRelatedResourcesFreshnessError  Traceback (most recent call last)
File <command-4197947471275293>, line 1
----> 1 validation_result = get_validation_result(checkpoint=checkpoint, batch_definition='xxx', batch_parameters=batch_parameters)

File <command-4197947471275220>, line 5, in get_validation_result(checkpoint, batch_definition, batch_parameters, expectation_parameters)
      1 def get_validation_result(checkpoint: Checkpoint, batch_definition: str, batch_parameters: Dict, expectation_parameters: Dict):
      3     run_id = gx.RunIdentifier(run_name=f"validation_checkpoint_for_{batch_definition}", run_time=datetime.now())
----> 5     validation_result = checkpoint.run(batch_parameters, run_id=run_id)
      7     if not validation_result.success:
      8         print("Validation failed! Notification has been sent.")

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/great_expectations/checkpoint/checkpoint.py:182, in Checkpoint.run(self, batch_parameters, expectation_parameters, run_id)
    180         self._add_to_store()
    181     else:
--> 182         diagnostics.raise_for_error()
    184 run_id = run_id or RunIdentifier(run_time=dt.datetime.now(dt.timezone.utc))
    185 run_results = self._run_validation_definitions(
    186     batch_parameters=batch_parameters,
 
    187     result_format=self.result_format,
    188     run_id=run_id,
    189 )

File /local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/great_expectations/core/freshness_diagnostics.py:90, in _ParentFreshnessDiagnostics.raise_for_error(self)
     87 @override
     88 def raise_for_error(self) -> None:
     89     if not self.success:
---> 90         raise self.raise_for_error_class(errors=self.errors)

CheckpointRelatedResourcesFreshnessError: 
	Checkpoint 'my_checkpoint' has changed since it has last been saved. Please update with `<CHECKPOINT_OBJECT>.save()`, then try your action again.

Note: I have also tried checkpoint.save()  but the error still persists
	
Expected behavior
The checkpoint is expected to run and send a notification to a teams channel through the teams webhook provided.

Environment:

Operating System: Windows
Great Expectations Version: 1.0.3
Data Source: Spark Dataframe
Cloud environment: Databricks

**Comment by SSchotten** [comment]
My team is facing the exact same issue in the same environment (though with Slack notification action instead of MS Teams). 

[edit] fwiw, we use an ephemeral datacontext.

**Comment by adeola-ak** [comment]
hi there @Erua-chijioke @SSchotten i've been looking into this and at first I was not able to reproduce but in another example, I am now able to reproduce. Thanks for bringing this to our attention. I'm going to speak with some other folks about this, more information soon -- hopefully today

**Comment by adeola-ak** [comment]
The fix has been merged and will be included in the next release. Thank you for reporting this issue and for your patience as we worked to resolve it. @Erua-chijioke @SSchotten
