### ISSUE TITLE
Does the Library support Greater Than, Less than type validations?

### ISSUE THREAD

**Issue by skondoji** [great-expectations/great_expectations#10407]
Hi
I am Continuing my evaluation and surprisingly, I am not seeing a way to add Column validations like Greater than, Less than (column greater than 100 or column less than 20 ) etc.
I am using 1.0.x version
Does the library also support validations of computed columns? I do see some examples like Column A greater than Column B, but not something like column C = Column A times Column B. 

Thanks
Sri

**Comment by adeola-ak** [comment]
Great Expectations supports validations like greater than or less than on columns using the expect_column_values_to_be_between expectation. While direct validation of computed columns (e.g., Column C = Column A * Column B) is not available out of the box, this can be achieved by writing a [custom expectation](https://docs.greatexpectations.io/docs/core/customize_expectations/).

**Comment by skondoji** [comment]
Thank you @adeola-ak
