### ISSUE TITLE
[BUG] Checkpoint json files are being saved with the values substituted, not the placeholders

### ISSUE THREAD

**Issue by leodrivera** [great-expectations/great_expectations#10473]
**Describe the bug**
After the correction implemented by https://github.com/great-expectations/great_expectations/pull/10443, the checkpoint json files are being saved with the values substituted, not the placeholders. As this file is intended to be committed alongside the other gx config files, I believe this is not an intended behavior.

**To Reproduce**

        actions = [
            # This Action sends a Slack Notification if an Expectation fails.
            gx.checkpoint.SlackNotificationAction(
                name="send_slack_notification_on_failed_expectations",
                slack_token="${validation_notification_slack_token}",
                slack_channel="${validation_notification_slack_channel}",
                notify_on="failure",
                show_failed_expectations=True,
            ),
            gx.checkpoint.actions.UpdateDataDocsAction(
                name="update_my_site", site_names=[site_name]
            )
        ]
        context.checkpoints.add(
            gx.Checkpoint(
                name=checkpoint_name,
                validation_definitions=[
                    full_table_validator_definition,
                    daily_validator_definition,
                    card_token_daily_validator_definition,
                ],
                actions=actions,
            )
        )
Then execute a checkpoint.run()

**Expected behavior**
I think that the expected behavior should just be like the `connection_string` from the *add_or_update_postgres* method, where the placeholders are saved in the `great_expectations.yml` file.

**Environment (please complete the following information):**
Operating System: Ubuntu 22.04
Great Expectations Version: 1.1.0
Data Source: Redshift
Cloud environment: AWS

**Comment by adeola-ak** [comment]
closed by #10476
