### ISSUE TITLE
Problem with determining the data type, Pandas

### ISSUE THREAD

**Issue by Iriomo** [great-expectations/great_expectations#10538]
**Describe the bug**
_There is a problem with determining the data type, when running jupiter notepad and the location of the csv file in the system._

> !pip install great_expectations
> 
> import great_expectations as gx
> import pandas as pd
> from great_expectations.core.batch import BatchRequest, RuntimeBatchRequest
> import shutil
> import os
> 
> if os.path.exists("./context/gx"):
> shutil.rmtree("./context/gx")
> 
> context = gx.get_context(mode="file", project_root_dir="./context")
> 
> print(type(context).name)
> 
> source_folder = "C:\Users\.....\data"
> data_source_name = "my_filesystem_data_source"
> data_source = context.data_sources.add_pandas(name=data_source_name)
> 
> asset_name = "World Population"
> path_to_data = "C:\Users\....\data\world_population.csv"
> asset = data_source.add_csv_asset(asset_name, filepath_or_buffer=path_to_data)
**> ValidationError: 1 validation error for _PandasDataAsset
> type
> field required (type=value_error.missing)**

_I´m prescribing the type:_

> asset_name = "World Population"
> path_to_data = "C:\Users\....\GX\data\world_population.csv"
> asset = data_source.add_csv_asset(asset_name, filepath_or_buffer=path_to_data, type="csv")

_There is no mistake, let´s move on_
_With kwargs:_

> batch_definition_name = "World Population 2022"
> batch_definition = asset.add_batch_definition(
> name=batch_definition_name)
> 
> batch_parameters = {"reader_method": "read_csv"}
> batch = batch_definition.get_batch(batch_parameters=batch_parameters)
> print(batch.head())
**> BuildBatchRequestError: Bad input to build_batch_request: options is not currently supported for this DataAsset and must be None or {}.**

_Without kwargs:_

> batch_definition_name = "World Population 2022"
> batch_definition = asset.add_batch_definition(
> name=batch_definition_name)
> 
> batch = batch_definition.get_batch()
> print(batch.head())
**> NotImplementedError: One needs to explicitly provide "reader_method" for Pandas DataAsset extensions as temporary work-around, until "type" naming convention and method for obtaining 'reader_method' from it are established.**

**Environment (please complete the following information):**
 - Operating System: Windows 10
 - Great Expectations Version: 1.1.3
 - Data Source: Pandas

**Additional context**
_In this form, everything works fine on Windows 11._

> source_folder = "C:\\Users\\...\\GX\\data"
> data_source_name = "my_filesystem_data_source"
> data_source = context.data_sources.add_pandas(name=data_source_name)
> 
> asset_name = "World Population"
> path_to_data = "C:\\Users\\...\\world_population.csv"
> asset = data_source.add_csv_asset(asset_name, filepath_or_buffer=path_to_data)
> 
> batch_definition_name = "World Population 2022"
> batch_definition = asset.add_batch_definition(
>     name=batch_definition_name)
> 
> batch = batch_definition.get_batch()
> print(batch.head())

**Comment by adeola-ak** [comment]
hi there. It doesn't look like you are following the workflow outlined in our [documentation](https://docs.greatexpectations.io/docs/core/connect_to_data/dataframes/). Is there a reason why you have specified "reader_method"? You are also not correctly adding the csv data souce.

You may want to try this approach to simplify things:

```
!pip install great_expectations==1.1.3

import great_expectations as gx
import pandas as pandas
import shutil
import os

project_path = "/..."
csv_file_path = "/.../us_airline_fares.csv"

if os.path.exists(f"{project_path}/gx"):
    shutil.rmtree(f"{project_path}/gx")

dataframe = pandas.read_csv(csv_file_path)

context = gx.get_context(mode="file", project_root_dir=project_path)

data_source = context.data_sources.add_pandas("my_filesystem_data_source")
data_asset = data_source.add_dataframe_asset("US Airline Fares")
batch_definition = data_asset.add_batch_definition_whole_dataframe(
   "US Airline Fares Batch"
)

batch_parameters = {"dataframe": dataframe}
batch = batch_definition.get_batch(batch_parameters=batch_parameters)

print(batch.head())
```

Please let me know if this helps.

**Comment by Iriomo** [comment]
Yes, it helped! After that, the problems [described here](https://github.com/great-expectations/great_expectations/issues/10270) arose and i fixed everything. Thank you!
