### ISSUE TITLE
Can't apply conditional expectation using spark parser

### ISSUE THREAD

**Issue by pishGold** [great-expectations/great_expectations#10637]
I'm trying to run expectations on a spark DF, created by reading from a delta table on databricks.

I define the expectation as such:
expectation = gx.expectations.ExpectColumnValuesToNotBeNull(
    column="founded",
    condition_parser='spark',
    row_condition='company_id IS NOT NULL'
)

But no matter what I do, I keep getting an exception:
raise convert_exception(\npyspark.errors.exceptions.connect.AnalysisException: [CANNOT_RESOLVE_DATAFRAME_COLUMN] Cannot resolve dataframe column \"founded\". It's probably because of illegal references like `df1.select(df2.col(\"a\"))`

This happens only when using an expectation that requires a 'column' parameter.
For example, this expectation works fine:

 expectation = gx.expectations.ExpectTableRowCountToBeBetween(
    min_value=1500,
    condition_parser='spark',
    row_condition='company_id IS NOT NULL'
    )

I should state that converting the DF to a pandas DF and running with 'pandas' engine instead of 'spark' works, although performance is terrible...

**Comment by adeola-ak** [comment]
what version of GX are you using? I am not able to reproduce this. Can you maybe share your script

Here's my example from databricks, also reading from a delta table converted from databricks sample nyctaxi data:

```
df = spark.read.table("samples.nyctaxi.trips")
df.write.format("delta").mode("overwrite").save("/FileStore/tables")
delta_df = spark.read.format("delta").load("/FileStore/tables")

context = gx.get_context(mode="ephemeral")

data_source = context.data_sources.add_spark(name="nyc_taxi_data_source")
data_asset = data_source.add_dataframe_asset(name="nyc_taxi_data_asset")

batch_definition = data_asset.add_batch_definition_whole_dataframe("nyc_taxi_batch")

suite = gx.ExpectationSuite(name="nyc_taxi_suite")
context.suites.add(suite)

suite.add_expectation(gx.expectations.ExpectColumnValuesToNotBeNull(
column="tpep_pickup_datetime",
condition_parser='spark',
row_condition='trip_distance IS NOT NULL'
)
)

validation_definition = context.validation_definitions.add(gx.core.validation_definition.ValidationDefinition(
                            name="definition",
                            data=batch_definition,
                            suite=suite
                        )
                    )

checkpoint = context.checkpoints.add(
                        gx.Checkpoint(
                            name="checkpoint",
                            validation_definitions=[validation_definition],
                            result_format={
                                "result_format": "COMPLETE", 
                                "unexpected_index_column_names":["pickup_zip","tpep_pickup_datetime","fare_amount","trip_distance","tpep_dropoff_datetime","dropoff_zip"],
                            }
                        )
                    )

validation_results = checkpoint.run(batch_parameters={'dataframe': delta_df})
print(validation_results)
```

**Comment by pishGold** [comment]
Thank you,
I found the problem
It occurs only when running on a multi user cluster
Running on a single user cluster works fine.
