### ISSUE TITLE
Wrong count from expect_column_unique_value_count_to_be_between

### ISSUE THREAD

**Issue by rayjan0114** [great-expectations/great_expectations#10652]
**Describe the bug**
Wrong counting of label
**The correct count is 2231 while the API giving 4078**
In [2]: df.label.nunique()
Out[2]: 2231

In [3]: {type(l) for l in df.label}
Out[3]: {str}

`df.expect_column_unique_value_count_to_be_between("label", min_value=1287.3, max_value=2758.5)`

```
{
  "success": false,
  "expectation_config": {
    "expectation_type": "expect_column_unique_value_count_to_be_between",
    "kwargs": {
      "column": "label",
      "min_value": 1287.3,
      "max_value": 2758.5,
      "result_format": "BASIC"
    },
    "meta": {}
  },
  "result": {
    "observed_value": 4078,
    "element_count": 27,
    "missing_count": null,
    "missing_percent": null
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}
```

**Tried**
I have tried:
1. delete the whole environment and install again
2. install different versions:  0.15.50, 0.18.22

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.15.50, 0.18.22
 - Pandas Version: 2.2.3

**Comment by adeola-ak** [comment]
Hi there! Version 0.18 is no longer supported. We offer a comprehensive [migration guide](https://docs.greatexpectations.io/docs/reference/learn/migration_guide/?utm_campaign=General%20Community%20Promotion&utm_source=GitHub&utm_medium=post&utm_content=migration-guide), and after upgrading, I think you’ll find that version 1 is simpler and easier to use. If the issue still persists in v1, we’d be happy to investigate any miscount you encounter.
