### ISSUE TITLE
Get all expectations that gx supports

### ISSUE THREAD

**Issue by ayaan-ak-1** [great-expectations/great_expectations#10659]
If someone want to get all the expectations that GX supports they cannot get it right now.

Solution -
create a GX API which will give a comprehensive list of expectations with their parameters respectively

**Comment by adeola-ak** [comment]
hi there what do you mean by 'get all the expectations'? You are able to see the full list of supported expectations [here](https://greatexpectations.io/expectations/) Do you mind sharing how else you would want access to them?

**Comment by ayaan-ak-1** [comment]
So basically I am writing a wrapper on top of GX to provide all the supported expectations in a list format, where each item in the list will have the expectation type and the required parameters 

example :
[
{
    "name": "ExpectColumnDistinctValuesToBeInSet",
    "params": [
      "column",
      "value_set"
    ]
  },
  {
    "name": "ExpectColumnDistinctValuesToContainSet",
    "params": [
      "column",
      "value_set"
    ]
  }
  ]
  
  
  now to do this, Is there any way to get the names of these expectations (all in a single list) so that I can write this wrapper ?

**Comment by adeola-ak** [comment]
we have them in a repo [here](https://github.com/great-expectations/great_expectations/tree/develop/great_expectations/expectations/core)

**Comment by gloshkajian** [comment]
wait, doesn't this already exist?

```python
from great_expectations.expectations.registry import list_registered_expectation_implementations, get_expectation_impl

for name in list_registered_expectation_implementations():
    expectation_type = get_expectation_impl(name)
```

**Comment by adeola-ak** [comment]
> wait, doesn't this already exist?
> 
> ```python
> from great_expectations.expectations.registry import list_registered_expectation_implementations, get_expectation_impl
> 
> for name in list_registered_expectation_implementations():
>     expectation_type = get_expectation_impl(name)
> ```

oh wow! thanks for sharing! 

@ayaan-ak-1 hopefully this was helpful. with that, i'll be closing this issue.
