### ISSUE TITLE
Warning: Result Format

### ISSUE THREAD

**Issue by VytSep** [great-expectations/great_expectations#10699]
**Describe the bug**
Hi team,
i'm recieving the following message:

INFO:great_expectations.data_context.types.base:Created temporary directory '/tmp/tmp8h2win61' for ephemeral docs site
WARNING:py.warnings:/local_disk0/.ephemeral_nfs/cluster_libraries/python/lib/python3.10/site-packages/great_expectations/expectations/expectation.py:1518: UserWarning: `result_format` configured at the Validator-level will not be persisted. Please add the configuration to your Checkpoint config or checkpoint_run() method instead.
  warnings.warn(

I already remove the result format from the validator but i still having this warning:
**To Reproduce**
Here is my code:

        context = gx.get_context()
        asset = context.sources.add_spark(f"{self.deltaTable}_spark").add_dataframe_asset(f"{self.deltaTable}_df_asset")
        tempDf = ut.add_gx_temp_key(tempDf)
        context.add_or_update_expectation_suite(expectation_suite_name)
        validator = context.get_validator(
            batch_request=asset.build_batch_request(dataframe=tempDf), 
            expectation_suite_name=expectation_suite_name
        )
        meta = {"is_hard_expectation": True}
        validator.expect_column_values_to_not_be_null("column_a", meta=meta)
        validator.expect_column_values_to_be_between("date", None, str(date.today()), False, False, meta=meta)
        validator.expect_column_values_to_be_between("date_ts", None, str(datetime.now()), False, meta=meta)
validator.save_expectation_suite(discard_failed_expectations=False)

and the checkpoint is:
        checkpoint = Checkpoint(
            name=f"{self.deltaTable}-checkpoint",
            run_name_template=f"{self.source}-{self.deltaTable}-%Y-%m-%dT%H:%M:%S.%f%z",
            data_context=context,
            batch_request=asset.build_batch_request(dataframe=tempDf),
            expectation_suite_name=expectation_suite_name,
            action_list=[
                {"name": "store_validation_result", "action": {"class_name": "StoreValidationResultAction"}},
            ],
            runtime_configuration={
                "result_format": {"result_format": "COMPLETE", "unexpected_index_column_names": ["gx_temp_key"], "return_unexpected_index_query": True, "include_unexpected_rows": True}
            }
        )
        context.add_or_update_checkpoint(checkpoint=checkpoint)
        self.checkpoint_result = checkpoint.run()
        self.write_checkpoint_result()

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: [Windows]
 - Great Expectations Version: [e.g. 0.18.5]
 - Data Source: [Spark DF]
 - Cloud environment: [Databricks]

**Additional context**
How should I proceed in this situation?

Thank you!

**Comment by adeola-ak** [comment]
Hi there,

This is a known issue, but we won’t be addressing it in older versions as it works as expected in v1. You can try resolving the warning by specifying the result format at runtime, which will apply to all Expectations, however since version 0.18 is no longer supported, this bug will not be fixed, and I will be closing this issue. 

I encourage you to upgrade at your convenience! We offer a comprehensive and intuitive [migration guide](https://docs.greatexpectations.io/docs/reference/learn/migration_guide/?utm_campaign=General%20Community%20Promotion&utm_source=GitHub&utm_medium=post&utm_content=migration-guide) to assist you through the process.

Thank you for your understanding!
