### ISSUE TITLE
Unexpected Index list and Values not populating

### ISSUE THREAD

**Issue by chandruexf** [great-expectations/great_expectations#10741]
**Describe the bug**
When I use **result_format={'result_format': 'COMPLETE'}**, we expected the output to give us the unexpected index list, unexpected value list, but none of them are comming in the result, even I set the return_unexpected_index_query true.

**To Reproduce**
import great_expectations as ge
data_context = ge.get_context()
data_source = data_context.data_sources.add_pandas("pandas")
data_asset = data_source.add_dataframe_asset(name="pd dataframe asset")
data_batch_definition = data_asset.add_batch_definition_whole_dataframe("batch definition")

import pandas as pd
data = {
    "ID": [1, 2, 3, 4, 5],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve"],
    "Age": [25, 30, 35, 40, None],
    "City": ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"]
}

df = pd.DataFrame(data)

data_batch = data_batch_definition.get_batch(batch_parameters={"dataframe": df})
result = data_batch.validate(
    ge.expectations.ExpectColumnValuesToBeNull(
        column="Age", result_format={'result_format': 'COMPLETE'}
    )
) 
print the result you wont be able to see the unexpected index list and values.

**Expected behavior**
{
  "success": false,
  "expectation_config": {
    "type": "expect_column_values_to_be_null",
    "kwargs": {
      "result_format": {
        "result_format": "SUMMARY",
        "return_unexpected_index_query": false
      },
      "batch_id": "pandas-pd dataframe asset",
      "column": "Age"
    },
    "meta": {}
  },
  "result": {
    "element_count": 5,
    "unexpected_count": 4,
    "unexpected_percent": 80.0,
    "unexpected_list":[
      25.0,
      30.0,
      35.0,
      40.0
    ],
    "unexpected_index_list":[
      0,
      1,
      2,
      3
    ],
    "partial_unexpected_list": [
      25.0,
      30.0,
      35.0,
      40.0
    ],
    "partial_unexpected_counts": [
      {
        "value": 25.0,
        "count": 1
      },
      {
        "value": 30.0,
        "count": 1
      },
      {
        "value": 35.0,
        "count": 1
      },
      {
        "value": 40.0,
        "count": 1
      }
    ],
    "partial_unexpected_index_list": [
      0,
      1,
      2,
      3
    ]
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}.

**Environment (please complete the following information):**
 - Operating System: [Windows]
 - Great Expectations Version: [1.2.4]
 - Data Source: [Pandas]
 - Cloud environment: []

**Additional context**

**Comment by chandruexf** [comment]
I think None of the result format is working, please check.

**Comment by adeola-ak** [comment]
Hi there. Can you try passing `result_format` to a checkpoint or validation definition as our [documentation](https://docs.greatexpectations.io/docs/core/run_validations/run_a_validation_definition?procedure=instructions) suggests. The way you have set it is incorrect for v1 which is causing the result format to be the default value of "SUMMARY" 

Example:
```
checkpoint = context.checkpoints.add(
    gx.Checkpoint(
        name="checkpoint",
        validation_definitions=[validation_definition],
        actions=[gx.checkpoint.actions.UpdateDataDocsAction(name="datadocs-action")],
        result_format= {"result_format": "COMPLETE"}
    )
)
```

or 

`validation_results = validation_definition.run(result_format={"result_format": "COMPLETE"})
`

**Comment by adeola-ak** [comment]
As the result format is being incorrectly set on an expectation, I will be closing this issue
