### ISSUE TITLE
Update Guide: "How to update Data Docs as a Validation Action" to v3, removing validation_operators in the instructions.

### ISSUE THREAD

**Issue by bhcastleton** [great-expectations/great_expectations#3602]
The Guide: "How to update Data Docs as a Validation Action" still references validation operators and needs to be updated to the v3 methods for updating data docs.

See documentation here: 
https://docs.greatexpectations.io/docs/guides/validation/validation_actions/how_to_update_data_docs_as_a_validation_action

**Comment by austiezr** [comment]
Resolved in #4087
