### ISSUE TITLE
Site rendering fails for expect_column_pair_values_to_be_equal

### ISSUE THREAD

**Issue by rdodev** [great-expectations/great_expectations#5328]
**Describe the bug**
Datadoc site rendering fails when using `expect_column_pair_values_to_be_equal` expectation and one of the column contains nulls or empty.

**To Reproduce**
```
Column_A Column_B
12345    12345
40318    null
54321    54321
```
2. run the expectation above

**Expected behavior**
The datadoc site to render properly

**Environment (please complete the following information):**
 - Operating System: OS X
 - Great Expectations 0.15.9

**Additional context**
There was a fix a few months ago pertaining to [multicolumn_map expectations](https://github.com/great-expectations/great_expectations/pull/4336/files) which may serve as guide for fix.

**Comment by nateGarcia** [comment]
Thanks for this! I figured it might be relevant to also include in this fix, separating the unexpected values in the chart output. The values get concatenated together.
<img width="818" alt="Screen Shot 2022-06-17 at 10 28 26 AM" src="https://user-images.githubusercontent.com/87150335/174318604-a020e7e6-78eb-44e7-b4fc-4c62eaca0b20.png">

**Comment by rdodev** [comment]
This is no longer an issue.
