### ISSUE TITLE
[FEATURE] Show SQL alongside with Expectation results in DataDocs

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#7405]
When you see an issue in DataDocs (with sampled values) it would be great to have an option to see a SQL corresponding to that issue - just to help Data Stewards find the same records in the database being checked really QUICKLY. 
Same SQL as generated during the Expectation execution should be presented here.

Same approach could work for Spark backends (just treat a dataframe as a temp view)

![image](https://user-images.githubusercontent.com/49131090/226371062-c407fc36-cd59-41b8-b3ed-5f487ed0a24f.png)

**Comment by alexsherstinsky** [comment]
Hi, @kujaska -- and thank you for bringing up this idea!  I will be sure to forward it to our Product Management Team for consideration.  Thanks again. /cc @talagluck

**Comment by talagluck** [comment]
Hi @kujaska, thanks for suggesting a feature! I think what you are describing is possible today using the `unexpected_index_query` [as shown here.](https://docs.greatexpectations.io/docs/reference/expectations/result_format/#behavior-for-summary). I'm going to close this issue for now, but if you have any trouble using it, please don't hesitate to ask in our Slack. And if you have additional feature ideas, please add them here!
