### ISSUE TITLE
[DOCS] How to configure Checkpoints store in Amazon S3

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#7435]
Is there a manual How to configure Checkpoints store in Amazon S3?

Nothing here - Customize your deployment page
https://docs.greatexpectations.io/docs/reference/customize_your_deployment/#additional-checkpoints-and-actions

**Comment by austiezr** [comment]
Hey @kujaska! We don't have any extant docs on configuring a CheckpointStore; however, the process is the same as other metadata stores. You should be able to adapt [this guide](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_validation_result_store_in_amazon_s3) and successfully configure the store.

Thanks for surfacing this; we'll review our docs in this area.
