### ISSUE TITLE
type-checking problems Upgrading from 0.15.50 to 0.16.1.

### ISSUE THREAD

**Issue by jmcorreia** [great-expectations/great_expectations#7436]
**Description**
Hey all, I am trying to migrate GX from 0.15.50 to 0.16.1 but getting errors on linting my code with flake8 (4.0.1) and mypy (0.961).

- E.G.: BaseDataContext is not valid as a type -> change my logic to use great_expectation.get_context and use AbstractDataContext and that was solved.
- assistant.py:57: error: "DataAssistantRunner" has no attribute "run" -> This one I am not being able to solve and not seeing any change in documentation referring the need to change the way we call the assistant. I am using: **context.assistants.onboarding.run(...)** which is what is mentioned in the documentation
- (Error on **map_metric** defining custom expectation) -> error: Incompatible types in assignment (expression has type "str", base class "MulticolumnMapExpectation" defined the type as "None")
- (Error on **success_keys** defining custom expectation) -> error: Incompatible types in assignment (expression has type "Tuple[str, str, str]", base class "MulticolumnMapExpectation" defined the type as "Tuple[str]")

Any help or idea how to solve this? Any place where I can see the expected changes while migrating?
For context, I am using Spark, reading from a runtime DataFrame.

**Expected behavior**
No complains from the lint.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.1

**Comment by Kilo59** [comment]
I believe the cause of this is the addition of the `py.typed` file. Specifically, it was added to the top-level `great_expectations` package. It should have only been added for packages that are fully typed.

https://peps.python.org/pep-0561/#packaging-type-information

Will try to get this fixed for the next release.
