### ISSUE TITLE
[BUG] Package conflict - pydantic with Airflow 2.2.3

### ISSUE THREAD

**Issue by itaise** [great-expectations/great_expectations#7461]
**Describe the bug**
Hi, 
We are using GX on Airflow 2.2.3, and trying to upgrade to the latest version - 0.16.3 we have a package conflict. 

Since [this PR](https://github.com/great-expectations/great_expectations/commit/68752af349bfa5b8d7b654390efe790b7097f787), GX depends on pydantic 1.10.4 which depends on typing-extensions>=4.2.0. 

The issue is that[ Airflow 2.2.3 ](https://raw.githubusercontent.com/apache/airflow/constraints-2.2.3/constraints-3.7.txt)depends on typing-extensions 3.10.0.2, so we get a conflict when building our env. 

Can you loosen the range of pydantic so it will be compatible with this old-ish Airflow version? 
Thanks a lot!

**Comment by talagluck** [comment]
Thanks for raising this, @itaise! I'm not sure whether this will be possible, but we will review and be in touch.

**Comment by Kilo59** [comment]
@itaise 
Can you move to Airflow `2.3.1` or later?

https://raw.githubusercontent.com/apache/airflow/constraints-2.3.1/constraints-3.7.txt

We rely on some features in `pydantic 1.10.4` for our new Fluent Datasources. It should be possible but we'd have to make some code changes to loosen this dependency.

**Comment by itaise** [comment]
Thanks @Kilo59, I will check internally.

**Comment by ariksa1** [comment]
Hi @Kilo59, 
I wonder if more GX consumers raise that the dependency as well? 
Although 2.2.3 is not a new version, but it's defiantly not old enough for packages conflict. Many organization not upgrade airflow on a quarterly basis and it will be problematic if we will need to do so. 
Thanks for your kindly investigation, we are waiting for your check respond. 
BTW, we do plan to upgrade airflow version in the following months, but till than we can't make any change that require new version.

**Comment by Kilo59** [comment]
@ariksa1 Thanks for the context here.
We are working on loosening the dependencies here to make us compatible with `2.2.3`, and adding steps to prevent this kind of issue from happening again.
Expect this to be part of this week's release.

**Comment by itaise** [comment]
Thank you so much @Kilo59 ! much appreciated.
