### ISSUE TITLE
Drivername in docs not compatible with recent change to SQLAlchemy >= 1.4 as lower bound

### ISSUE THREAD

**Issue by HuhtaLauri** [great-expectations/great_expectations#7464]
**Describe the bug**

In recent release, we set the lower bound for SQLAlchemy to version 1.4. With the version 1.4, SQLAlchemy dropped the use of "postgres" as drivername and "postgresql" must be used instead.

On this page in [docs](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_postgresql_data) we are still guiding to use "postgres" and this will not work.

In the next docs update, could we change the variable of drivername to "postgresql" so others won't face this issue in the future.

**Comment by talagluck** [comment]
Thanks for raising this and opening the corresponding PR @Itzblend! We will review and be in touch.
