### ISSUE TITLE
Databricks Error - py4j.security.Py4JSecurityException: Constructor public org.apache.spark.SparkConf(boolean) is not whitelisted

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#7555]
Details - https://github.com/great-expectations/great_expectations/issues/3538

While this issue is not reproducible on Databricks Community 11.3 LTS (includes Apache Spark 3.3.0, Scala 2.12),
it **is reproducible** on AWS Databricks 12.2 LTS Shared cluster (includes Apache Spark 3.3.2, Scala 2.12)
with great_expectations-0.16.5-py3-none-any.whl

Many thanks to @dbeswick-bupa - monkey-patch from https://github.com/great-expectations/great_expectations/issues/3538 works!

Please consider merging the monkey-patch to core library...

**Comment by rdodev** [comment]
Hey @kujaska thanks for bringing this up. I'll make engineering aware of the issue and monkey patch.

**Comment by molliemarie** [comment]
Hello @kujaska. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗

**Comment by molliemarie** [comment]
Closing
