### ISSUE TITLE
Expectation suite not found: Great_expectation error on Windows

### ISSUE THREAD

**Issue by Rashmikoparde** [great-expectations/great_expectations#7556]
I am working with great_expectations version 0.15.7. My operating system is Windows. I am validating data present in Azure blob storage. While executing the code, I get expectation_suite not found even if the expectation_suite is available. 
While debugging I found out that in **/great_expectations/data_context/store/tuple_store_backend.py::TupleAzureBlobStoreBackend**, 
the line **az_blob_key = os.path.relpath(obj.name)** doesn't work for Windows system. 
My code worked when I changed above code line to **az_blob_key = obj.name**.

**Environment :**
 - Operating System: Windows
 - Great Expectations Version: 0.15.7

**Comment by rdodev** [comment]
Hey @Rashmikoparde thanks for raising this issue. Unfortunately GX doesn't officially support Windows environments. While changing that line makes it work for Windows, it likely breaks for unix based OSs. That having been said, I have noted this as a feature request and Product will take into consideration.

**Comment by austiezr** [comment]
Hey @Rashmikoparde ! Closing this out for now as we've captured this for our backlog. Thank you! 🚀
