### ISSUE TITLE
Specified Key does not exist/Access denied : While building data docs | AWS EMR or AWS EMR Serverless

### ISSUE THREAD

**Issue by abhishek0603** [great-expectations/great_expectations#7586]
**Describe the bug**

Getting 'Specified Key does not exist / Access denied' error while building data docs in AWS EMR and EMR Serverless.

**To Reproduce**

As per the great expectations guide, boto3_options needs to be added in data_doc site specified in great_expectations.yml

![image](https://user-images.githubusercontent.com/84580625/230633858-04466a64-cf1c-49f6-8e41-d381e3b615cc.png)

while executing the following command in AWS EMR serverless or EMR environment,

![image](https://user-images.githubusercontent.com/84580625/230635688-2a3c115b-143b-4da9-87e2-c431651292e8.png)

getting this error: 

![image](https://user-images.githubusercontent.com/84580625/230637854-f4bffa47-8531-4c6b-b75d-b8eb93d67941.png)

When I remove boto3_options from data doc sites in great_expectations.yml then it throws 'Access denied error' but data doc is being generated successfully in the s3 bucket which I have configured in great_expectations.yml but causing EMR serverless job to get failed.

![image](https://user-images.githubusercontent.com/84580625/230639275-bff415a4-3d25-4740-baa0-7446262b6810.png)

**Expected behavior**
EMR serverless job shouldn't be failed. It should be success with no errors.

**Environment (please complete the following information):**
 - Operating System: [Ubuntu EMR serverless]
 - Great Expectations Version: [e.g. 0.16.3]

**Additional context**
In local jupyter notebook, this seems to be working fine(no errors). No boto3_options is specified in great_expectations.yml(for data doc site)

Getting below output in the local when the same command is executed.

![image](https://user-images.githubusercontent.com/84580625/230642490-db9e1c68-c825-4569-bdac-6242217bae09.png)

Please let me know if any other info needs to be provided.

Thanks,
Abhishek

**Comment by austiezr** [comment]
Hey @abhishek0603! Thanks for raising this. We'll review and be in touch.

**Comment by abhishek0603** [comment]
Any update on this ?

**Comment by molliemarie** [comment]
Hello @abhishek0603. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
