### ISSUE TITLE
Streaming Data - Checkpoint Results over Time (e.g., as a Line Chart)

### ISSUE THREAD

**Issue by Buedenbender** [great-expectations/great_expectations#7590]
**Is your feature request related to a problem? Please describe.**
I have streaming data; A database is updated daily e.g. with data from multiple sensors (tempretature, velocity, throughput). With a Runtime (Query) Connector and a handcrafted expectation suite I got a good way of testing my expectation for each new day. However I would like to have a plot comparable to the one in the readme of great expectations, that allows me to track the daily results in one convenient plot. E.g. below ![Screenshot_2023-04-09-17-33-26-417_com.github.android.jpg](https://user-images.githubusercontent.com/38650857/230782319-d7cc8a62-673f-4d49-ac11-7610553266aa.jpg)
 

**Describe the solution you'd like**
A plot for expectations for streaming data over time (comparable to the profiler across multiple batches)

Ideally the result of a new day would just be appended to all previous runs of this checkpoint, and not require for each new day that all previous days need to be computed again. 

... More details soon

**Why/Benefits**
This would enable one to see if a (daily) batch is just a temporary outlier / exception (e.g. a day with heavy demand) or if the data fundamentally shifted and the new values are the new ground truth.

**Comment by austiezr** [comment]
Hey @Buedenbender! Thanks for raising this.

We've captured this Feature Request for review in our backlog. I'll leave this Issue open for the next week if you have any further comments or context.

**Comment by austiezr** [comment]
Hey @Buedenbender! Closing this out as we've captured this for our backlog. Thank you! 🚀

**Comment by Buedenbender** [comment]
This appears also related to issue #7161 where the question was for a metric store, which as far as I know is already available ([link](https://docs.greatexpectations.io/docs/guides/setup/configuring_metadata_stores/how_to_configure_a_metricsstore/ ). The plots could be constructed based on the metric store
