### ISSUE TITLE
The table.column_type metric can't be calculated when using SQLAlchemy backend with RuntimeDataConnector and create_temp_table set to False

### ISSUE THREAD

**Issue by dreamofi** [great-expectations/great_expectations#7593]
**Describe the bug**
This is probably the root cause for this issue: https://github.com/great-expectations/great_expectations/issues/7316
Currently I'm trying to generate the expectation suite with the UserConfigurableProfiler and  SQLAlchemy backend (connecting to AWS RDS MySQL). My user doesn't have the permission to create temp table, so I pass the parameter create_temp_table: False to the execution engine.
I've seen the following behaviors:
- Triggering the **UserConfigurableProfiler** with **RuntimeDataConnector** results in `KeyError: 'type'` error related to the `expect_column_values_to_be_in_type_list` expectation. When I remove the create_temp_table parameter, the profiler runs successfully.
- Switching from **RuntimeBatchRequest**  to **ConfiguredAssetDataConnector** (while keeping the create_temp_table False) results in the profiler runs successfully.

Upon further investigation, it has dawn on me that the problem actually lies with the calculation of "table.column_type" metric in  the file /expectations/metrics/util.py, so using either OnboardingDataAssistant or UserConfigurableProfiler will still give out error.

In function `get_sqlalchemy_column_metadata()`, with `create_temp_table: False` then the column metadata will be fetched by running this line:

```
if isinstance(table_selectable, TextClause):
    if hasattr(table_selectable, "selected_columns"):
        columns = table_selectable.selected_columns.columns
    else:
--->>   columns = table_selectable.columns().columns
```

However, with the way SQLAlchemy working with TextClause object, it will return an empty list, and as such it will fallback to column_reflection_fallback() function. Since this function does not do much for mysql dialect, it just returns a list of column name without the type, and so we get the `KeyError: type error`. To temporarily fix this, I've added this code:

```
def column_reflection_fallback(
    selectable: Select, dialect: Dialect, sqlalchemy_engine: Engine
) -> List[Dict[str, str]]:
    """If we can't reflect the table, use a query to at least get column names."""
    col_info_dict_list: List[Dict[str, str]]
    if dialect.name.lower() == "mssql":
      ...
    elif dialect.name.lower() == "trino":
      ...
    # The addition code is from here, since I can only test with mysql at the moment, I explicitly only check for mysql dialect
    elif dialect.name.lower() == "mysql":
        if isinstance(selectable, TextClause):
            query: TextClause = selectable
        else:
            query = sa.select(sa.text("*")).select_from(selectable).limit(1)
        result_object = sqlalchemy_engine.execute(query)
        # noinspection PyProtectedMember

        col_names: List[str] = result_object.keys()

        # To get column types need to use the cursor.description, and since it return Type code
        # it's needed to have a dict to retrieve the type in String.
        # This dict is obtained from here: https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/constants/FIELD_TYPE.py
        column_types: List[str] = [desc[1] for desc in result_object.cursor.description]
        MySqlTypeCode = {
            0: "DECIMAL",
            1: "CHAR",
            2: "SHORT",
            3: "LONG",
            4: "FLOAT",
            5: "DOUBLE",
            6: "NULL",
            7: "TIMESTAMP",
            8: "LONGLONG",
            9: "INT24",
            10: "DATE",
            11: "TIME",
            12: "DATETIME",
            13: "YEAR",
            14: "NEWDATE",
            15: "VARCHAR",
            16: "BIT",
            245: "JSON",
            246: "NEWDECIMAL",
            247: "INTERVAL",
            252: "TEXT",
            253: "VAR_STRING",
            254: "STRING"
        }
        get_dialect_name = dialect.name.lower()
        get_dialect_type = getattr(sa.dialects, get_dialect_name)
        # to get the type similar to that returned by the inspector in normal case, need to convert type name to dialect type instance
        col_info_dict_list = [
            {"name": name, "type": getattr(get_dialect_type.types, MySqlTypeCode[typ])()}
            for name, typ in zip(col_names, column_types)
        ]
    else:
       ...
```

**Environment (please complete the following information):**
 - Operating System: Windows/Linux
 - Great Expectations Version tested: 0.15.50 to 0.16.5
 - Databases: AWS RDS MySQL, MySQL 5.7 
 - Backend: SQLAlchemy

**Comment by austiezr** [comment]
Hey @dreamofi! Thanks for raising this. We'll review and be in touch.

**Comment by dreamofi** [comment]
Hello, I want to update more on this.
First of all it's not the root cause for this issue: https://github.com/great-expectations/great_expectations/issues/7316. The issue 7316 talked about the `expect_column_values_to_be_unique`, and thus the underlying metrics to be calculated is different from our issue here, which is about the `expect_column_values_to_be_in_type_list` with `table.column_type` metric.

Moreover, the adhoc code fix that I posted may cause problem when the returned data type doesn't have relevant class of MySQL dialect in SQLAlchemy.
So this is the one that should work better:
```
def column_reflection_fallback(
    selectable: Select, dialect: Dialect, sqlalchemy_engine: Engine
) -> List[Dict[str, str]]:
    """If we can't reflect the table, use a query to at least get column names."""
    col_info_dict_list: List[Dict[str, str]]
    if dialect.name.lower() == "mssql":
      ...
    elif dialect.name.lower() == "trino":
      ...
    # The addition code is from here, since I can only test with mysql at the moment, I explicitly only check for mysql dialect
    elif dialect.name.lower() == "mysql":
        if isinstance(selectable, TextClause):
            query: TextClause = selectable
        else:
            query = sa.select(sa.text("*")).select_from(selectable).limit(1)
        result_object = sqlalchemy_engine.execute(query)
        # noinspection PyProtectedMember

        col_names: List[str] = result_object.keys()

        # To get column types need to use the cursor.description, and since it return Type code
        # it's needed to have a dict to retrieve the type in String.
        # This dict is obtained from here: https://github.com/PyMySQL/PyMySQL/blob/main/pymysql/constants/FIELD_TYPE.py
        column_types: List[str] = [desc[1] for desc in result_object.cursor.description]
        MySqlTypeCode = {
            0: "DECIMAL",
            1: "CHAR",
            2: "INT",
            3: "INT",
            4: "FLOAT",
            5: "DOUBLE",
            6: "NULL",
            7: "TIMESTAMP",
            8: "BIGINT",
            9: "INT",
            10: "DATE",
            11: "TIME",
            12: "DATETIME",
            13: "YEAR",
            14: "DATE",
            15: "VARCHAR",
            16: "BIT",
            245: "JSON",
            246: "DECIMAL",
            247: "INTERVAL",
            252: "TEXT",
            253: "TEXT",
            254: "TEXT",
        }
        get_dialect_name = dialect.name.lower()
        get_dialect_type = getattr(sa.dialects, get_dialect_name)
        # to get the type similar to that returned by the inspector in normal case, need to convert type name to dialect type instance
        col_info_dict_list = [
            {"name": name, "type": getattr(get_dialect_type.types, MySqlTypeCode[typ], sa.types.NullType)()}
            for name, typ in zip(col_names, column_types)
        ]
    else:
       ...
```

**Comment by ddsr-ops** [comment]
@dreamofi Thanks for tracking this, I met the case similar to you. I use the fix code you posted overcome the case .

**Comment by molliemarie** [comment]
Hello @dreamofi. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
