### ISSUE TITLE
expectations get duplicated in the results+statistics when the spark executor hits exceptions

### ISSUE THREAD

**Issue by paul-felt** [great-expectations/great_expectations#7659]
**Describe the bug**
A single expectation gets reported as many expectations in the results list and stats when
1. you run on spark backend
2. the expectation results in an exception (eg, malformed regex)

**To Reproduce**

this snippet reproduces

```
import pandas as pd
from datetime import datetime

import great_expectations as gx
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.core.yaml_handler import YAMLHandler
from great_expectations.core.expectation_configuration import ExpectationConfiguration

yaml = YAMLHandler()

context = gx.get_context()

datasource_config = {
    "name": "taxi_datasource",
    "class_name": "Datasource",
    "module_name": "great_expectations.datasource",
    "execution_engine": {
        "module_name": "great_expectations.execution_engine",
        "class_name": "SparkDFExecutionEngine",
    },
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
        },
    },
}
context.add_datasource(**datasource_config)


# We're going to create a single expectation here that raises an exception (it's a malformed regex)
context.add_expectation_suite(
	expectation_suite_name="my_expectation_suite",
	id=None,
	expectations=[
		ExpectationConfiguration(**{
			"expectation_type": "expect_column_values_to_match_regex",
			"kwargs": {
				"column": "passenger_count",
				"regex": "[1",
				"batch_id": "default_pandas_datasource-#ephemeral_pandas_asset"
			}
		})
	]
)


checkpoint_config = {
    "name": "my_checkpoint",
    "config_version": 1,
    "class_name": "SimpleCheckpoint",
    "validations": [
        {
            "batch_request": {
                "datasource_name": "taxi_datasource",
                "data_connector_name": "default_runtime_data_connector_name",
                "data_asset_name": "taxi_data",
            },
            "expectation_suite_name": "my_expectation_suite",
        }
    ],
}
context.add_or_update_checkpoint(**checkpoint_config)

spark = gx.core.util.get_or_create_spark_application()
pdf = pd.read_csv("https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv")
df = spark.createDataFrame(pdf)

results = context.run_checkpoint(
    checkpoint_name="my_checkpoint",
    batch_request={
        "runtime_parameters": {"batch_data": df},
        "batch_identifiers": {
            "default_identifier_name": ""
        },
    },
)

# we just ran one expectation -- we should get just one result
assert 1 == len(list(results["run_results"].values())[0]["validation_result"]["results"])
assert 1 == list(results["run_results"].values())[0]["validation_result"]["statistics"]["evaluated_expectations"]

```

**Expected behavior**
The two asserts at the end should pass: you should get a single expectation result and report just 1 "evaluated_expectations".  This is the case for pandas, but not spark. Instead I see 6 of them
```
{
  "evaluated_expectations": 6,
  "successful_expectations": 0,
  "unsuccessful_expectations": 6,
  "success_percent": 0.0
}
```

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.7

**Additional context**
Didn't test extensively, but I also noticed it affecting expectations that reference non-existent columns, so I don't think it's regex-specific.

**Comment by austiezr** [comment]
Hey @paul-felt! Thanks for raising this. We'll review this behavior and be in touch.

**Comment by molliemarie** [comment]
Hello @paul-felt. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
