### ISSUE TITLE
Injecting an already available connection

### ISSUE THREAD

**Issue by akghosh1232003** [great-expectations/great_expectations#7733]
**Is your feature request related to a problem? Please describe.**
We have an ETL Platform where we will be executing the GX. The DB connection will be injected by ETL platform, so our need is to re-use the same connections instead of GX to create one using the DB connection details

**Describe the solution you'd like**
Re-using an already available connection instead of GX to create one using the DB connection details

**Describe alternatives you've considered**
Currently I am managing 2 connections,  first connection is created by GX with the connection details provided and second connection which ETL framework provided.

**Comment by austiezr** [comment]
Hey @akghosh1232003! Thanks for raising this.

We've captured this Feature Request for our internal backlog; I'll close this issue out in one week, please feel free to leave any further context in the meantime.
