### ISSUE TITLE
expect_compound_columns_to_be_unique fails upon a Snowflake Binary field - TypeError bytearray cannot be serialized

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#7805]
**Describe the bug**
expect_compound_columns_to_be_unique fails upon a Snowflake Binary field with error:

TypeError: bytearray(b'b\xbb\nWf\xbc\xdd~^a\x') is of type bytearray which cannot be serialized.

Error is raised **only if records with issues are found** - looks like GE can’t handle binary result correctly.

**To Reproduce**
```
create TABLE test_ge_compound_chk (
	table_PK BINARY(8388608) NOT NULL,
	START_FROM DATE NOT NULL,
	test_attr VARCHAR(16777216)
);


--add 1 row:
insert into test_ge_compound_chk
values ('368292D3C897186734D4A5E4CE673BD6',date '2023-05-01', 'test');

run a checkpoint upon an expectation suite with expect_compound_columns_to_be_unique expectation:

 {
      "expectation_type": "expect_compound_columns_to_be_unique",
      "kwargs": {
        "column_list": [
          "table_pk",
          "start_from"
        ]
      },
      "meta": {}
    }

and get Success because no issues were found.

--Add one more row with same values to produce duplicates on compound_columns:
insert into test_ge_compound_chk
values ('368292D3C897186734D4A5E4CE673BD6',date '2023-05-01', 'test')
;

run the checkpoint again and get the error:
TypeError: bytearray(b'b\xbb\nWf\xbc\xdd~^a\x') is of type bytearray which cannot be serialized.

```

**Expected behavior**

GE works fine with binary fields without this error.

**Environment (please complete the following information):**
 - Operating System: Linux,
 - Great Expectations Version: 0.16.8

**Additional context**

**Workaround:**

add VARCHAR field in Checkpoint and check VARCHAR - it will work fine

```
query: "SELECT TO_VARCHAR(table_PK) as table_PK_, 
t.*
from test_ge_compound_chk  t"
```

**Comment by austiezr** [comment]
Hey @kujaska ! Thanks for raising this. We'll review this behavior.

**Comment by alexsherstinsky** [comment]
Hello, @kujaska -- I am looking at this issue now; thank you so much for reporting it.  Could you please provide a full stack trace of the error leading to the `TypeError`, which you encountered?  In addition, your exact Python code, including the line causing the exception would be extremely valuable to us in terms of trying to reproduce the issue.  Thank you very much, and thanks for using GX!

**Comment by alexsherstinsky** [comment]
@kujaska I am closing this issue for now. Please feel free to reopen and let us know at any time. Thank you very much for using GX!
