### ISSUE TITLE
StoreMetricsAction updates AWS S3 w/ '__' filename

### ISSUE THREAD

**Issue by ren0nie0** [great-expectations/great_expectations#7856]
StoreMetricsAction updates AWS S3 w/ '__' filename

  A key, value pair of the desired metric is output albeit to a file named '__' which is not desirable for future use.

I have added the following action in my checkpoint:

 name: store_metrics
    action:
      class_name: StoreMetricsAction
      target_store_name: metric_store
      requested_metrics:
        expectation_name_test:
          - expect_table_row_count_to_equal.result.observed_value

My metricstore store is configured as follows:

  metric_store:
    class_name: MetricStore
    store_backend:
      class_name: TupleS3StoreBackend
      bucket: s3_bucket
      prefix: /metric_store

I expected an .JSON file to be output with a more informant filename.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.11

**Comment by tjholsman** [comment]
Hi @ren0nie0, thanks for reporting this and including all the pertinent information. We've currently only built full support for MetricStore with DatabaseStoreBackend using Postgres, but we'll take a look.

**Comment by molliemarie** [comment]
Hello @ren0nie0. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
