### ISSUE TITLE
Creating BatchRequest fails for AWS Athena

### ISSUE THREAD

**Issue by bossenti** [great-expectations/great_expectations#7869]
**Describe the bug**
When trying to create a `BatchRequest` to instantiate a validator for a AWS Athena table with below code a DB error is returned (see below). We were able to trace this error down to the creation of the temporary table in [`SQLAlchemyBatchData`](https://github.com/great-expectations/great_expectations/blob/46054d91139717ea2b832f06be96238a54b31584/great_expectations/execution_engine/sqlalchemy_batch_data.py#L154). Here the dialect is not correctly retrieved from the SQLalchemy engine. The code ends up with the dialect `GXSqlDialect.OTHER` which yields to executing the wrong SQL command ( `TEMPORARY` does not exist in Athena).
This is due to the wrong dialect name for Athena in `GXSqlDialect`, which is `athena` instead of `awsathena` (see the naming in PyAthena: https://github.com/laughingman7743/PyAthena/blob/master/pyathena/sqlalchemy/base.py#L862).
The mapping recently changed in GX with this commit: https://github.com/great-expectations/great_expectations/commit/b2ec0c8c6bdb99475f80e6987d40de8cd230bf6f

**To Reproduce**
```python
context = gx.get_context()

con_str = "awsathena+rest://@athena.eu-central-1.amazonaws.com/?s3_staging_dir=s3://some-s3-bucket"

datasource_dict = {
    "name": "my_awsathena_datasource",
    "class_name": "Datasource",
    "execution_engine": {
        "class_name": "SqlAlchemyExecutionEngine",
        "module_name": "great_expectations.execution_engine",
        "connection_string": con_str,
    },
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
            "module_name": "great_expectations.datasource.data_connector",
        },
        "default_inferred_data_connector_name": {
            "class_name": "InferredAssetSqlDataConnector",
            "module_name": "great_expectations.datasource.data_connector",
            "include_schema_name": "true",
        },
    },
}

context.add_datasource(**datasource_dict)

suite = context.add_expectation_suite(expectation_suite_name="test")

batch_request = {
    "datasource_name": "my_awsathena_datasource",
    "data_connector_name": "default_inferred_data_connector_name",
    "data_asset_name": f"demo_db.demo_table",
    "limit": 1000,
}

validator = context.get_validator(
    batch_request=BatchRequest(**batch_request),
    expectation_suite_name="test",
)
```

> sqlalchemy.exc.DatabaseError: (pyathena.error.DatabaseError) An error occurred (InvalidRequestException) when calling the StartQueryExecution operation: line 1:8: mismatched input 'TEMPORARY'. Expecting: 'MATERIALIZED', 'OR', 'ROLE', 'SCHEMA', 'TABLE', 'VIEW'
[SQL: CREATE TEMPORARY TABLE "gx_temp_f4b22884" AS SELECT * 
FROM demo_db.demo_table 
WHERE true]

**Expected behavior**
BatchRequest could be created/loaded for Athena table

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.12

**Comment by bossenti** [comment]
I could also come up with a PR, but I don't really know which consequences this may have

**Comment by tjholsman** [comment]
Hi @bossenti, thanks for logging this and doing the detective work! We would definitely welcome a PR submission. Our [contributing doc](https://github.com/great-expectations/great_expectations/blob/develop/CONTRIBUTING_CODE.md) offers guidance on how to work with the repo, run tests, and submit the PR. We'll review it and suggest any changes if necessary.

Let me know if you're interested!

**Comment by bossenti** [comment]
thanks for getting back @tjholsman 

Sure, then I'll just come up with a PR 🙂

**Comment by tjholsman** [comment]
Great, thank you!

**Comment by kenwade4** [comment]
Should be fixed by https://github.com/great-expectations/great_expectations/pull/7950
