### ISSUE TITLE
'Datasource' object has no attribute 'add_query_asset'

### ISSUE THREAD

**Issue by samlotti** [great-expectations/great_expectations#7912]
Hi,

**Describe the bug**
Want to add a sql query to my data source, 

follow the page: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data_using_a_query
to add a query but the data source does not have the method.

To reproduce, follow the quick start, create a data source, then try to add the query.

import great_expectations as gx
context = gx.get_context()
datasource = context.get_datasource("imydatasource")

>> <great_expectations.datasource.new_datasource.Datasource object at 0x0000019405844090>

table_asset = datasource.add_query_asset(name="my_asset", query="SELECT passenger_count, total_amount FROM yellow_tripdata")

>> AttributeError: 'Datasource' object has no attribute 'add_query_asset'

**Expected behavior**'
Expect to be able to add the query to the data source.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.16.12

**Comment by Kilo59** [comment]
Sorry about that `.add_query_asset()` is a method for our newer "Fluent" `SQLDatasource` types.

Despite the name `new_datasource.Datasource`, is an older Datasource type and it doesn't implement this newer method.

You can still continue to use this datasource but you should reference the 0.15 documentation.
https://docs.greatexpectations.io/docs/0.15.50/guides/connecting_to_your_data/connect_to_data_overview

Or you can re-create your datasource as one of our new "Fluent" datasources.
https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview

The linked Pull Request adds better error messages for this. It will be part of the release next week `0.16.14`. If you want access to these better error messages right away you can always install `GX` directly from the Github develop branch.
https://pip.pypa.io/en/stable/topics/vcs-support/
