### ISSUE TITLE
'Datasource' object has no attribute 'get_asset'

### ISSUE THREAD

**Issue by r-findley** [great-expectations/great_expectations#7921]
**Describe the bug**
Attempt to connect to a data asset to create expectations

**To Reproduce**
follow the page: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/batch_requests/how_to_request_data_from_a_data_asset
to access the asset but the data source does not have the method.

To reproduce, follow the quick start, create a data source, then try to access the asset.

import great_expectations as gx
context = gx.get_context()
datasource = context.get_datasource("imydatasource")

<great_expectations.datasource.new_datasource.Datasource object at 0x0000019405844090>

AttributeError: 'Datasource' object has no attribute 'get_asset'

Expected behavior'
Expect to be able to access the data asset

Environment (please complete the following information):

Operating System: Windows
Great Expectations Version: 0.16.12

**Comment by Kilo59** [comment]
Sorry about that. We should have a better error message here. `.get_asset()` is a method for our newer "Fluent" datasource types.

Despite the name `new_datasource.Datasource`, is an older Datasource type and it doesn't implement this newer method.

You can still continue to use this datasource but you should reference the `0.15` documentation.
https://docs.greatexpectations.io/docs/0.15.50/guides/connecting_to_your_data/connect_to_data_overview

Or you can re-create your datasource as one of our new "Fluent" datasources.
https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/connect_to_data_overview
