### ISSUE TITLE
Quick guide validation result incorrectly opens in Edge

### ISSUE THREAD

**Issue by vfg222** [great-expectations/great_expectations#7948]
**Describe the bug**
I'm trying out the [quickstart](https://docs.greatexpectations.io/docs/tutorials/quickstart/) guide, and when I try to view the validation result the Microsoft Edge browser opens to the start page, instead of the expected data documentation. My default browser is Firefox. I'm executing the code in a notebook in jupyter lab. The complete code that I run is

```
import great_expectations as gx

context = gx.get_context()

validator = context.sources.pandas_default.read_csv(
    "https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv"
)

validator.expect_column_values_to_not_be_null("pickup_datetime")
validator.expect_column_values_to_be_between("passenger_count", auto=True)

checkpoint = gx.checkpoint.SimpleCheckpoint(
    name="my_quickstart_checkpoint",
    data_context=context,
    validator=validator,
)

checkpoint_result = checkpoint.run()

validation_result_identifier = checkpoint_result.list_validation_result_identifiers()[0]
print(validation_result_identifier)
context.open_data_docs(resource_identifier=validation_result_identifier)
```

**Expected behavior**
I expect the specific validation result page in the Data Docs to be displayed in my default browser (Firefox) when I run `context.open_data_docs(resource_identifier=validation_result_identifier).`

**Environment**
- OS: Windows 11 Home
- Python Version: 3.10.11
- Great Expectations Version: 0.16.12

**Additional context**
If I run
```
context.open_data_docs()
```
instead of 
```
context.open_data_docs(resource_identifier=validation_result_identifier)
```
the browser opens correctly in firefox.

I'm new to Great Expectations and learning it through the quick guide. Any help would be much appreciated. Thanks!

**Comment by tjholsman** [comment]
Hi @vfg222, thanks for reaching out! We currently only offer limited support for Windows but will review this to potentially address in the future. The workaround we would advise is to call `context.open_data_docs()` without arguments, as you described.
