### ISSUE TITLE
Not able to use custome query expectation

### ISSUE THREAD

**Issue by swapnilborude04062000** [great-expectations/great_expectations#7951]
**Describe the bug**
No provider found for query.table using PandasExecutionEngine.

**To Reproduce**
1. Go to 'https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations' created the custom query expectation template file as per given instructions and with the same query and example =[] given
2. Ran it using the instructions in  'https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations' In which I have used the validator as given below : validator = context.sources.pandas_default.read_csv(
    "https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv"
)

**Expected behavior**
I have used the same query in custom query expectation template instruction..so since I am following your example only I am expecting to run the custom query to return the result but getting error

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [0.16.13]

**Additional context**

**Comment by tjholsman** [comment]
Hi @swapnilborude04062000, thanks for reporting this! We only support custom query Expectations for SQL and Spark datasources. This is noted in the [docs](https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_query_expectations): `QueryExpectations are a type of Expectation, enabled for SQL and Spark`

Depending on your use case, you may be able to use `pandasql` to run queries, then pass the resultant dataframes to GX for validation. Hope this helps and let us know if you have additional feedback or questions.
