### ISSUE TITLE
Data Docs: Broken validation links

### ISSUE THREAD

**Issue by jkingdon-ms** [great-expectations/great_expectations#7954]
**Describe the bug**
After running any great expectation validations, the Data Docs home page is generated and links to each validation run. The problem is, those links are invalid. This bug is reflected regardless of data_docs_sites destination and has been verified locally and via Azure Blob Storage.

Here's my reference code:
```python
import great_expectations as gx

context = gx.get_context()

validator = context.sources.pandas_default.read_csv(
    "https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv"
)

validator.expect_column_values_to_not_be_null("pickup_datetime")
validator.expect_column_values_to_be_between("passenger_count", auto=True)

checkpoint = gx.checkpoint.SimpleCheckpoint(
    name="my_quickstart_checkpoint",
    data_context=context,
    validator=validator,
)

checkpoint_result = checkpoint.run()

validation_result_identifier = checkpoint_result.list_validation_result_identifiers()[0]
context.build_data_docs()
context.open_data_docs(resource_identifier=validation_result_identifier, site_name="local")
```

**To Reproduce**
1. Run Great Expectations code above and view the validation run
2. Click 'Home' in the top left
3. Click any Validation Run listed on the homepage
4. Error, file not found

**Expected behavior**
1. Run Great Expectations code above and view the validation run
2. Click 'Home' in the top left 
3. Click any Validation Run listed on the homepage
4. Validation Run is viewable

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.13

**Additional context**
I've observed that there is a discrepancy between the URL generated from Step 1 and Step 4. The URL that works uses the character encoding for '#' (e.g. `default_pandas_datasource-%23ephemeral_pandas_asset.html`) while the broken link uses the no encoding for '#' (e.g. `default_pandas_datasource-#ephemeral_pandas_asset.html`) .

**Comment by tjholsman** [comment]
Hey @jkingdon-ms, thanks for reporting this and submitting a PR! We'll close this once the PR is merged.

**Comment by NathanFarmer** [comment]
PR is merged. Thanks @jkingdon-ms!

**Comment by jkingdon-ms** [comment]
Thanks everyone!
