### ISSUE TITLE
Not able to use custom expectations as part of checkpoint

### ISSUE THREAD

**Issue by karthigai-selvan** [great-expectations/great_expectations#7972]
**Describe the bug**
I have created a custom expectations and was able to test it in jupyter notebook by running great_expectations suite new command with below commands

from great_expectations.expectations.registry import (
    get_expectation_impl,
    register_expectation,
)

from expectations.expect_column_values_not_to_be_future_date import ExpectColumnValuesNotToBeFutureDate

register_expectation(ExpectColumnValuesNotToBeFutureDate)

But once I create a checkpoint with the mentioned suite and run it I am getting expect_column_values_not_to_be_future_date not found error. But as mentioned in the docs I have put my custom expectation in plugins/expectations directory.

**To Reproduce**

**Expected behavior**
Though I am not yet contributed my custom expectation to great_expectations git repo, I should be able to use it for my purpose in my dev environments.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.16.13

**Additional context**

**Comment by kujaska** [comment]
While this guide may help
 https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations/

I would suggest for GX team to add automatic import feature for plugins folder

**Comment by karthigai-selvan** [comment]
Hi @kujaska I have followed this document only while running "from expectations.expect_query_count_with_filter_to_meet_threshold import ExpectQueryCountWithFilterToMeetThreshold" in jupyter notebook it works but after creating a checkpoint/suite which are json based files I am not able to use the custom expectations and it throws an error expect_query_count_with_filter_to_meet_threshold does not found. please find the suite in json format as follows:

{
  "data_asset_type": null,
  "expectation_suite_name": "test",
  "expectations": [
    {
      "expectation_type": "expect_query_count_with_filter_to_meet_threshold",
      "kwargs": {
        "condition_parser": "great_expectations__experimental__",
        "query": " SELECT * from tablename where to_timestamp (\"date_column\"::bigint::text,'YYYYMMDD')::date > CURRENT_DATE",
        "template_dict": {
          "col": "\"STATUS\"",
          "filter": "'Active'"
        },
        "threshold": 1
      },
      "meta": {}
    }
  ],
  "ge_cloud_id": null,
  "meta": {
    "citations": [
      {
        "batch_request": {
          "data_asset_name": "xxxxxxxxx",
          "data_connector_name": "default_configured_data_connector_name",
          "datasource_name": "postgres_datasource",
          "limit": 1000
        },
        "citation_date": "2023-05-22T15:47:16.001670Z",
        "comment": "Created suite added via CLI"
      }
    ],
    "great_expectations_version": "0.15.50"
  }
}

**Comment by tjholsman** [comment]
Hi @karthigai-selvan thanks for reaching out! In the code where you are running the checkpoint, are you also importing the custom expectation? You'll need to import the custom expectation in order for the checkpoint to be able to locate it.

**Comment by karthigai-selvan** [comment]
Hi @tjholsman,
I have created a checkpoint(yml file) and running it through CLI using the command(great_expectations checkpoint run <checkpointname> and also I have put my custom expectation file in /great_expectations/plugins/expectations folder but I am getting an error stating <expectation_name> not found. How can I import the custom expectation in checkpoint yml file?

**Comment by karthigai-selvan** [comment]
Additionally, I have referred the how to guide on how to use custom expectations(link: [ https://github.com/great-expectations/great_expectations/blob/develop/docs_rtd/guides/how_to_guides/creating_and_editing_expectations/how_to_create_custom_expectations.rst](url)  It is mentioned like         7. **Import**: To use a custom Expectation, you need to ensure it has been imported into the running python interpreter. While including the module in your `plugins/` directory will make it *available* to import, you must still import the Expectation:
but since the checkpoint is yml file and suite is json file how can I import the custom expectation that present in plugins/ directory?

**Comment by tjholsman** [comment]
Hi @karthigai-selvan, you should be able to use the v0.15.50 version of this doc https://docs.greatexpectations.io/docs/0.15.50/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations to help you create a script for your checkpoint that you can then execute via the CLI.

`great_expectations checkpoint script <my_checkpoint_name>`

Then create and save a script for your checkpoint as shown.

Then you can run the checkpoint via `python great_expectations/uncommitted/run_my_checkpoint_name.py`

Please also be advised that [we have deprecated the CLI](https://greatexpectations.io/blog/a-fond-farewell-to-the-cli) and recommend using Python going forward for running checkpoints.
