### ISSUE TITLE
AttributeError: 'FileDataContext' object has no attribute '_write_vars'

### ISSUE THREAD

**Issue by franciskuttivelil** [great-expectations/great_expectations#7979]
I am trying to run Great Expeectations on Matillion whihc is hosted on CentOS. The GX version is 0.16.13.
I am following this [document](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/instantiating_data_contexts/how_to_explicitly_instantiate_an_ephemeral_data_context/)

But I am getting the following error :- 

```
Traceback (most recent call last):
  File "/tmp/interpreter-input-e8381e41-5ad6-4e1d-b3f9-62939a474914.tmp", line 10, in <module>
    context._write_vars()
AttributeError: 'EphemeralDataContext' object has no attribute '_write_vars'
```

When I just try to implement 
`context = gx.get_context()`

I get the below error

```
Traceback (most recent call last):
  File "/tmp/interpreter-input-a7e1d7d2-ac02-4df4-bafd-d4bc5068ad3d.tmp", line 13, in <module>
    context._write_vars()
AttributeError: 'FileDataContext' object has no attribute '_write_vars'
```

Please help.

**Comment by tjholsman** [comment]
Hi @franciskuttivelil, thanks for reaching out! Could you include your complete code so we can review it?

**Comment by franciskuttivelil** [comment]
Below is the code:

```
from great_expectations.data_context.types.base import (DataContextConfig,InMemoryStoreBackendDefaults)
from great_expectations.data_context import EphemeralDataContext

project_config = DataContextConfig(store_backend_defaults=InMemoryStoreBackendDefaults())
context = EphemeralDataContext(project_config=project_config) 
```

**Comment by tjholsman** [comment]
Thanks, @franciskuttivelil! Which python and CentOS versions are you using? That will help us in trying to reproduce and troubleshoot the error.

**Comment by franciskuttivelil** [comment]
We are using Centos 7 and Python 3.8

**Comment by franciskuttivelil** [comment]
@tjholsman Wondering if you were able to replicate the issue?

**Comment by tjholsman** [comment]
@franciskuttivelil we will take a look but please be advised that given our support for Centos may be limited given the status of Centos.

**Comment by alexsherstinsky** [comment]
Hello, @franciskuttivelil -- I am looking into this now (sorry for the delay).  We have not worked with Matillion, but I do not see why CentOS should be a problem.  I will get back to you shortly.  Thank you for your patience.

**Comment by alexsherstinsky** [comment]
One more request, please: @franciskuttivelil -- could you please provide the full stack trace with line numbers?  You are welcome to reach me in the GX Community Slack (we might need to schedule a troubleshooting session via Zoom).  Thanks!

**Comment by franciskuttivelil** [comment]
It seems the issue was with my environment. My default python was version 2 instead of 3
Thanks @alexsherstinsky and @tjholsman
