### ISSUE TITLE
Documentation Update: Google Cloud Composer Path

### ISSUE THREAD

**Issue by TheEverlastingBish** [great-expectations/great_expectations#8015]
**Describe the bug**

When using `BashOperator` in Google Cloud Composer, the path in the documentation needs to be updated ... 
from: `/home/airflow/gcsfuse/great_expectations/`
to: `/home/airflow/gcsfuse/actual_mount_path/great_expectations/`

[Existing Documentation Link](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_with_google_cloud_platform_and_bigquery)

---

**To Reproduce**
Steps to reproduce the behaviour:

1. Build a DAG using a `BashOperator` with the path currently in the documentation and in the GitHub example: https://github.com/great-expectations/great_expectations/blob/develop/tests/integration/fixtures/gcp_deployment/ge_checkpoint_bigquery.py

2. Load this DAG to Google Cloud Composer with an existing Great Expectations folder setup and trigger it.

3. See error like `FileNotFound` for the checkpoint file. The DAG is being accessed fine but it cannot find the `great_expectations` folder.

---

**Expected behavior**

I would expect the DAG to find the checkpoint file and run it normally.

**Environment (please complete the following information):**
 - Operating System: Linux, Google Cloud Composer 2 ( `composer-2.2.0-airflow-2.4.3` )
 - Great Expectations Version: `0.16.12`, `0.16.13`, `0.16.14`

**Additional context**

**Comment by austiezr** [comment]
Hey @TheEverlastingBish! Thanks for raising this. We'll review this documentation and update as needed. 🙇
