### ISSUE TITLE
How to use row_condition for Spark and SQLAlchemy (Not documented)

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#8022]
**Describe the bug**

Not complete documentation page -
https://docs.greatexpectations.io/docs/reference/expectations/conditional_expectations/

**1) it does not explain how to use row_condition for SQLAlchemy**

At least this condition works in 0.16.x (JSON example):
```

        "condition_parser": "great_expectations__experimental__",
        "row_condition": "col(\"my_column_name\")!=\"My text\" and col(\"my_column2_name\")!=\"My text\""
```

- notice col() syntax not mentioned in the docs at all
- make sure you have **no spaces around "!="** 

**2) it looks like GE has a dedicated spark condition_parser not explained, too**

At least this condition works in 0.16.x (JSON example):
```

        "condition_parser": "spark",
        "row_condition": "my_date > DATE \"2001-01-01\"",

```
**To Reproduce**

Open documentation page
https://docs.greatexpectations.io/docs/reference/expectations/conditional_expectations/
and read ;)

**Expected behavior**

Documentation is up to date.

**Environment (please complete the following information):**
 - Operating System:  Linux, 
 - Great Expectations Version:  0.16.x

**Comment by austiezr** [comment]
Hey @kujaska ! Thanks for raising this. We'll review the relevant documentation and update as necessary. 🙇

**Comment by molliemarie** [comment]
Hello @kujaska. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
