### ISSUE TITLE
Support for Polars

### ISSUE THREAD

**Issue by jordan-carson** [great-expectations/great_expectations#8023]
**Is your feature request related to a problem? Please describe.**
Feature request to add polars data frame support to great_expectations. 

**Describe the solution you'd like**
Addition of polars as a data source, data_set, execution_engine, configured_asset, inferred_asset, and all of the above.

**Describe alternatives you've considered**
Pandas is great, but other libraries and frameworks have emerged over the past few years that perform better, see [DuckDB Benchmarks](https://duckdblabs.github.io/db-benchmark/). As these new technologies are released and used by the data analytics/science/AI community, great expectations can leverage such opportunities to widen its support. 

**Additional context**
[Polars User Guide](https://pola-rs.github.io/polars-book/user-guide/)
[Polars GitHub](https://github.com/pola-rs/polars)

Have begun researching the requirements, i.e. the folders within the repo that will need to be added. There's a good amount of work involved, I will be reaching out in the Slack community as well.

**Comment by austiezr** [comment]
Hey @jordan-carson! Thanks for raising this; we've captured this feature request for our internal backlog. We're currently reviewing a best path forward for new Execution Engines, as this has [previously been requested](https://github.com/great-expectations/great_expectations/issues/5503). I'll leave this Issue open for the next week if you have any further context you'd like to provide, at which point I'll close this out.

**Comment by jordan-carson** [comment]
Is this completed or still in development by the polars team?

**Comment by lmmx** [comment]
This issue has reappeared for a third time:

- https://github.com/great-expectations/great_expectations/issues/9649
