### ISSUE TITLE
Error When Using Data Profiler on a Postgres Source

### ISSUE THREAD

**Issue by andrewp-nextphase** [great-expectations/great_expectations#8028]
When using the data profiler with the OnboardingDataAssistant on my Postgres table I am running into an error when running it (I am using default configs from the jupyter notebook). ValueError: zero-size array to reduction operation minimum which has no identity. I've tried profiling a similar table with Snowflake and it seems to work fine. I've attached the full stacktrace here.
The  version i'm using is version 0.15.47 if that helps.
[error_log.txt](https://github.com/great-expectations/great_expectations/files/11603996/error_log.txt)

**Comment by austiezr** [comment]
Hey @andrewp-nextphase! Thanks for reaching out.

Are you able to share your OS, as well as the exact workflow generating this error, and an example of the data in the column `"Amount "`, as this is explicitly referenced in the error log? That will help us to better diagnose what may be happening here.

**Comment by alexsherstinsky** [comment]
Hello, @andrewp-nextphase -- thank you for reporting this issue and providing the informative error log file.  In this file, I am seeing exceptions concerning `col("Amount ").notnull()` -- is it possible that the actual column name should not contain the blank space?  Right now, I am seeing the column named as "Amount " (i.e., with the blank space at the end).  This may be causing a problem.  Please let us know, and also, if you could please provide your full code example and some idea of what the test data should be, it would greatly help us in terms of being able to reproduce it.  Thanks a lot, and thanks for using GX!

**Comment by alexsherstinsky** [comment]
@andrewp-nextphase I am hoping that our suggestions helped. I am closing this issue for now. Please feel free to reopen and let us know at any time. Thank you very much for using GX!
