### ISSUE TITLE
Variable Substitution not working with Secret Managers (Azure Key Vault)

### ISSUE THREAD

**Issue by SashiDareddy** [great-expectations/great_expectations#8034]
**Describe the bug**
In [How to Configure Credentials](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials) we are told that if we add a prefix such as `secret|<url to Azure Key Vault identifier >` then Gx can retrieve the connection string stored in Azure Key Vault [AKV]. 

In GX 0.15.34 I could pass `secret|https://my-vault-name.vault.azure.net/secrets/my-secret` as my connection string (here `my-secret`  refers to a Postgres connection string) in the YAML and it worked exactly as the document linked above said it would. However, in the latest version this doesnt seem to be the case. Instead SQL alchemy directly tries to use the literal value: `secret|https://my-vault-name.vault.azure.net/secrets/my-secret` and fails with the message: `Something went wrong when trying to use SQLAlchemy to obfuscate URL: Could not parse SQLAlchemy URL from string "secret|https://my-vault-name.vault.azure.net/secrets/my-secret" `

The actual variable substitution of AKV identifier to actual connection string is handled via [_ConfigurationSubstitutor](https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/core/config_substitutor.py#L28). I can manually use this class by doing the following:

Before I run the following I make sure to set the AZURE_CLIENT_ID, AZURE_TENANT_ID, AZURE_CLIENT_SECRET to appropriate values as environment variables so that authentication to AKV is successful. 
```python
from functools import partial
from great_expectations.core.config_substitutor import _ConfigurationSubstitutor

sub_value = partial(
_ConfigurationSubstitutor().substitue_config_variable, config_variables_dict={}
)

sub_value("secret|https://my-vault-name.vault.azure.net/secrets/my-secret" ) # this correctly returns the connection string stored in AKV
```

**To Reproduce**
1. Try adding a SQL data source where you provide the connection string as `secret|<your-azure-key-vault-identifier>` eg: `secret|https://my-vault-name.vault.azure.net/secrets/my-secret`

**Expected behavior**
As described in [How to Configure Credentials](https://docs.greatexpectations.io/docs/guides/setup/configuring_data_contexts/how_to_configure_credentials) - whenever GX sees a string starting with `secret|` it should attempt to substritute that strng with the actual value in the chosen Secrets Manager

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: issue detected in version: 0.16.14 (`great_expectations[azure_secrets]==0.16.14`) it works in 0.15.34 `great_expectations[azure_secrets]==0.15.34`

**Additional context**

**Comment by SashiDareddy** [comment]
I noticed that the variable substitution does work if set an environment variable like `export CONNECTION_STRING=secret|https://my-vault-name.vault.azure.net/secrets/my-secret` and then do 
`context.sources.add_sql(name="myds", connection_string="${CONNECTION_STRING}")` then under fluent data sources the connection_string will be listed as ${CONNECTION_STRING} in the yaml. This is definetly a breaking change from before but at least now I know how to get around the issue.

**Comment by austiezr** [comment]
Hey @SashiDareddy! Thanks for raising this (and providing a workaround). We'll review this functionality and address. 🙇

**Comment by Kilo59** [comment]
@SashiDareddy can you provide the full stacktrace from the 
`Something went wrong when trying to use SQLAlchemy to obfuscate URL: Could not parse SQLAlchemy URL from string "secret|https://my-vault-name.vault.azure.net/secrets/my-secret" ` error?

**Comment by alexsherstinsky** [comment]
@SashiDareddy I am hoping that our suggestions helped.  I am closing this issue for now. Please feel free to reopen and let us know at any time.  Thank you very much for using GX!
