### ISSUE TITLE
[BUG] New release causing Data Docs rendering issue

### ISSUE THREAD

**Issue by data-han** [great-expectations/great_expectations#8041]
**Describe the bug**
With the upgrade to the latest version 0.16.14, I'm facing issues when rendering Data Docs and seem like the issue is caused by the recent changes with the new release. There is also no link in slack notification.

![image](https://github.com/great-expectations/great_expectations/assets/51312880/20e23367-eb42-423c-9ebc-f0e8f81fd625)
![image](https://github.com/great-expectations/great_expectations/assets/51312880/e48a21c6-2e7c-4d6b-902a-2c97aef0b1cb)
![image](https://github.com/great-expectations/great_expectations/assets/51312880/4841f889-5800-40b0-9e2f-8b10101d29d3)
![image](https://github.com/great-expectations/great_expectations/assets/51312880/22bdec14-fbb9-4404-8501-80d5324dc1f4)

**To Reproduce**

**Expected behavior**
Data Docs should be rendered properly without throwing any error

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows] MacOS
 - Great Expectations Version: [e.g. 0.13.2] 0.16.14

**Additional context**

**Comment by tjholsman** [comment]
Should be fixed by https://github.com/great-expectations/great_expectations/pull/8044

**Comment by austiezr** [comment]
Hey @data-han! Thanks for raising this. Closing out as resolved by #8044 , but feel free to re-open if this continues to be an issue on `0.16.15`.
