### ISSUE TITLE
WARNING - Regex is not supported for dialect snowflake

### ISSUE THREAD

**Issue by thisisdope** [great-expectations/great_expectations#8048]
**Describe the bug**
Expectation `expect_column_values_to_match_regex` fails with warning `WARNING - Regex is not supported for dialect snowflake` after update from version 0.15.41 to version 0.16.13. 

**To Reproduce**
execute for a snowflake datasource
```
import great_expectations as gx
import great_expectations.jupyter_ux
from great_expectations.core.batch import BatchRequest
from great_expectations.exceptions import DataContextError

context = gx.data_context.DataContext()

batch_request = {
    "datasource_name": "snowflake_datasource",
    "data_connector_name": "default_inferred_data_connector_name",
    "data_asset_name": "schema_xyz.view_xyz",
    "limit": 1000,
}

expectation_suite_name = "sample.warning"

validator = context.get_validator(
    batch_request=BatchRequest(**batch_request),
    expectation_suite_name=expectation_suite_name,
)

validator.expect_column_values_to_match_regex(
    column="col_xyz",
    regex="^\d{1,16}\.{0,1}\d{0,2}$",
)

```

**Expected behavior**
Expectation runs without error.

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows] Windows
 - Great Expectations Version: [e.g. 0.13.2] 0.16.13
 - Datasource: Snowflake

**Additional context**

**Comment by austiezr** [comment]
Hey @thisisdope! Thanks for raising this. We'll review this functionality.

**Comment by austiezr** [comment]
Hey @thisisdope! Just reaching out to let you know that we've captured this work for our internal backlog and will be addressing. Thank you! 🚀

**Comment by kenwade4** [comment]
@thisisdope what versions of `snowflake-connector-python` and `snowflake-sqlalchemy` were you running before and after the upgrade?

**Comment by kenwade4** [comment]
Fixed in https://github.com/great-expectations/great_expectations/pull/8403
