### ISSUE TITLE
TypeError: dataclass_transform() got an unexpected keyword argument 'field_specifiers' - Databricks

### ISSUE THREAD

**Issue by richbenmintz** [great-expectations/great_expectations#8097]
Using Databricks runtime 12.2 LTS, I am unable to import the latest version of great expectations into a python notebook

![image](https://github.com/great-expectations/great_expectations/assets/12468093/94ad7445-08b3-4142-be7c-e8994d39c216)

Reproduce Steps:
- Install great expectations as a cluster library
- create a python notebook
- run the following code in a cell
- `import great_expectations`

**Expected behavior**
The library is expected to import successfully

**Environment (please complete the following information):**
 - Azure Databricks
 - Great Expectations Version: 0.16.16
 - Azure - Databricks

**Additional context**
Imports successfully by downgrading databricks to runtime 11.3 LTS

**Comment by Kilo59** [comment]
What version of `pydantic` and `typing_extensions` are in your environment?

See related issues 
https://github.com/explosion/spaCy/issues/12034
https://github.com/pydantic/pydantic/issues/4885

**Comment by richbenmintz** [comment]
Hi @Kilo59, 

I have pinned typing-extensions to 4.5.0, but have not explicitly installed pydantic in my virtual env. this package incompatabilty occured about a month ago with great-expectations and it seems like the recent release has introduced the same issue.

**Comment by austiezr** [comment]
Hey @richbenmintz; we've had some motion in this area over the past month, and believe this should now be resolved on latest versions. If this is still an issue for you, please feel free to re-open!
