### ISSUE TITLE
context.sources.add_sql doesn't work with environment vars

### ISSUE THREAD

**Issue by Plozano94** [great-expectations/great_expectations#8099]
**Describe the bug**
Using context.sources.add_sql to add a fluent database doesn't work with environment vars (It doesn't replace the vars before testing the connection). Also this way it's recommended in [the docs](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_sql_data) 

**To Reproduce**
Empty data context and then:
```
import great_expectations as gx

from great_expectations.datasource.fluent.interfaces import (
    Datasource as FluentDatasource,
)

context = gx.get_context()

connection_string = "postgresql+psycopg2://username:${POSTGRES_PASSWORD}@$host:port/database"
context.sources.add_sql(name="test",connection_string=connection_string)
```

**Expected behavior**
Adding the expectation correctly 

**Environment (please complete the following information):**
 - Operating System: Ubuntu 22
 - Great Expectations Version: 0.16.16
 - Datasource: Fluent
 - Cloud environment: None

**Additional context**

**Comment by austiezr** [comment]
Hey @Plozano94 ! Thanks for raising this. We'll review this behavior and address.

**Comment by Kilo59** [comment]
@Plozano94 yeah, this was my mistake. We were doing a `re.match` instead of `re.search` to look for the config template syntax.

This fix should make it into the release this Thursday but if you need an immediate workaround you can put your whole connection string in an environment variable and the substitution should work.
```python
import great_expectations as gx

context = gx.get_context()

context.sources.add_sql(name="test",connection_string="${MY_FULL_PG_CONN_STR}")
```

**Comment by Plozano94** [comment]
Thank you both!
