### ISSUE TITLE
expect_column_most_common_value_to_be_in_set unexpectedly fails for DateType column in pyspark

### ISSUE THREAD

**Issue by mbassennesm** [great-expectations/great_expectations#8161]
- Create a spark dataframe with a single column with DateType. 
- Validate against the rule "expect_column_most_common_value_to_be_in_set" where the value set is a list with a single element (tried with both datetime.type and string type values in Python).
- The validation fails even though the validation object shows this ( observed value is the same as value set element but fails to validate?!):

```
 {
      "exception_info": {
        "exception_message": null,
        "exception_traceback": null,
        "raised_exception": false
      },
      "expectation_config": {
        "expectation_type": "expect_column_most_common_value_to_be_in_set",
        "kwargs": {
          "batch_id": "feddfd34bae72c55769bfbd96946fe1e",
          "column": "date_col",
          "value_set": [
            "2023-06-20"
          ]
        },
        "meta": {},
      },
      "meta": {},
      "result": {
        "observed_value": [
          "2023-06-20"
        ]
      },
      "success": false
    },
```

**Comment by HaebichanGX** [comment]
Hi @mbassennesm thank you for raising this issue. We would need more context from your environment to understand the issue. Can you share more info on error message, your environment? 

Here's an example of another issue raised by another user: https://github.com/great-expectations/great_expectations/issues/8153

**Comment by mbassennesm** [comment]
@HaebichanGX (is this better/ok?)

Please find below the complete code to reproduce:

```
!pip install great_expectations==0.16.10
```

```
# Imports

import great_expectations as gx

from datetime import datetime
from pyspark.sql import functions as F
from ruamel import yaml
```

```
# Basic Spark session

spark_config = {
    "spark.executor.instances": 1,
    "spark.executor.memory": '2G',
    "spark.executor.cores": 1,
    "spark.driver.cores": 1,
    "spark.driver.memory": '2G',
}

spark = gx.core.util.get_or_create_spark_application(
    spark_config=spark_config,
)

spark
```

```
# Test dataframe

date_str = "2023-01-01"

data = spark.createDataFrame([
    {
        "date_str": "2023-01-01",
    },
])

data = data.withColumn("date_date", F.col("date_str").cast("date"))
data = data.withColumn("date_ts", F.col("date_str").cast("timestamp"))

data.printSchema()

data.show()
```

```
context = gx.util.get_context()

datasource_config = {
    "name": "datasource_name",
    "class_name": "Datasource",
    "execution_engine": {"class_name": "SparkDFExecutionEngine"},
    "data_connectors": {
        "data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["batch_id"],
        }
    },
}

# context.test_yaml_config(yaml.dump(datasource_config))
context.add_datasource(**datasource_config)

batch_request =gx.core.batch.RuntimeBatchRequest(
    datasource_name="datasource_name",
    data_connector_name="data_connector_name",
    data_asset_name="data_asset_name",  # This can be anything that identifies this data_asset for you
    batch_identifiers={"batch_id": "default_identifier"},
    runtime_parameters={"batch_data": data},  # Your dataframe goes here
)

validator = context.get_validator(
    batch_request=batch_request,
)
```

```
# SANITY CHECK

validator.expect_column_most_common_value_to_be_in_set(
    column="date_str",
    value_set=[date_str],
)
```

```
# FAILS :-(

date_object = datetime.strptime(date_str, '%Y-%m-%d').date()
print(date_object, type(date_object))

datetime_object = datetime.strptime(date_str, '%Y-%m-%d')
print(datetime_object, type(datetime_object))

validator.expect_column_most_common_value_to_be_in_set(
    column="date_date",
    value_set=[date_object, datetime_object, date_str],
)
```

**THIS SHOULD PASS, BUT IT FAILS (SEE OUTPUT BELOW)**
```
{
  "success": false,
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  },
  "result": {
    "observed_value": [
      "2023-01-01"
    ]
  }
}
```

**Comment by HaebichanGX** [comment]
Hi @mbassennesm yes! I'll add it to our backlog. To confirm, is this on a mac?

**Comment by mbassennesm** [comment]
The example above is on Mac. I experienced the same on a Linux machine previously.

**Comment by mbassennesm** [comment]
@HaebichanGX Wanted to add that the issue seems to be a broader bug around DateType columns. Other expectations such as `expect_column_distinct_values_to_equal_set` and related ones also fail when not supposed to.

**Comment by HaebichanGX** [comment]
@mbassennesm acknowledged.

**Comment by HaebichanGX** [comment]
Hi @mbassennesm I don't seem to get this error. I've replicated your code. You have created a date_str column in spark dataframe but that column remains a string 

`date_str = "2023-01-01"`
`data = spark.createDataFrame([
    {
        "date_str": "2023-01-01",
    },
])
`

`
validator.expect_column_most_common_value_to_be_in_set(
    column="date_str",
    value_set=[date_str],
)`

I'm not sure why you're encountering this error, but in my example, I created `dummy_date_spark` which is a string column. It only has one value as well, "2023-10-01". When I validate the expectation, I get true. I'm therefore not able to replicate your error. 

![Screenshot 2023-10-25 at 10 53 20 AM](https://github.com/great-expectations/great_expectations/assets/133805639/f48ba36b-eb69-42cd-aaeb-8616035997e1)

**Comment by HaebichanGX** [comment]
I've also recreated your exact use case with the dummy data, also not running into error.

![Screenshot 2023-10-25 at 11 00 15 AM](https://github.com/great-expectations/great_expectations/assets/133805639/7a78f6e0-29a0-49fb-b2f1-15866c8d9351)

**Comment by mbassennesm** [comment]
Hi @HaebichanGX , this particular use case is not the one failing (see the original post mentions this is a sanity check). It fails when the type is DateType, not the StringType one. Does that make sense?

**Comment by HaebichanGX** [comment]
@mbassennesm hm...I think you're right. I'm seeing the same issue. Let me get back to my team and see if this is a bug. Thank you.

**Comment by molliemarie** [comment]
Hello @mbassennesm. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
