### ISSUE TITLE
Some expectations are missing from the suite

### ISSUE THREAD

**Issue by andrii-fadieiev** [great-expectations/great_expectations#8232]
**Describe the bug**
In my slightly modified version of getting started code one of expectations is missing from the suite 

**To Reproduce**
```
import great_expectations as gx
context = gx.get_context()

validator = context.sources.pandas_default.read_csv(
    "https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv"
)

validator.expect_column_values_to_not_be_null("pickup_datetime")
validator.expect_column_values_to_be_null("dropoff_datetime")

validator.save_expectation_suite("./suite.json")
```

**Expected behavior**
I'm expecting to see two expectations in the suite and not one. Screenshot of suite.json is the following
<img width="397" alt="Screenshot_1" src="https://github.com/great-expectations/great_expectations/assets/537693/e845eebd-a941-41c5-99b8-8b14a26b0bf3">

**Environment (please complete the following information):**
 - Windows
 - Great Expectations Version: 0.17.2
 - Datasource: Pandas
 - Cloud environment: Local setup

**Additional context**
The funny thing is if I change `validator.expect_column_values_to_be_null("dropoff_datetime")` to `validator.expect_column_values_to_not_be_null("dropoff_datetime")` then I can see two expectations in the suite so it works fine in that case. But why original code don't work as expected?

**Comment by HaebichanGX** [comment]
Hi @andrey-fadeev , the short of the answer is that **save_expectation_suite** function has **discard_filed_expectation** attribute set to True by default. 

`validator.save_expectation_suite("./suite.json", discard_failed_expectations=False)`

So the **validator.expect_column_values_to_be_null("dropoff_datetime")** expectation failed so it wasn't recorded on your json. 

as per your additional context, I can't replicate that scenario, it gives me the appropriate response of only giving me successful expectations, the one where it's **to_not_be_null**

**Comment by andrii-fadieiev** [comment]
Ohh, I knew I miss something obvious like that flag `discard_failed_expectations`.. Thank you very much for your explanation @HaebichanGX
