### ISSUE TITLE
Pydantic V2 support

### ISSUE THREAD

**Issue by matty-rose** [great-expectations/great_expectations#8259]
Hi,

Are there any plans in the near future to support [Pydantic V2](https://github.com/pydantic/pydantic/releases/tag/v2.0)?

**Comment by HaebichanGX** [comment]
Hi @matty-rose let me log this internally as a feature request so it's kept in our backlog. I'll leave this open for a week just in case and close out the PR since the information is kept in our back system.

**Comment by HaebichanGX** [comment]
Hi @matty-rose so after speaking with engineering teams, the thought is that GX will adopt V2 at some point in the future. Thanks!
