### ISSUE TITLE
Make great_expectations compatible with Google Colab

### ISSUE THREAD

**Issue by robzor92** [great-expectations/great_expectations#8260]
**Is your feature request related to a problem? Please describe.**
I would expect great_expectations to work in Google Colab. However if I run a notebook with:

`!pip install great_expectations`

_ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires notebook==6.4.8, but you have notebook 6.5.4 which is incompatible._

and then in a consecutive cell just run a simple:

`print("test")`

colab crashed and fails to execute the cell.

The reason is the [colab environment](https://pypi.org/project/google-colab/) strictly requires `notebook==6.4.8`, however great_expectations requires atleast `6.4.10`.

**Describe the solution you'd like**

Make `great_expectations` compatible with a very common python execution environment - Google Colab.

**Describe alternatives you've considered**

I could roll back my `great_expectations` version to an older version such as 0.14.13 and it would work. But supporting this execution environment should be taken into consideration for newer versions of this library.

**Comment by HaebichanGX** [comment]
Hi @robzor92 thank you for this feature request. We have put it into our backlog. I'll open up this PR for another week and close it out as the information is kept internally in our system.

**Comment by robzor92** [comment]
Thanks @HaebichanGX! Looking forward to this. 👍

**Comment by robzor92** [comment]
@HaebichanGX I understand you guys are very busy. Is there any news on this making it into the codebase any time soon? :smile:

**Comment by robzor92** [comment]
@HaebichanGX This issue and the issue tracked on your side can now be closed. Colab is using notebook 6.5.5 instead of 6.4.8 which means great-expectations is now also compatible there.
