### ISSUE TITLE
Databrick link says Page Not Found

### ISSUE THREAD

**Issue by drishyatm** [great-expectations/great_expectations#8267]
**Describe the bug**
Integration says about databricks integration. However the hyperlink connect to the data source as databricks says Page Not Found. 

**To Reproduce**
https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_great_expectations_in_databricks/

Click on databricks on the Integrations sections

**Expected behavior**
The web page corresponding to the provided URL should load successfully, displaying its content.

OS : Ubuntu
Browser tried : Google Chrome

**Comment by HaebichanGX** [comment]
Hi @drishyatm we have updated our docs recently, perhaps that's why it's failing. The new link is here: https://docs.greatexpectations.io/docs/tutorials/getting_started/how_to_use_great_expectations_in_databricks/

If looks good to you, I'll close out this PR

**Comment by drishyatm** [comment]
Yes, now points to the respective URL. Thanks !
