### ISSUE TITLE
AWS Athena/ AWS glue data catalog fluent datasource

### ISSUE THREAD

**Issue by isired01** [great-expectations/great_expectations#8328]
**Is your feature request related to a problem? Please describe.**
i'm trying to use great_expectation in aws glue,my data are in some athena tables, i see them also in the data catalog of glue.
For now i'm reading this data from some csv file stored in an S3 bucket

**Describe the solution you'd like**
I would need to know when and if a fluent datasource to connect GX to an AWS athena table will be implemented

**Comment by austiezr** [comment]
Hey @isiuni01 ! Thanks for reaching out.

GX should already be able to connect to Athena with Fluent Datasources, following these guides ([1](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/connect_sql_source_data), [2](https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/database/how_to_connect_to_a_sql_table)). If you're unable to do so following this guidance, please feel free to re-open this issue or raise a question in our Slack or Discourse communities.

**Comment by isired01** [comment]
Hi @austiezr , thank so much, so the doc at this [LINK](https://docs.greatexpectations.io/docs/deployment_patterns/how_to_use_gx_with_aws/how_to_use_gx_with_aws_using_athena) is old right?
