### ISSUE TITLE
AWS glue docs dont work

### ISSUE THREAD

**Issue by isired01** [great-expectations/great_expectations#8329]
**Describe the bug**
Bug nei documenti al link: https://docs.greatexpectations.io/docs/0.15.50/deployment_patterns/how_to_use_great_expectations_in_aws_glue 
il codice a questo link non funziona, ho prodotto del codice per collegare AWS Glue a un file csv memorizzato in s3 e vorrei condividerlo. 
 

how can i do that?

**Comment by austiezr** [comment]
Hey @isiuni01! Please share the exact error you're receiving, the exact block of code creating this error, and your environment details (including GX version & OS). That will help us to better investigate what may be happening here.

**Comment by austiezr** [comment]
Hey @isiuni01! Closing this out for now; feel free to re-open if necessary.
