### ISSUE TITLE
Data docs rendering the unexpected and expected values in the wrong order at random

### ISSUE THREAD

**Issue by Adchartuni** [great-expectations/great_expectations#8343]
**Describe the bug**
When running a checkpoint, the validation doc sometimes, at random, reverses the order of the pair values compared. This introduces confusion when sharing the report with another person as it is not clear to which column the value belongs to.
**To Reproduce**
This has happened to me with the expectation: expect_column_pair_values_to_be_equal. 
This is the config of the expectation:
`"expectation_type": "expect_column_pair_values_to_be_equal",
        "kwargs": {
          "batch_id": "data_equality_datasource-data_equality_asset",
          "column_A": "ordered_quantity",
          "column_B": "ordered_item_quantity"`

The result of this expectation as stored in the validation JSON file looks like this:
`"result": {
        "element_count": 748259,
        "missing_count": 0,
        "missing_percent": 0.0,
        "partial_unexpected_counts": [
          {
            "count": 15,
            "value": [
              1,
              0
            ]
          },
          {
            "count": 1,
            "value": [
              2,
              0
            ]
          },
          {
            "count": 1,
            "value": [
              4,
              0
            ]
          }
        ],`

When rendered in the data docs it looks like [this](https://files.slack.com/files-pri/T7NEH00BA-F05HHRD8LAY/image.png)

**Expected behavior**
The expected behavior should be:
The order of the valeus should match with the order of the columns,that means, column_A should be the first value, column_B should be the second value.

Like in this [picture](https://files.slack.com/files-pri/T7NEH00BA-F05H0S29QTZ/image.png), where I ran the same expectation but got the right order without changing anything.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.17.5
 - Datasource: Pandas Dataframe

**Additional context**
The order changes occassionally, it is not a persistent error.

**Comment by austiezr** [comment]
Hey @Adchartuni ! Thanks for raising this. We'll investigate this behavior and address.

**Comment by HaebichanGX** [comment]
Hi @Adchartuni I can't seem to reproduce this error on my side but will review with the engineering team to see what might be the issue. Thanks!

**Comment by Adchartuni** [comment]
@HaebichanGX thank you for your comment on this issue. 
Let me know if there's anything I can provide to replicate this on your end.

**Comment by molliemarie** [comment]
Hello @Adchartuni. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
