### ISSUE TITLE
minor bug in sqlalchemy_execution_engine

### ISSUE THREAD

**Issue by SaeedFarahani** [great-expectations/great_expectations#8373]
Describe the bug
I found a minor bug while I was running our system integration tests and it happens when using some special rules so I think it's better to fix this issue in the main branch.

To Reproduce

great_expectations.yml config is attached
[great_expectations.yml.txt](https://github.com/great-expectations/great_expectations/files/12118257/great_expectations.yml.txt)

Expected behavior

this is the expectation that GX raised:

great_expectations/execution_engine/execution_engine.py", line 550, in _process_direct_and_bundled_metric_computation_configurations\n raise gx_exceptions.MetricResolutionError(\ngreat_expectations.exceptions.exceptions.MetricResolutionError: 'Subquery' object has no attribute 'subquery'\n", "exception_message": "'Subquery' object has no attribute 'subquery'",

Environment (please complete the following information):

Operating System: MacOS
Great Expectations Version: 0.17.5
Datasource: SQL

**Comment by HaebichanGX** [comment]
Thanks @SaeedFarahani! Let me put this into backlog so we can look into this

**Comment by SaeedFarahani** [comment]
@HaebichanGX you're welcome, 
I've submitted a PR to fix this and, it got approved, could you merge it??

https://github.com/great-expectations/great_expectations/pull/8374

**Comment by HaebichanGX** [comment]
Thank you for opening up the issue and getting this resolved, resolved by #8374
