### ISSUE TITLE
Json Datatypes not converted to Python data types in expectation suite notebook editing tool

### ISSUE THREAD

**Issue by MarcelBeining** [great-expectations/great_expectations#8377]
**Describe the bug**
The json data types seem to be not converted to Python data types when editing the expectation suite using `great_expectations suite edit `

**To Reproduce**
1. Create an expectation "expect_column_values_to_be_in_set" in your expectation suite yml:
`{
        "kwargs": {
            "column": "XXXX",
            "mostly": 1.0,
            "value_set": [false, true],
        },
        "expectation_type": "expect_column_values_to_be_in_set",
    }`

2. Edit your expectation suite with command `great_expectations suite edit YOURSUITENAME`
3. The section with the expectation from above cannot be executed as it says 

> NameError: name 'false' is not defined

**Expected behavior**
The line `"value_set": [false, true],` should have been transformed to `"value_set": [False, True],` during notebook creation.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.15.2

**Comment by HaebichanGX** [comment]
Hey @MarcelBeining thank you for letting us know! Let me put it into backlog for review.

**Comment by HaebichanGX** [comment]
Hi @MarcelBeining so we no longer provide support for version 0.15.2. Can you upgrade to our latest version and see if that error still occurs?

**Comment by MarcelBeining** [comment]
@HaebichanGX Yes the problem persists with version 0.17.9
![image](https://github.com/great-expectations/great_expectations/assets/1278660/ec7effc2-d234-4691-8706-d7f422f01e78)

**Comment by HaebichanGX** [comment]
closed as GX no longer has deprecated the CLI function
