### ISSUE TITLE
Incorrect result file referencing on Windows

### ISSUE THREAD

**Issue by mspaulik** [great-expectations/great_expectations#8387]
**Describe the bug**

When executing Great Expectations on Windows, index.html incorrectly references the filepath inside results folder. The key '_table_row_link_path' in the file contains link to the path which has **'%5C'** symbol in the filepath instead of regular **'/'.** Thus, the file cannot be found.

Example of code snippet from index.html :

Object.assign(
{
columns: [.....]
data: [ "_table_row_link_path" : 'validations%5CData_Suite%5C6567%5C20230724T080927.1287666Z%5C123.html']
},
toolbar: [....]
)

Thus, when trying to open these results in index.html file, it give error that: "Hmmmmm.... cant reach page."

The output folder structure created is:
```
- great-expectations/runResults/
     - static/
     - validations/
         - Data_Suite /
             - 6567 /
                 - 20230724T080927.1287666Z/
                     - 123.html
     - index.html
```

**To Reproduce**

```
yaml = YAMLHandler()
context = gx.get_context()
datasource_config = {
  "name" :  "customDatasource",
  "class_name" : "Datasouce",
  "execution_engine" : { "class_name": "PandasExecutionEngine"},
  "data_connectors": {
     "DefaultRuntimeDataConnector": {
          "class_name" : "RuntimeDataConnector",
          "batch_identifiers" : ["default_batch"],
      }
  }
}

context.test_yaml_config(yaml.dump(datasource_config))
context.add_datasource(**datasource_config)

batch_request = RuntimeBatchRequest(
  datasource_name = "customDatasource",
  data_connector_name = "DefaultRuntimeDataConnector",
  data_asset_name = "custom_data_asset",
  runtime_parameters = {"path": datafile },
  batch_identifiers = {"default_batch": "default_batch"},
  batch_spec_passthrough = batch_spec_passthrough 
)

validator = context.get_validator{
  batch_request = batch_request,
  expectations_suite_name = rulesfile,
}

checkpoint = gx.checkpoint.SimpleCheckpoint(
  name = "default_checkpoint",
  data_context = context,
  validator = validator,
  run_name_template = custom_id
)

checkpoint_result = checkpoint.run()
```

config_variables.yml

`BASE_DIRECTORY: '..\runResults'`

**Comment by MarcelBeining** [comment]
@HaebichanGX I have a fix for this error, but it seems I cannot push a new branch to this repo to be able to start a Pull Request (error 403 after authorization). Do you need to authorize me for this?

**Comment by MarcelBeining** [comment]
Otherwise, here is the fix:
In file great_expectations\render\renderer\site_builder.py starting with line 603, replace this
```
        if run_id:
            filepath = (
                os.path.join(  # noqa: PTH118
                    "validations",
                    *expectation_suite_name.split("."),
                    *run_id.to_tuple(),
                    batch_identifier,
                )
                + ".html"
            )
        else:
            filepath = (
                os.path.join(  # noqa: PTH118
                    "expectations", *expectation_suite_name.split(".")
                )
                + ".html"
            )
```

with this
```
        if run_id:
            filepath = (
                "/".join(
                    [  # noqa: PTH118
                        "validations",
                        *expectation_suite_name.split("."),
                        *run_id.to_tuple(),
                        batch_identifier,
                    ]
                )
                + ".html"
            )
        else:
            filepath = (
                "/".join(
                    [  # noqa: PTH118
                        "expectations",
                        *expectation_suite_name.split(".")
                    ]
                )
                + ".html"
            )
```


Explanation: os.path.join produces backslashes on Windows which are then url encoded to '%5C'. Using os.path.join here is totally unnecessary as the url needs slashes anyways.

**Comment by Kilo59** [comment]
@MarcelBeining you need to fork the repo and then you will be able to submit a pull request back to source.

https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by Kilo59** [comment]
Closing this as the PR was merged.
