### ISSUE TITLE
Broken expectation suite links in data docs starting with 0.16.15

### ISSUE THREAD

**Issue by MarcelBeining** [great-expectations/great_expectations#8392]
**Describe the bug**
In newer GE versions the links to the data docs of each expectation suite is broken. I tested every version 0.15.0 to 0.17.6 and before 0.16.16 it works fine.

**To Reproduce**
- Install any version >= 0.16.16
- Rebuild the data docs of your project (at least one expectation suite necessary). For this I deleted the "uncommitted" folder and then executed `great_expectations docs build` in command line
- On the data docs webpage that opens, click on "Expectation Suites" and on one of your project's expectation suites.
- The browser shows missing page problem as it points to 

> file:///YOUR_PROJECT_DIR/great_expectations/uncommitted/data_docs/local_site/expectations%5CYOUR_DATASOURCE%5CYOUR_EXPECTATION_SUITE_NAME.html

**Expected behavior**
The link should point to 

> file:///YOUR_PROJECT_DIR/great_expectations/uncommitted/data_docs/local_site/expectations/YOUR_DATASOURCE/YOUR_EXPECTATION_SUITE_NAME.html

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: >= 0.16.16

**Comment by MarcelBeining** [comment]
Seems to be related to #8387

**Comment by HaebichanGX** [comment]
Hi @MarcelBeining I just reproduced your error and for me it works fine. Please bear in mind that GX doesn't officially support Windows, which can also raise the issue. For Mac, on my side, it works fine

<img width="1508" alt="Screenshot 2023-07-28 at 10 58 21 AM" src="https://github.com/great-expectations/great_expectations/assets/133805639/e05c11c4-13c9-42cd-8539-138d8a590eab">
