### ISSUE TITLE
Queries returned by the unexpected_index_query have syntax errors

### ISSUE THREAD

**Issue by nebloc** [great-expectations/great_expectations#8407]
**Describe the bug**
Attempting to create a spark dataframe from the returned `unexpected_index_query` in the checkpoint result, however the returned queries can't be evaluated in pyspark.

**To Reproduce**
Using pyspark notebook, create a dataframe:
`df = spark.read.parquet("Files/Raw/assetnum/test.parquet")`
Create an expectations, such as expect column value to not be null for serialnum, and set result format for a simple checkpoint
```python
checkpoint = gx.checkpoint.SimpleCheckpoint( # Create Checkpoint
    name = checkpoint_name,
    data_context = context,
    validations = [{
        "batch_request": batch_request,
        "expectation_suite_name": expectationsuite_name,
    }],
    runtime_configuration = {
        "result_format": {
            "result_format": "COMPLETE",
            "unexpected_index_column_names": ["assetnum"],
            "return_unexpected_index_query": True,
        },
    },
)
```
Extract the unexpected_index_query from the checkpoint result, and evaluate it with `eval(returned_query)`
```
    df.filter(F.expr(NOT (serialnum IS NOT NULL)))
                          ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

**Expected behavior**
Dataframe filter to run and provide unexpected rows.

**Environment (please complete the following information):**
 - Operating System: Windows - But Azure Synapse
 - Great Expectations Version: 0.17.4
 - Datasource: Spark Dataframe from parquet file
 - Cloud environment: Azure Synapse

**Additional context**
Creating it as a pandas dataframe works and query can be evaluated, but is different (just contains a filter for all the index values)

**Comment by HaebichanGX** [comment]
Hi @nebloc This seems to be your syntax error, not GX's bug. Your expression should be: 

`df.filter(F.expr("NOT (Name IS NOT NULL)"))`

Also, we've deprecated SimpleCheckpoint. Please refer to using regular Checkpoint

**Comment by nebloc** [comment]
Thanks @HaebichanGX ;

https://docs.greatexpectations.io/docs/terms/checkpoint/#simplecheckpoint-class sorry, doesn't say its deprecated; but have changed to check point as below;
```python
checkpoint = context.add_or_update_checkpoint(
    name="my_checkpoint",
    validations=[
        {
            "batch_request": batch_request,
            "expectation_suite_name": expectationsuite_name,
        },
    ],
    runtime_configuration = {
        "result_format": {
            "result_format": "COMPLETE",
            "unexpected_index_column_names": ["assetnum"],
            "return_unexpected_index_query": True,
        },
    },
)
checkpoint_run = checkpoint.run() # Run checkpoint
```

```python
res = checkpoint_run.list_validation_results()
query = res[0].results[0].result['unexpected_index_query']
```
query is now set to the query produced by gx

![image](https://github.com/great-expectations/great_expectations/assets/15227649/6432d2a0-be8b-4385-b05f-4c0ee85bd3c3)

**Comment by nebloc** [comment]
So I agree, but it's coming from GX and I think it should be formed correctly with quotations?

**Comment by nebloc** [comment]
Hi @HaebichanGX, did you have any thoughts on this? is there anything else I can provide to help with investigation?

We would like to use the library in production, but are needing a way to quarantine data so this is a key feature

**Comment by HaebichanGX** [comment]
Hi @nebloc can you share your full code here? I don't know where the df.filter is being called.

**Comment by nebloc** [comment]
Hi, @HaebichanGX, everything is already in the previous post, not sure how much more I can provide. I am creating a checkpoint and running the checkpoint with runtime_configuration COMPLETE, shown in the code snippet above. If we then take this output, of this checkpoint: 
``` json
[
  {
    "evaluation_parameters": {},
    "meta": {
      "great_expectations_version": "0.17.4",
      "expectation_suite_name": "expectations_test",
      "run_id": {
        "run_time": "2023-08-03T11:48:51.800509+00:00",
        "run_name": null
      },
      "batch_spec": {
        "batch_data": "SparkDataFrame"
      },
      "batch_markers": {
        "ge_load_time": "20230803T114851.804613Z"
      },
      "active_batch_definition": {
        "datasource_name": "my_datasource",
        "data_connector_name": "fluent",
        "data_asset_name": "my_dataasset",
        "batch_identifiers": {}
      },
      "validation_time": "20230803T114851.822226Z",
      "checkpoint_name": "checkpoint",
      "validation_id": null,
      "checkpoint_id": null
    },
    "results": [
      {
        "result": {
          "element_count": 15235,
          "unexpected_count": 0,
          "unexpected_percent": 0.0,
          "partial_unexpected_list": [],
          "unexpected_index_column_names": [
            "col2"
          ],
          "missing_count": 7699,
          "missing_percent": 50.53495241220873,
          "unexpected_percent_total": 0.0,
          "unexpected_percent_nonmissing": 0.0,
          "partial_unexpected_index_list": [],
          "partial_unexpected_counts": [],
          "unexpected_list": [],
          "unexpected_index_list": [],
          "unexpected_index_query": "df.filter(F.expr((col1 IS NOT NULL) AND (NOT ((col1 >= 0) AND (col1 <= 600000)))))"
        },
        "exception_info": {
          "raised_exception": false,
          "exception_traceback": null,
          "exception_message": null
        },
        "meta": {},
        "success": true,
        "expectation_config": {
          "kwargs": {
            "column": "col1",
            "max_value": 600000,
            "min_value": 0,
            "batch_id": "my_datasource-my_dataasset"
          },
          "expectation_type": "expect_column_values_to_be_between",
          "meta": {
            "id": 10
          }
        }
      }
    ],
    "success": false,
    "statistics": {
      "evaluated_expectations": 12,
      "successful_expectations": 5,
      "unsuccessful_expectations": 7,
      "success_percent": 41.66666666666667
    }
  }
] 
```
We can see that the unexpected index query is not correctly formed. In me previous post I was using the `eval()` command to run the query as python code, which is where the df.filter is coming from - its in the unexpected_index_query returned from the checkpoint results.

**Comment by YeshanhAntares** [comment]
Hi @HaebichanGX @nebloc, I'm experiencing the same error as well. Is this fixed? To elaborate I'm trying to run the "unexpected_index_query" returned from my validation within python's eval function. For eg: the below the query that i get when i need to validate null checks for my cabin column.

`
"unexpected_index_query": "df.filter(F.expr(NOT (Cabin IS NOT NULL)))"
`

When I try to run this code within pythons eval function as below:

`
x = eval("df.filter(F.expr(NOT (Cabin IS NOT NULL)))")
`

I then get the below error:

```
Traceback (most recent call last):

  File ~/cluster-env/clonedenv/lib/python3.10/site-packages/IPython/core/interactiveshell.py:3442 in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  Cell In[100], line 3
    x = eval("df.filter(F.expr(NOT (Cabin IS NOT NULL)))")

  File <string>:1
    df.filter(F.expr(NOT (Cabin IS NOT NULL)))
                          ^
SyntaxError: invalid syntax. Perhaps you forgot a comma?
```

As far as I know, when we use the expr function, we need to wrap the relevant expression within quotes as well, which then works.

`x = eval("df.filter(F.expr('NOT (Cabin IS NOT NULL)'))")`

Furthermore, when utilizing the regex Expectation `expect_column_values_to_match_regex`, the response query usees the RLIKE method, in which the second param or rather the regex value is not wrapped with single quotes '\'', resulting in another error. Such queries are include:

```
"df.filter(F.expr((Happiness_Score IS NOT NULL) AND (NOT RLIKE(Happiness_Score, ^(0|1|true|false)$))))"

"df.filter(F.expr((Country IS NOT NULL) AND (NOT RLIKE(Country, ^N))))"
```

And considering the above code, the correct result should be:

```
"df.filter(F.expr("(Happiness_Score IS NOT NULL) AND (NOT RLIKE(Happiness_Score, '^(0|1|true|false)$'))"))"

"df.filter(F.expr("(Country IS NOT NULL) AND (NOT RLIKE(Country, '^N'))"))"
```

As for the GX declaration information, refer the code below.

```
        datasource = self.context.sources.add_spark(self.datasource_name)
        data_asset = datasource.add_dataframe_asset(name=self.data_asset_name)
        my_batch_request = data_asset.build_batch_request(dataframe=self.df)

        # Create Expecation suite
        self.context.add_or_update_expectation_suite(self.expectation_suite_name)
        validator = self.context.get_validator( batch_request=my_batch_request, expectation_suite_name=self.expectation_suite_name )
        validator = self.setExpectations(validator)
        validator.save_expectation_suite(discard_failed_expectations=False)

        # Create Checkpoint
        checkpoint = Checkpoint(
            name=self.checkpoint_name,
            run_name_template="%Y%m%d-%H%M%S-my-run-name-template",
            data_context=self.context,
            batch_request=my_batch_request,
            expectation_suite_name=self.expectation_suite_name,
            action_list=[
                {
                    "name": "store_validation_result",
                    "action": {"class_name": "StoreValidationResultAction"},
                },
                {
                    "name": "store_evaluation_params",
                    "action": {"class_name": "StoreEvaluationParametersAction"},
                },
                {"name": "update_data_docs", "action": {"class_name": "UpdateDataDocsAction"}},
            ],
            runtime_configuration={
                "result_format": {
                    "result_format": "COMPLETE",
                    "unexpected_index_column_names": [self.sk],
                    "return_unexpected_index_query": True,
                    "include_unexpected_rows": False
                },
            },
        )
        self.context.add_or_update_checkpoint(checkpoint=checkpoint)
        self.checkpoint_result = checkpoint.run()
```

Also currently the code is running in
```
Environment: Hosted - Microsoft Fabric Notebook (Similar to Databricks Notebooks)
Pyspark version: PySpark version: 3.3.1.5.2-100694667
```


Please look into this error since its very important when extracting the invalid rows of data since people would utilize the query rather than looping through the list of indexes returned.

**Comment by HaebichanGX** [comment]
Hey @YeshanhAntares @nebloc it seems like the output of unexpected_index_query is in not in a string format for immediate execution from `eval` function. As you both mentioned above, currently it's `"df.filter(F.expr(NOT (Cabin IS NOT NULL)))"` rather than `df.filter(F.expr("NOT (Cabin IS NOT NULL")))`. 

Rather than just running `eval` on the output, why don't we create an intermediary function to transform the strings in the right order (my code syntax is having issues right now). 


<img width="1054" alt="Screenshot 2023-10-18 at 9 49 42 AM" src="https://github.com/great-expectations/great_expectations/assets/133805639/cad3f1b4-2366-4c2b-860e-2d9815820d55">

**Comment by HaebichanGX** [comment]
closing the issue due to more than week in response

**Comment by BenConstable9** [comment]
Is there any plan to fix this issue and make the `unexpected_index_query` work if used? For instance if strings are included within the output, the filter is invalid.
