### ISSUE TITLE
Possibility to alter SQLAlchemy session

### ISSUE THREAD

**Issue by KHerashchenko** [great-expectations/great_expectations#8444]
**Is your feature request related to a problem? Please describe.**
We faced the need to provide [query tags](https://docs.snowflake.com/en/sql-reference/parameters#query-tag) for GX running on Snowflake datasource (we connect to the database using the SQLAlchemy engine). It will provide us visibility on Snowflake credits consumption by GX. 

**Describe the solution you'd like**
The straightforward solution is to give an opportunity to modify the running session - to run `alter session set query_tag = 'random_tag_here';` (So far, I see it possible only for Custom Expectations because it gives control over the query to run)

**Describe alternatives you've considered**
Provide additional kwargs for Expectations or Checkpoints to set session parameters.

**Comment by HaebichanGX** [comment]
Hi @KHerashchenko can you please provide us more information regarding your environment? And please share your code if you feel this will be helpful for us to reproduce the issue. Please see example here: https://github.com/great-expectations/great_expectations/issues/8243

**Comment by KHerashchenko** [comment]
great-expectations 0.15.41

The most functional solution for us would be:
```
{
    "data_asset_type": null,
    "expectation_suite_name": "mock_data_ge_test",
    "expectations": [
        {
            "expectation_type": "expect_column_values_to_be_in_set",
               "kwargs": {
                  "query_tag": "my_tag",
                  "column": "col_1",
                  "value_set": ["expected_value_1","expected_value_2"],
                  "mostly": 1.0
               }
        }
    ]
}
```

**Comment by HaebichanGX** [comment]
Hi @KHerashchenko, firstly, we no longer support version 0.15. This is a quite old version and we've moved on to 0.17. But I think this is relevant regardless. Let me put this into our backlog. Since it's been more than a week, I will close out this feature request suggestion
