### ISSUE TITLE
Will dataset.SparkDFDataset and dataset.PandasDataset be supported in future versions?

### ISSUE THREAD

**Issue by mikeweltevrede** [great-expectations/great_expectations#8479]
**Is your feature request related to a problem? Please describe.**
We are utilizing the `dataset.SparkDFDataset` and `dataset.PandasDataset` in our solution for `great-expectations==0.17.5`. We found that this is an easy way to set op GX for in-memory DataFrames. However, we can only find the documentation for them in the latest docs, only in legacy.docs.greatexpectations.io.

**Our question**: will `dataset.SparkDFDataset` and `dataset.PandasDataset` be supported in future versions? I.e. if new expectations are added, are they also added there?

**Describe the solution you'd like**
For `dataset.SparkDFDataset` and `dataset.PandasDataset` to be supported in future versions.

**Describe alternatives you've considered**
Followed the latest documentation on ["How to configure a Spark Datasource" ](https://docs.greatexpectations.io/docs/0.15.50/guides/connecting_to_your_data/datasource_configuration/how_to_configure_a_spark_datasource) and ["How to connect to in-memory data in a Spark dataframe"](https://docs.greatexpectations.io/docs/0.15.50/guides/connecting_to_your_data/in_memory/spark) (and Pandas). However, this requires much more setup that simply instantiating `dataset.SparkDFDataset` with our dataframe.

**Additional context**
Current implementation is as simple as this:

```
        if isinstance(df, pyspark.sql.DataFrame):
            return SparkDFDataset(df)
        if isinstance(df, pd.DataFrame):
            return PandasDataset(df)
        raise TypeError(f"Type {type(df)} is not a usable type")
```

**Comment by Kilo59** [comment]
@mikeweltevrede have you seen this documentation on using an in-memory Pandas Dataframe?

https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/in_memory/how_to_connect_to_in_memory_data_using_pandas

Given you already have the pandas dataframe as `df` it can be as simple as...
```python
import great_expectations as gx

context = gx.get_context()
my_asset = context.sources.pandas_default.add_dataframe_asset("my_asset_name")
my_batch_request = my_asset.build_batch_request(dataframe=df)
```

What is the source data for your `dataframe`?
If it's a `csv`, `parquet` etc. you could use the `.add_csv_asset()` or `.add_parquet_asset()` methods which also allow most of the same config options as the Pandas `IO` methods.
https://pandas.pydata.org/docs/reference/io.html
https://docs.greatexpectations.io/docs/reference/api/datasource/fluent/PandasFilesystemDatasource_class

**Comment by HaebichanGX** [comment]
Hi @mikeweltevrede yes we do support spark and pandas dataframes as @Kilo59 mentioned. For additional context on how to implement this using our latest Fluent Data Source (FDS) method, you can use this flowchart to get a visual understanding how everything connects: https://lucid.app/lucidspark/4373d267-f0bf-4085-8a44-b077277c0748/edit?invitationId=inv_a832619d-4907-4518-b495-2d89c840454f&page=0_0#

**Comment by mikeweltevrede** [comment]
Thanks both @Kilo59 and @HaebichanGX! We will try your suggestions. I am still wondering: do I understand correctly that you cannot guarantee that `PandasDataset` and `SparkDFDataset` will be supported with new expectations in the future and that we should, therefore, switch to the new implementation you mentioned?

@HaebichanGX would it be possible to share an image or PDF version of the flowchart since the address is unfortunately blocked by my employer?

PS: My apologies for my delay in response, I was on holiday.

**Comment by HaebichanGX** [comment]
Hi @mikeweltevrede pardon the late response, the alert escaped my radar. So yes, `dataset.SparkDFDataset` and `dataset.Dataset`are legacy implementation. Please use the new Fluent Data Sources method to implement GX end to end. 

It's a bit difficult to see, please let me know if you're able to zoom in on the components.

![Screenshot 2023-08-25 at 1 47 18 PM](https://github.com/great-expectations/great_expectations/assets/133805639/b00f74fc-792b-4324-93c5-aa7ab349a880)
