### ISSUE TITLE
Passing value_set through Evaluation Parameters crashes if list size is more than 100

### ISSUE THREAD

**Issue by BilalGGS** [great-expectations/great_expectations#8490]
**Describe the bug**
Bug is related to airflow operator for great expectations.
Dialect Used: Snowflake
Expectation Used : expect_column_values_to_be_in_set

Example of expectation:

```
"expectations": [
    {
      "expectation_type": "expect_column_values_to_be_in_set",
      "kwargs": {
        "column": "column_A",
        "value_set": {
          "$PARAMETER": "valid_ids"
        }
      },
      "meta": {
        "id": "test_unknown_ids"
      }
    }
  ],
```
Problem:
If the size of list passed through evaluation parameters(Not loading params from db, loading them from python list) to this expectation crosses 100, it breaks the underlying json.

Error Message:
```

sqlalchemy.exc.DataError: (psycopg2.errors.InvalidTextRepresentation) invalid input syntax for type json
LINE 1: ...rendered_task_instance_fields SET rendered_fields='{"run_nam...
                                                             ^
DETAIL:  Token "Infinity" is invalid.
CONTEXT:  JSON data, line 1: ...6e5", 150641421, "e6096a21", "e6093099", Infinity...
```
**To Reproduce**
Use expect_column_values_to_be_in_set with airflow operator with value set passed as param through operator params rather than query store

**Expected behavior**
It should accept the value_set parameter longer than 100 size list.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.42
 - Data Source: Snowflake
 - Cloud environment: Airflow MWAA

**Additional Question**
Is it a bug that expectation crashes on list size more than 100 or is it desired behaviour?
I have verified that it only crashes when I pass 100+ size value_set through evaluation params, expectation works fine if I add the list of 100+ size directly into expectation json. So I think it must be something related to handling of big json objects by operator.

**Comment by HaebichanGX** [comment]
Hi @BilalGGS we no longer support version 0.15. We have moved onto Fluent Data Sources (FDS) implementation of GX. Can you please update the code and see if the issue is still occurring? Here's a flowchart to visualize the code connections. https://lucid.app/lucidspark/4373d267-f0bf-4085-8a44-b077277c0748/edit?invitationId=inv_a832619d-4907-4518-b495-2d89c840454f&page=0_0#
