### ISSUE TITLE
Remove SELECT Prefix Constraint in QueryAsset to Allow More Complex SQL Queries

### ISSUE THREAD

**Issue by nnuthman** [great-expectations/great_expectations#8517]
**Is your feature request related to a problem? Please describe.**
For context in #8163 I migrated to the newest API in 0.17.7.

Now, using a SQL DataSource with a QueryAsset requires that the query starts with 'SELECT' and is followed by a whitespace.
Which means I can no longer use my existing queries, for two reasons:
- I would like to have a comment at the start of the query to describe what it is doing
  - This can easily be moved, but still feels unnecessary since the database will ignore the string
- Some queries start with a 'WITH' block to define more complex queries

In general I think the database should evaluate the legitimacy of the query.

**Describe the solution you'd like**
In the Query Asset [definition](https://github.com/great-expectations/great_expectations/blob/24367fd1efedbc1c48f50b9267c1169da6fc69c0/great_expectations/datasource/fluent/sql_datasource.py#L782) I would like to see the pydantic constraint removed.

**Describe alternatives you've considered**
Obviously, I could refactor all my queries for my expectations.

**Additional context**
I definitely don't understand the whole context here (for example `as_selectable` seems to require this 'SELECT ' prefix).
But my perspective is that I want to use Great Expectations to run queries on the database and evaluate the result against the expected outcome. Everything that is proper SQL can be evaluated on the database.
So now I can't execute valid SQL anymore, because of some (from my perspective) arbitrary constraint to have it start with SELECT.

I hope, it is clear what I mean. Please let me hear your thoughts on this design decision.

**Comment by HaebichanGX** [comment]
Hi @nnuthman thank you for this feature request. Let me tag this issue so the information is in our systems and keep it open for a week and close it out

**Comment by TrangPham** [comment]
Hi @nnuthman 

We have updated our code to comply with SQLAlchemy's deprecation of standalone subqueries. 
`sqlalchemy.exc.SADeprecationWarning: The standalone subquery() function is deprecated and will be removed in a future release.  Use select().subquery(). (deprecated since: 1.4)`

For now I suggest wrapping your queries for your expectations. I believe something such as the code below would work:
```
def wrap(query):
    return f"SELECT * FROM ({query}) AS my_wrapped_query"
    
QueryAsset(
        name="my_query_asset",
        query=wrap("/* This is a comment */ SELECT * FROM my_schema.my_table"),
)
```
 If this works for all your queries, feel free to add a PR which adds this logic to the QueryAsset and include test cases.

**Comment by nnuthman** [comment]
Hi @TrangPham, thanks for the hint. Sad that I didn't get it myself..
Works perfectly so far with this change!

I added the following later on, so that from the outside the old behavior is preserved (e.g., when getting the Query from CheckpointResult.
```python
query.removeprefix("SELECT result FROM (").removesuffix(") AS my_wrapped_query")
```

If I find the time next week, I will try to create a PR.

**Comment by r34ctor** [comment]
Hi @nnuthman, I just wanted to follow up with you here. Are you still planning to create a PR to address this issue? We would be happy to support you with this if needed.

**Comment by r34ctor** [comment]
We'll close this issue off for now, but please feel free to re-open it needed, thanks!
