### ISSUE TITLE
Optimize BigQuery Batch Requests to fully leverage pruning

### ISSUE THREAD

**Issue by lmandruzzato-bc** [great-expectations/great_expectations#8518]
**Initial context**
Referring to the Discourse topic: https://discourse.greatexpectations.io/t/batch-requests-converted-to-non-optimized-queries-in-bigquery-googlesql/1316.

I mapped a BigQuery dataset to a GX Datasource and then I mapped a BigQuery table to a GX Data Asset (via Table Asset). Afterward, I added a splitter (yearly, monthly, and daily) to the Data Asset so that I can control what data to fetch via GX Batch Requests. The splitter is on the partition column of the underlying table.

**Is your feature request related to a problem? Please describe.**
The final Batch Request inferred by GX and executed on BigQuery is not optimized to fully leverage [pruning](https://cloud.google.com/bigquery/docs/querying-partitioned-tables). This is the way GX translates the Batch Request to the GoogleSQL dialect:
```sql
CREATE OR REPLACE TABLE `<GX TEMP ID>`
	OPTIONS(
		expiration_timestamp=TIMESTAMP_ADD(
		CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
	)
	AS SELECT * 
FROM `<NAME OF THE TABLE>` 
WHERE EXTRACT(year FROM `<COLUMN NAME>`) = <YEAR> AND EXTRACT(month FROM `<COLUMN NAME>`) = <MONTH> AND EXTRACT(day FROM `<COLUMN NAME>`) = <DAY>
```
In my specific case, this is processing ~30GB because it does pruning on the `<YEAR>` only. So, it loads all the (daily) partitions of the `<YEAR>` instead of loading the daily partition only `<YEAR>-<MONTH>-<DAY>`.

**Describe the solution you'd like**
I'd like GX translating the Batch Request this way:
```sql
CREATE OR REPLACE TABLE `<GX TEMP ID>`
	OPTIONS(
		expiration_timestamp=TIMESTAMP_ADD(
		CURRENT_TIMESTAMP(), INTERVAL 24 HOUR)
	)
	AS SELECT * 
FROM `<NAME OF THE TABLE>` 
WHERE TIMESTAMP_TRUNC(<COLUMN NAME>, DAY) = TIMESTAMP("<YEAR>-<MONTH>-<DAY>")
```
This way, in my specific case, BigQuery processes ~130MB which is ~250 times more efficient than the current solution.

**Describe alternatives you've considered**
The only alternative I see at the moment is to redefine a new Query Asset at every execution by providing an optimized query as input; this way I don't leverage Batch Requests at all (every time I ask for the whole Data Asset which is already filtered as needed). 
In a nutshell:
- from one single Table Asset + granular Batch Requests every time
- to a new granular Query Asset every time + whole Batch Requests

**Additional context**
I don't know if it makes sense to extend the `split_on_date_parts` so that it behaves differently for the BigQuery dialect. Maybe the proper solution would be to have something similar to `split_on_converted_datetime` which works for SQLite only. So, something like `split_on_truncated_timestamp` that works for BigQuery only and given a `column_name` and a string representing the required timestamp `required_timestamp` (it must be well formatted according to ISO8601), it is able to return the required data. Pseudo-code:
```
# look for the most granular date part of the provided required_timestamp
most_granular_date_part = _extract_most_granular_date_part_from_timestamp(required_timestamp)

# where statement in the final Batch Request (GoogleSQL dialect)
TIMESTAMP_TRUNC(<column_name>, most_granular_date_part) = TIMESTAMP(required_timestamp)
```

**Comment by HaebichanGX** [comment]
Thank you for this feature request @lmandruzzato-bc ! I have flagged this issue for review. We will open this PR for another week just in case and close it out. Thanks!

**Comment by molliemarie** [comment]
Hello @lmandruzzato-bc. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
