### ISSUE TITLE
Sqlalchemy takes too much time

### ISSUE THREAD

**Issue by hymekeci** [great-expectations/great_expectations#8528]
Suppose I want to observe a lot of tables and a lot of rows in sql. But because the great expectations library uses `sqlalchemy` to read data from sql, each row is translated into a python object. 

This takes a lot of time. 

To avoid this I would like to be able to use `custom engines` instead of having to use sqlalchemy.

**Comment by austiezr** [comment]
Hey @halilhan ! Thanks for reaching out. We've captured this feedback for internal review -- I'll leave this issue open for the next week if you'd like to provide any further context!
