### ISSUE TITLE
Evaluation Parameter null return behavior

### ISSUE THREAD

**Issue by ktc1016** [great-expectations/great_expectations#8535]
**Describe the bug**
I am currently trying to compare 2 datasets by mean value thus, to achieve this, I need to create a checkpoint with 2 expectation suites and use 1st expectation suite's results as basis for the 2nd suite's rules (evaluation parameter will be used here). My Checkpoint test works if there are values in the column since there is an actual numerical mean however if the values are Null it will resort to an error. Average value of Null is a probable return on our use case since there are times where this column is not filled up. 

**To Reproduce**

Data Setup - To reproduce easily, lets use sqlite but the actual setup is Pandas and Postgres
```python
import pandas as pd
from sqlalchemy import create_engine
conn = create_engine('sqlite:///sample.sqlite3')

# Adjust data values here
df_source_1 = pd.DataFrame([{'column_1': None}])
df_source_2 = pd.DataFrame([{'column_1': 1},{'column_1': 2},{'column_1': 3}])

df_source_1.to_sql(name='source_1', con=conn, if_exists='replace',index=False)
df_source_2.to_sql(name='source_2', con=conn, if_exists='replace',index=False)
``` 

GX Code Prerequisites - Code to setup the Suite and fluent datasources
```python
import great_expectations as gx

context = gx.get_context()

# Run if gx config has not been setup.
# connection_string = "sqlite:///sample.sqlite3"

# datasource = context.sources.add_sql(
#     name="my_datasource", connection_string=connection_string
# )

# datasource.add_query_asset(name='asset_1', query='SELECT * FROM source_1')
# datasource.add_query_asset(name='asset_2', query='SELECT * FROM source_2')

 
context.add_or_update_expectation_suite(
    expectation_suite_name='suite_1',
)
context.add_or_update_expectation_suite(
    expectation_suite_name='suite_2'
)

datasource = context.get_datasource('my_datasource')

asset_1 = datasource.get_asset('asset_1')
asset_2 = datasource.get_asset('asset_2')
```

GX Validations - Setup Validation rules including use of evaluation parameters. 
```python
asset_1_request = asset_1.build_batch_request()

validator_asset_1 = context.get_validator(
    batch_request=asset_1_request,
    expectation_suite_name='suite_1',
)

asset_2_request = asset_2.build_batch_request()
validator_asset_2 = context.get_validator(
    batch_request=asset_2_request,
    expectation_suite_name='suite_2',
)

validator_asset_1.interactive_evaluation = False
validator_asset_2.interactive_evaluation = False


validator_asset_1.expect_column_mean_to_be_between(
    "column_1",
    min_value=None,
    max_value=None,
)

column_1_mean = f"urn:great_expectations:validations:suite_1:expect_column_mean_to_be_between.result.observed_value:column=column_1"
validator_asset_2.expect_column_mean_to_be_between(
    "column_1",
    min_value={
        "$PARAMETER": column_1_mean,
    },
    max_value={
        "$PARAMETER": column_1_mean,
    },
)


validator_asset_1.save_expectation_suite(discard_failed_expectations=False)
validator_asset_2.save_expectation_suite(discard_failed_expectations=False)
```

GX Checkpoint and run - setup the checkpoint for execution
```python
checkpoint = gx.checkpoint.SimpleCheckpoint(
    name='checkpoint',
    data_context=context,
    validations=[
        {
            "batch_request": asset_1_request,
            "expectation_suite_name": 'suite_1',
        },
        {
            "batch_request": asset_2_request,
            "expectation_suite_name": 'suite_2',
        }
    ],
)

checkpoint.run()
```

Error Message - Error if the source asset (asset 1) mean is null.
![image](https://github.com/great-expectations/great_expectations/assets/9059807/6ff576b1-5f02-4a7e-b99d-e7c785f50de4)

> [!NOTE]\
> If you want to make it work, change the `None` value in the data setup to an actual numerical number. 

**Expected behavior**
Null value should be recognized and be used as comparison. If both asset_1 and asset_2 checks returns Null, the test should be successful 

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 0.17.2
 - Data Source: Pandas & Postgres. (Sample used is Sqlite for easy replication. It returns the same behavior)

**Additional context**
[Raised this as a clarification in discourse and Austin asked me if I can write a Github issue](https://discourse.greatexpectations.io/t/evaluation-parameter-null-return-behavior/1326)

**Comment by HaebichanGX** [comment]
Hi @ktc1016 thank you for raising this issue. I've put this into our backlog for engineering review

**Comment by molliemarie** [comment]
Hello @ktc1016. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
