### ISSUE TITLE
Hosted Environment DataContext, Checkpoint.run does not execute the supplied suite on the batch

### ISSUE THREAD

**Issue by KumarJayanti** [great-expectations/great_expectations#8536]
**Describe the bug**
I am trying to execute a suite by configuring a checkpoint with a BatchRequest and a test suite.  I am trying a hosted environment scenario. The run_checkpoint method does not run the suite and produces an empty ([]) results response.
**To Reproduce**
Please find the full self contained notebook [here](https://drive.google.com/file/d/1EKikDco43IDmuFfYrvD3TH4LfmZUMJwH/view?usp=sharing)

**Expected behavior**
run_checkpoint is expected to run the provided suite test_suite, but it does not.

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: 
 - Data Source: [e.g. Pandas, Snowflake]
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]

**Additional context**
As a workaround i just wanted to use validator but the validator does not seem to provide any way to execute the expectations on the batch of data even though it allows creation of a validator using the batchrequest and test suite.

**Comment by HaebichanGX** [comment]
Hi @KumarJayanti we have moved on from BatchRequest and configs to Fluent Data Source (FDS) methods. Please use this flowchart to visualize GX implementation end to end using FDS: https://miro.com/app/board/uXjVMsCjbE0=/

As we no longer support older version of GX, I will close this out this issue. If you have questions about FDS, please come to our gx-community-support slack channel
