### ISSUE TITLE
Validation results on PySpark dataframe marked as "success," failed expectations omitted

### ISSUE THREAD

**Issue by jonesmo** [great-expectations/great_expectations#8548]
**The Bug**
I'm running `.expect_column_values_to_not_be_null("col_name")` on a PySpark dataframe column that contains Python `None`.  I expect this validation to fail, but the validation suite succeeds with that particular expectation omitted from the validation result.  I'm also running `.expect_column_max_to_be_between("int_col_name", 0, 10)` on an integer column, and regardless of the values in the column, the validation suite succeeds.  If the column contains integers outside the (0, 10) range, the expectation is omitted from the validation result, but if it only contains integers in the (0, 10) range, it is included in the validation result.

**How to Reproduce**
```
    datasource = gx_context.sources.add_spark("event")
    data_asset = datasource.add_dataframe_asset(name="event")

    gx_context.add_or_update_expectation_suite("event")

    batch_request = data_asset.build_batch_request(dataframe=df)

    validator = gx_context.get_validator(
        batch_request=batch_request,
        expectation_suite_name="event",
    )

    validator.expect_table_row_count_to_be_between(1, None)
    validator.expect_table_column_count_to_equal(40)
    validator.expect_column_values_to_not_be_null("col_name")
    validator.expect_column_max_to_be_between("int_col_name", 0, 10, strict_min=True, strict_max=True)

    validator.save_expectation_suite()

    checkpoint = gx_context.add_or_update_checkpoint(
            name="event_checkpoint", validator=validator, expectation_suite_name="event"
        )
```
When the checkpoint runs, the validation suite succeeds, despite the fact that the "col_name" column contains `None` and the "int_col_name" column contains integers outside the (0, 10) range.  When I look at the logs, I see progress bars for these two expectations, but when I look at the checkpoint result, I see:
```
"validation_result": {
        "success": true,
        "results": [
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_table_row_count_to_be_between",
              "kwargs": {
                "max_value": null,
                "min_value": 1,
                "batch_id": "event-event"
              },
              "meta": {}
            },
            "result": {
              "observed_value": 21430
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          },
          {
            "success": true,
            "expectation_config": {
              "expectation_type": "expect_table_column_count_to_equal",
              "kwargs": {
                "value": 40,
                "batch_id": "event-event"
              },
              "meta": {}
            },
            "result": {
              "observed_value": 40
            },
            "meta": {},
            "exception_info": {
              "raised_exception": false,
              "exception_traceback": null,
              "exception_message": null
            }
          }
        ],
"statistics": {
          "evaluated_expectations": 2,
          "successful_expectations": 2,
          "unsuccessful_expectations": 0,
          "success_percent": 100.0
        }
```
The latter two validations don't seem to be getting picked up in the expectation suite.

Replacing `None` in "col_name" with `np.nan` yields the same results.  When I add `.expect_column_values_to_not_be_null()` expectations on columns that contain no `None`s or other kinds of nulls, they are included in the validation suite and they succeed.  When I add `.expect_column_values_to_not_be_null()` to multiple columns that contain `None`, they are all omitted from the validation result (eg, when I run that expectation against 22 columns, two of which contain `None`s, the statistics block lists "evaluated_expectations": 20).

**Expected behavior**
I expect `expect_column_values_to_not_be_null()` to fail the validation if `None` is found in the column, and I expect `expect_column_max_to_be_between()` to fail the validation if the integers contained in the column are outside the (0, 10) range.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.17.8
 - Data Source: PySpark df
 - Cloud environment: Airflow

**Comment by jonesmo** [comment]
Update: I tried explicitly replacing `None` with `np.nan` with the same results.

**Comment by jonesmo** [comment]
Update #2: `expect_column_values_to_not_be_null()` validations on columns that contains no `None`s succeed and appear in the validation suite.

**Comment by HaebichanGX** [comment]
@jonesmo Hey thanks for raising this issue, we've put it into our backlog for review

**Comment by HaebichanGX** [comment]
Hi @jonesmo so this isn't an issue. To discard failed expectations, you can run 

`validator.save_expectation_suite(discard_failed_expectations=False)` 

when saving expectation suite. 

Relevant Docs: https://docs.greatexpectations.io/docs/tutorials/getting_started/how_to_use_great_expectations_with_sql/#create-expectations

Please let me know if you see the same results. If so, I will close out this ticket

**Comment by jonesmo** [comment]
I do see the same results.  Thanks!

For what it's worth, we're using GX for the first time, and it's super confusing to have the default behavior be to ignore any failed expectations.  Maybe an explicit paragraph about that in the documentation would be useful?  Just a suggestion.

**Comment by HaebichanGX** [comment]
@jonesmo we're thinking the same after reviewing this, we're also thinking about having a print statement or a log when you don't ignore failed expectations. Thanks!
