### ISSUE TITLE
expect_compound_columns_to_be_unique with problems with timestamps

### ISSUE THREAD

**Issue by guicorsi** [great-expectations/great_expectations#8566]
**Describe the bug**
Hey, i'd tried to use the expect_compound_columns_to_be_unique expectation in a dataset with a timestamp column and i received the following error:

```
python3.9/site-packages/great_expectations/execution_engine/execution_engine.py", line 550, in _process_direct_and_bundled_metric_computation_configurations
raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: Casting to unit-less dtype 'datetime64' is not supported. Pass e.g. 'datetime64[ns]' instead.

```

**To Reproduce**
try to use this expectation in a dataset containing timestamp columns. example of the column value that brought this bug:
2023-07-14 00:00:00

**Expected behavior**
the expectation should not break with that kind of data

**Environment (please complete the following information):**
 - Operating System: Mac OS M1
 - Great Expectations Version: 0.17.9
 - Data Source: parquet processed with PySpark
 - Cloud environment: local

**Additional context**
it seems to be a simple casting problem, I cast the timestamp column to date and it worked.

**Comment by HaebichanGX** [comment]
Thank you for sharing this issue with us @guicorsi. Will put it into our backlog for review.

**Comment by molliemarie** [comment]
Hello @guicorsi. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
