### ISSUE TITLE
Quickstart Bug - context.view_validation_result(checkpoint_result) not opening results

### ISSUE THREAD

**Issue by Baelfur** [great-expectations/great_expectations#8590]
**Describe the bug**
I followed the [Quickstart Guilde](https://docs.greatexpectations.io/docs/tutorials/quickstart/) and when issuing the `context.view_validation_result(checkpoint_result)` command in a vscode notebook, the browser window opens to [This Page](https://www.msn.com/?ocid=iehp)

**To Reproduce**
```python
# %%
import great_expectations as gx

# %%
context = gx.get_context()

# %%
validator = context.sources.pandas_default.read_csv(
    "https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv"
)

# %%
validator.expect_column_values_to_not_be_null("pickup_datetime")
validator.expect_column_values_to_be_between("passenger_count", auto=True)
validator.save_expectation_suite()

# %%
checkpoint = context.add_or_update_checkpoint(
    name="my_quickstart_checkpoint",
    validator=validator,
)

# %%
checkpoint_result = checkpoint.run()

# %%
context.view_validation_result(checkpoint_result)
```

**Expected behavior**
I expected the browser window to load some sort of profile output

**Environment (please complete the following information):**
 - Operating System: 
Edition	Windows 11 Pro
Version	22H2
Installed on	‎6/‎10/‎2023
OS build	22621.2134
Experience	Windows Feature Experience Pack 1000.22659.1000.0

PS C:\Users\usr> systeminfo | findstr /B /C:"OS Version"
OS Version:                10.0.22621 N/A Build 22621

- Default Browser:
PS C:\Users\usr> reg query "HKEY_CURRENT_USER\Software\Microsoft\Edge\BLBeacon" /v version

HKEY_CURRENT_USER\Software\Microsoft\Edge\BLBeacon
    version    REG_SZ    115.0.1901.203

 - Great Expectations Version: [e.g. 0.13.2]
 (.venv) PS C:\Users\usr\OneDrive\Documents\dev\personal\gx_dev> great_expectations --version
great_expectations, version 0.17.10+0.g0d308ac69.dirty

- Python Version: 
(.venv) PS C:\Users\usr\OneDrive\Documents\dev\personal\gx_dev> python --version
Python 3.11.4

 - Data Source: [e.g. Pandas, Snowflake]
 "https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv"

 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]
 local

**Additional context**
**vsCode version**
(.venv) PS C:\Users\usr\OneDrive\Documents\dev\personal\gx_dev> code --version
1.81.1
6c3e3dba23e8fadc360aed75ce363ba185c49794
x64

**installed packages**
(.venv) PS C:\Users\usr\OneDrive\Documents\dev\personal\gx_dev> pip list --local
Package                   Version
------------------------- -----------
altair                    4.2.2
anyio                     3.7.1
argon2-cffi               23.1.0
argon2-cffi-bindings      21.2.0
arrow                     1.2.3
asttokens                 2.2.1
async-lru                 2.0.4
attrs                     23.1.0
Babel                     2.12.1
backcall                  0.2.0
beautifulsoup4            4.12.2
bleach                    6.0.0
certifi                   2023.7.22
cffi                      1.15.1
charset-normalizer        3.2.0
click                     8.1.7
colorama                  0.4.6
comm                      0.1.4
cryptography              41.0.3
debugpy                   1.6.7.post1
decorator                 5.1.1
defusedxml                0.7.1
entrypoints               0.4
executing                 1.2.0
fastjsonschema            2.18.0
fqdn                      1.5.1
great-expectations        0.17.11
idna                      3.4
ipykernel                 6.25.1
ipython                   8.14.0
ipython-genutils          0.2.0
ipywidgets                8.1.0
isoduration               20.11.0
jedi                      0.19.0
Jinja2                    3.1.2
json5                     0.9.14
jsonpatch                 1.33
jsonpointer               2.4
jsonschema                4.19.0
jsonschema-specifications 2023.7.1
jupyter                   1.0.0
jupyter_client            8.3.0
jupyter-console           6.6.3
jupyter_core              5.3.1
jupyter-events            0.7.0
jupyter-lsp               2.2.0
jupyter_server            2.7.2
jupyter_server_terminals  0.4.4
jupyterlab                4.0.5
jupyterlab-pygments       0.2.2
jupyterlab_server         2.24.0
jupyterlab-widgets        3.0.8
makefun                   1.15.1
MarkupSafe                2.1.3
marshmallow               3.20.1
matplotlib-inline         0.1.6
mistune                   3.0.1
nbclient                  0.8.0
nbconvert                 7.7.4
nbformat                  5.9.2
nest-asyncio              1.5.7
notebook                  7.0.2
notebook_shim             0.2.3
numpy                     1.25.2
overrides                 7.4.0
packaging                 23.1
pandas                    2.0.3
pandocfilters             1.5.0
parso                     0.8.3
pickleshare               0.7.5
pip                       23.2.1
platformdirs              3.10.0
prometheus-client         0.17.1
prompt-toolkit            3.0.39
psutil                    5.9.5
pure-eval                 0.2.2
pycparser                 2.21
pydantic                  1.10.12
Pygments                  2.16.1
pyparsing                 3.1.1
python-dateutil           2.8.2
python-json-logger        2.0.7
pytz                      2023.3
pywin32                   306
pywinpty                  2.0.11
PyYAML                    6.0.1
pyzmq                     25.1.1
qtconsole                 5.4.3
QtPy                      2.3.1
referencing               0.30.2
requests                  2.31.0
rfc3339-validator         0.1.4
rfc3986-validator         0.1.1
rpds-py                   0.9.2
ruamel.yaml               0.17.17
scipy                     1.11.2
Send2Trash                1.8.2
setuptools                65.5.0
six                       1.16.0
sniffio                   1.3.0
soupsieve                 2.4.1
stack-data                0.6.2
terminado                 0.17.1
tinycss2                  1.2.1
toolz                     0.12.0
tornado                   6.3.3
tqdm                      4.66.1
traitlets                 5.9.0
typing_extensions         4.7.1
tzdata                    2023.3
tzlocal                   5.0.1
uri-template              1.3.0
urllib3                   2.0.4
wcwidth                   0.2.6
webcolors                 1.13
webencodings              0.5.1
websocket-client          1.6.1
widgetsnbextension        4.0.8

**Comment by HaebichanGX** [comment]
Hi @Baelfur unfortunately GX doesn't officially support Windows at this time, which is likely the cause of the issue. On MacOS, the quickstart runs fine. Please let me know if this discussion can be helpful: 

https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1691996443796409

**Comment by dylanw-oss** [comment]
It has the same problem on WSL-Ubuntu.
Is there a way to output validation result to local folder? 

I added `build_data_docs()` but there is no html file output.
```python
context.view_validation_result(checkpoint_result)
context.build_data_docs()
```

**Comment by molliemarie** [comment]
Hello @Baelfur. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
