### ISSUE TITLE
Asset Name not showing on data docs for Spark Dataframe 

### ISSUE THREAD

**Issue by jmcorreia** [great-expectations/great_expectations#8594]
**Describe the bug**
I was trying to migrate my spark dataframe asset/source to fluent apis.
It seems to be working properly, however, the data_docs produced are presenting some inconsistencies.
Legacy:
- everything is filled
- batch id is auto generated
![image](https://github.com/great-expectations/great_expectations/assets/11615737/2aad06fe-65e8-4548-b6e6-a92fbbf8e6e6)

Fluent:
- asset_name not being field
- batch_id seems to have changed it type, as it is now, not an auto generated
![image](https://github.com/great-expectations/great_expectations/assets/11615737/c8886450-ebc7-432e-8224-ac096c98d15c)

**To Reproduce**
I have migrated from legacy to fluent datasource definition.
Below you find my configuration.

`
        context = great_expectations.get_context(project_config=cls._get_data_context_config())

        dataframe_datasource = context.sources.add_or_update_spark(
            name="datasource",
            force_reuse_spark_context=True,
            persist=False
        )

        dataframe_asset = dataframe_datasource.add_dataframe_asset(
            name="test",
            dataframe=df,
            # batch_metadata={
            #     "batch_identifiers": DQDefaults.DQ_BATCH_IDENTIFIERS.value
            # }
        )
        assert dataframe_asset.name == "test" # this is passing

        expectation_suite_name = name...""
        context.add_or_update_expectation_suite(
            expectation_suite_name=expectation_suite_name
        )
       
        batch_request = dataframe_asset.build_batch_request()
...
`

**Expected behavior**
Data Asset Name should show up in the site.

**Environment (please complete the following information):**
 - Operating System: Mac OS
 - Great Expectations Version: 0.17.11
 - Data Source: Spark Dataframe
 - Cloud environment: Databricks, Spark

**Comment by jmcorreia** [comment]
Not sure if relevant, but I am getting this log message
EphemeralDataContext has not implemented `_load_fluent_config()` returning empty `GxConfig`

**Comment by HaebichanGX** [comment]
@jmcorreia Hm... how strange let us put this into backlog for us to review.

**Comment by Kilo59** [comment]
@jmcorreia This was fixed in `0.18.14`

- https://github.com/great-expectations/great_expectations/pull/9950
