### ISSUE TITLE
Bug importing Custom Expectations on filesystem

### ISSUE THREAD

**Issue by mholubinka1** [great-expectations/great_expectations#8602]
**Describe the bug**

Following the steps to use custom expectations in the current documentation (https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_use_custom_expectations/)

```
context = gx.get_context()
from expectations.my_custom_expectation import ExpectMyCustomValues
```

When trying this with the following python project and code sample, I receive an import error per the attached screenshot:

Filesystem:

```
gx-dq
- great_expectations
  - plugins
    - expectations
      - __init__.py
      - my_custom_expectation.py
- helpers
- pre-processing
- config.py
- configure-gx.py
```

Code:

When executing this code snippet from either `config.py` or `configure-gx.ipynb`

```
import great_expectations as gx

context = gx.get_context(context_root_dir = absolute/path/to/great_expectations)
from expectations.my_custom_expectation import ExpectMyCustomValues
```
![0](https://github.com/great-expectations/great_expectations/assets/7592699/e7c91d3c-ad86-4820-8dcb-d2b9ff6f10cd)

**Expected behavior**

The custom expectations are imported successfully.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.17.7
 - Data Source: Pandas
 - Cloud environment: N/A

**Additional context**

In order for custom expectations to be in imported the expectations folder needs to be moved from `great_expectations/plugins/` to the root folder of the python project `gx-dq`

There is an additional report of this issue by another user in relation to Apache Airflow in the Slack channel [here](https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1689079211087069).

**Comment by HaebichanGX** [comment]
Issue has been resolved by removing the folder and restarting with FileDataContext method. https://greatexpectationstalk.slack.com/archives/CUTCNHN82/p1692795351336289?thread_ts=1689079211.087069&cid=CUTCNHN82
