### ISSUE TITLE
Add support for key-pair authentication to Snowflake data source

### ISSUE THREAD

**Issue by bennylu2** [great-expectations/great_expectations#8616]
**Is your feature request related to a problem? Please describe.**
Key-pair authentication was added previously in https://github.com/great-expectations/great_expectations/pull/1662 but the fluent snowflake data source currently does not support this authentication.

**Describe the solution you'd like**
Support of key-pair authentication for snowflake data source. The snowflake data source uses sqlalchemy and create_engine behind the scenes. Snowflake SQLAlchemy supports key-pair authentication https://github.com/snowflakedb/snowflake-sqlalchemy#key-pair-authentication-support therefore it is a simple feature to add

**Describe alternatives you've considered**
Although it's still possible to connect to Snowflake using the old data source api using the CLI, we'd like to use and follow the new fluent style

**Additional context**
- https://github.com/great-expectations/great_expectations/blob/develop/great_expectations/datasource/fluent/snowflake_datasource.py
- https://github.com/great-expectations/great_expectations/blob/bfccfd3ddf25cfff3e2c39162c7b2b1dd33c12b9/great_expectations/datasource/fluent/sources.pyi#L575

**Comment by nitishsahni** [comment]
Hi @Kilo59 👋 it would be great if we could get a sense of timeline with this feature request. I don't mind getting started with some work, so it's easier and faster to release. Let me know what you think - thanks!

**Comment by Kilo59** [comment]
Hi @bennylu2 and  @nitishsahni thanks for the feature request.
Sorry, I can't give a timeline or estimate on this feature request yet.

If this is something you would be interested in contributing to I would take a look here 👇
This method is responsible for creating and returning the SqlAlchemy engine. Any changes to how the `Engine` is created for the Snowflake Datasource would need to happen here.

https://github.com/great-expectations/great_expectations/blob/c087984dcd1a563ddc55888c7ab47bc3af566f38/great_expectations/datasource/fluent/snowflake_datasource.py#L126

**Comment by nitishsahni** [comment]
Thanks @Kilo59 !

**Comment by Kilo59** [comment]
@nitishsahni would you like me to assign this issue to you?

**Comment by jintaogao** [comment]
@Kilo59 
Hi,
I was wondering if there's update to this feature?

**Comment by Kilo59** [comment]
@bennylu2 @jintaogao 

We've added some minimal support for this in [`0.18.6`](https://github.com/great-expectations/great_expectations/releases/tag/0.18.16)

- https://github.com/great-expectations/great_expectations/pull/10031
- https://github.com/great-expectations/great_expectations/pull/10046

In a future release, we plan to make some other improvements such as improved documentation and not requiring a `password` to be provided when providing a `private_key`.
