### ISSUE TITLE
Unreadable rendering of data docs for a custom expectation

### ISSUE THREAD

**Issue by vasisthasinghal** [great-expectations/great_expectations#8632]
**Describe the bug**
I created a custom expectation - expect_multicolumn_sum_values_to_be_equal_to_single_column and when the data doc displays sampled unexpected values, it shows the decimal values in the different columns without any spaces, which makes it really difficult to read. 

**Snapshot**
![Screen Shot 2023-08-28 at 10 08 19 AM](https://github.com/great-expectations/great_expectations/assets/24483258/0e8d33bb-ac29-4a45-8662-67a1bb92bfac)

**Expected behavior**
The different values must be separated by a space or represented in different columns of the rendered table. 

**Environment (please complete the following information):**
 - Operating System: [MacOS]
 - Great Expectations Version: [e.g. 0.17.6]
 - Data Source: [Pandas]
 
**Additional context**

**Comment by HaebichanGX** [comment]
Hi @vasisthasinghal thank you for raising this issue. I'm not sure if this is a bug or a feature request, either way, we'll log this internally.

**Comment by molliemarie** [comment]
Hello @vasisthasinghal. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
