### ISSUE TITLE
Allow index columns to be used in expectations

### ISSUE THREAD

**Issue by konstantinkobs** [great-expectations/great_expectations#8708]
**Is your feature request related to a problem? Please describe.**
In my use case, I load data with specific index columns in order to later merge multiple datasets easily on index. However, I am not able to formulate expectations for the index column.

Demonstration code based on Quickstart guide:
```python
import great_expectations as gx
context = gx.get_context()
validator = context.sources.pandas_default.read_csv(
    "https://raw.githubusercontent.com/great-expectations/gx_tutorials/main/data/yellow_tripdata_sample_2019-01.csv", index_col="pickup_datetime"
)
validator.expect_column_values_to_match_regex(column="pickup_datetime", kwargs={"regex": "\d{4}\-\d{2}\-\d{2} \d{2}:\d{2}:\d{2}"})
```

This throws a `MetricResolutionError: Error: The column "pickup_datetime" in BatchData does not exist.` error. I also tried using "index" as the column parameter, with the same error.

**Describe the solution you'd like**
While it might be possible to create new expectations that are specifically designed for index columns of data sources, I think it would be easier to extend the existing expectation implementations to allow specifying the index column. I think this would prevent a large amount of duplicated code.

If this is possible, the profiler should also list the index column as a possible column to profile.

**Comment by austiezr** [comment]
Hey @konstantinkobs! Thanks for raising this; we've added this to our internal backlog for review. We'll leave this open for the next week if you have any other context you'd like to provide!

**Comment by MarcelBeining** [comment]
@austiezr You marked it as completed. How was this implemented now? Cannot find it.
