### ISSUE TITLE
Data Docs links are broken on Windows

### ISSUE THREAD

**Issue by robinstauntoncollins** [great-expectations/great_expectations#8710]
**Describe the bug**
The links to the validations and the expectation suite pages are broken on Windows due to incorrect generation of paths on Windows

Link from data docks main page to most recent validation:
`<myprojectdir>/great_expectations/uncommitted/data_docs/local_site/validations%5CMDS_PMDS_METRICS_EXPECTATIONS%5C20230913-133808-my-run-name-template%5C20230913T133808.191053Z%5Cmds_local_docker_db-my_table_asset.html`
The Expectation suite is called MDS_PMDS_METRICS_EXPECTATIONS so GX is adding %5C (backslash) character.
The path in my local directory is this:
`<myprojectdir>\great_expectations\uncommitted\data_docs\local_site\validations\MDS_PMDS_METRICS_EXPECTATIONS\20230830-114545-my-run-name-template\20230830T114545.993300Z\mds_local_docker_db-my_table_asset.html`

This issue applies to all parts of the data docs:
Status | Run Time | Run Name | Asset Name | Batch ID | Expectation Suite

**To Reproduce**
Please include your great_expectations.yml config, the code you’re executing that causes the issue, and the full stack trace of any error(s).

Unnecessary in this case I think.

**Expected behavior**
Links in data docs between main page, validations and expectations work correctly on windows.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.17.12
 - Data Source: MS SQL local docker instance
 - Cloud environment: None

**Additional context**

**Comment by robinstauntoncollins** [comment]
Duplicate of https://github.com/great-expectations/great_expectations/issues/8387

**Comment by r34ctor** [comment]
Hi @robinstauntoncollins, it looks like this issue may have been addressed with PR #8663. The next version of GX will be released tomorrow. Can you please check this against that new version?

**Comment by robinstauntoncollins** [comment]
@r34ctor Yep, works as expected now. Thanks!

**Comment by r34ctor** [comment]
Perfect, thank you! I'll close this out.
