### ISSUE TITLE
Great Expectations Airflow operator unable to create expectation suit on S3.

### ISSUE THREAD

**Issue by da-sbarde** [great-expectations/great_expectations#8718]
I am using GreatExpectationOperator with airflow. The expectation store is setup on S3, below are the yaml configurations for the same- 
        stores:
          expectations_S3_store:
            class_name: ExpectationsStore
            store_backend:
              class_name: TupleS3StoreBackend
              bucket: {expectations_bucket}
              prefix: {expectations_prefix}
              
My Airflow tasks can access the S3 locations specified, but when I try to create expectation suit to be used for GE operator using following code -
    suite = context_gx.create_expectation_suite(
        expectation_suite_name, overwrite_existing=True
    )
    
I get error unable to set object in S3. 
To my wonder it only happens when I use GE operator, I can create expectation suites with python task in airflow but not with GE operator.

**Comment by da-sbarde** [comment]
I believe this is due to the dependancies mainly boto3 and botocore.
GE operator requires boto3 version <1.16.0,>=1.15.0 and botocore<1.19.0,>=1.18.0, which are not the latest.

**Comment by rachhouse** [comment]
Hi @da-sbarde, thanks for reaching out! Can also you let us know:
* The version of GX you're using
* Your Operating System

**Comment by rachhouse** [comment]
Hi @da-sbarde, since we haven't heard back from you, I'm going to close out this issue for now. Feel free to reopen it with added context if needed, thanks!
