### ISSUE TITLE
Missing docker image documentation

### ISSUE THREAD

**Issue by benelot** [great-expectations/great_expectations#8733]
Hello there!

On dockerhub, there seem to be 3 docker images that get quite regular updates, but I can not find any documentation on them:
* greatexpectations/jupyter
* greatexpectations/agent
* greatexpectations/test

Are they official? What are they for?

**Comment by rachhouse** [comment]
Hi @benelot, thanks for your question!

These Docker images are currently under development internally and are not yet official or documented for public use. Apologies for the confusion!

**Comment by rachhouse** [comment]
Hi @benelot, would you be interested in speaking with a GX engineer about your interest/need for Docker containers in your GX workflow? I asked internally about making those existing Docker Hub images private for now (to avoid future confusion), and there's interest on our side in understanding how you're containerizing and deploying GX in your workflow.

Thanks for considering!

**Comment by benelot** [comment]
Hi @rachhouse 
Thank you for the update! I indeed was a bit confused as they seem to cover some specific use cases, but it is not immediately clear what they are for.

I am currently looking into a deployment via the dagster-ge integration, but I am not sure yet if that is going to cover all our needs. So once that is ready, I am very interested to talk with a GX engineer about our current setup and if it matches our expectations ;-)

Can I give you a shout out in a couple of weeks here?

**Comment by rachhouse** [comment]
@benelot Absolutely (just tag me on this issue when you're ready) and thanks!
