### ISSUE TITLE
Data docs without internet access

### ISSUE THREAD

**Issue by Joul1285** [great-expectations/great_expectations#8734]
**Describe the bug**
Data docs is unusable when accessing it without internet access because of JavaScript dependencies (jquery, bootstrap, ect.).

`n.css net::ERR_ABORTED 403 (Forbidden)
index.html:14     GET https://unpkg.com/bootstrap-table@1.19.0/dist/extensions/filter-control/bootstrap-table-filter-control.min.css net::ERR_ABORTED 403 (Forbidden)
index.html:221     GET https://unpkg.com/bootstrap-table@1.19.1/dist/bootstrap-table.min.js net::ERR_ABORTED 403 (Forbidden)
index.html:216     GET https://kit.fontawesome.com/8217dffd95.js net::ERR_ABORTED 403 (Forbidden)
index.html:222     GET https://unpkg.com/bootstrap-table@1.19.1/dist/extensions/filter-control/bootstrap-table-filter-control.min.js net::ERR_ABORTED 403 (Forbidden)
index.html:1 Access to script at 'https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index.html:219     GET https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js net::ERR_FAILED 403 (Forbidden)
index.html:15     GET https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css net::ERR_ABORTED 403 (Forbidden)
index.html:223     GET https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js net::ERR_ABORTED 403 (Forbidden)
index.html:1 Access to script at 'https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js' from origin 'null' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
index.html:220     GET https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js net::ERR_FAILED 403 (Forbidden)
index.html:213     GET https://cdn.jsdelivr.net/npm/vega@5 net::ERR_ABORTED 403 (Forbidden)
index.html:16     GET https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.1.0/dist/css/bootstrap-prefers-dark.css net::ERR_ABORTED 403 (Forbidden)
index.html:214     GET https://cdn.jsdelivr.net/npm/vega-lite@4 net::ERR_ABORTED 403 (Forbidden)
index.html:12     GET https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css net::ERR_ABORTED 403 (Forbidden)
index.html:215     GET https://cdn.jsdelivr.net/npm/vega-embed@6 net::ERR_ABORTED 403 (Forbidden)
index.html:218     GET https://code.jquery.com/jquery-3.4.1.min.js net::ERR_ABORTED 403 (Forbidden)
index.html:539 Uncaught ReferenceError: $ is not defined
    at index.html:539:3
(anonymous) @ index.html:539
index.html:557 Uncaught ReferenceError: $ is not defined
    at hide_cards (index.html:557:5)
    at index.html:559:3
hide_cards @ index.html:557
(anonymous) @ index.html:559
index.html:570 Uncaught ReferenceError: $ is not defined
    at index.html:570:11
(anonymous) @ index.html:570
index.html:805 Uncaught ReferenceError: $ is not defined
    at index.html:805:3
(anonymous) @ index.html:805
index.html:907 Uncaught ReferenceError: $ is not defined
    at index.html:907:3
(anonymous) @ index.html:907
index.html:971 Uncaught ReferenceError: $ is not defined
    at index.html:971:5
(anonymous) @ index.html:971
index.html:979     GET https://great-expectations-web-assets.s3.us-east-2.amazonaws.com/full_logo_dark.png 403 (Forbidden)
index.html:591     GET https://great-expectations-web-assets.s3.us-east-2.amazonaws.com/logo-long.png?d=20230919T115355.831453Z&dataContextId=dae5555c-fe8d-4441-b9c7-9a31ef622b02 403 (Forbidden)`

**Environment:**
great_expectations = "0.15.50" 

Is there any way to embedded those JavaScript ?

**Comment by rachhouse** [comment]
Hi @Joul1285, thanks for your feedback! Offline Data Docs are not a feature that GX plans to support, so I'm going to go ahead and close out this issue.
