### ISSUE TITLE
Partial_unexpected_list should appear in data docs when result_format is SUMMARY 

### ISSUE THREAD

**Issue by FlorianDG** [great-expectations/great_expectations#8759]
**Describe the bug**
When generating data docs using Great Expectations, the partial_unexpected list is not included in the resulting documentation when _result_format_ is set to SUMMARY on checkpoint level.

**To Reproduce**

1. Set up a Great Expectations project and a DataContext using S3 and pandas.
2. Create an expectation suite with one or more expectations that may result in partial unexpected values.
3. Setup and run a checkpoint to generate data docs using `"result_format":"SUMMARY"`, e.g.:

```python
checkpoint = context.add_or_update_checkpoint(

         ...

         runtime_configuration={
            "result_format": {
                "result_format": "SUMMARY",
                "partial_unexpected_count": 5,
                "unexpected_index_column_names": ["Colum_Token"]
            }})
``` 

5. Navigate to the generated data docs and inspect the expectation details. See that the partial_unexpected_list is not rendered in the data docs, but included in the validation JSON.

**Expected behavior**
The partial_unexpected list is expected to be included in the expectation details section of the data docs of failed expectations as indicated in the [documantation](https://docs.greatexpectations.io/docs/reference/expectations/result_format).

**Environment (please complete the following information):**
 - Operating System:  (MacOS)
 - Great Expectations Version: [0.17.15]
 - Data Source:  Pandas / S3
 - Cloud environment:  AWS

**Additional context**
In our case, we would like to have the possibility to add additional column information to the data docs (e.g. a unique token) in case of failed expectations just as it is included in the partial_unexpected_list but not rendered into the data docs, to make data sessions uniquely identifiable outside of great expectations without using result_format="COMPLETE" in a production setting. This would provide more flexibility to users in customizing the output format in data docs for specific expectations within a checkpoint. This allows for a finer level of control over how results are presented, enhancing the usability of Great Expectations for Business Users.

**Comment by rachhouse** [comment]
Hi @FlorianDG, thanks for surfacing this issue! We've captured it for internal review.

**Comment by molliemarie** [comment]
Hello @FlorianDG. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
