### ISSUE TITLE
[DATA LEAKS] : Handling PII Data Exposure - Validation results format

### ISSUE THREAD

**Issue by MMoussabbih** [great-expectations/great_expectations#8780]
Hello everyone,

I hope you're all doing well. I wanted to share with you a critical issue that has come to our attention while using `great-expectations`. Specifically, we need to address the potential exposure of **Personally Identifiable Information (PII)** data.

As we all know, protecting the **privacy** and **security** of user data is paramount. PII data includes sensitive information such as names, addresses, phone numbers, and email addresses, among others. If this data were to be inadvertently exposed through, it could have serious consequences for both our users and our project's reputation.

During the validation stage of an expectation suite, since we want to get indexes for rejected lines through `unexpected_index_list`, we are using the following `result_format` :

```python
"result_format": { 
      "result_format": "COMPLETE",
      "partial_unexpected_count": 0,
      "unexpected_index_column_names": ["__id"],
      "include_unexpected_rows": False,
}
``` 

As a result, if we take the example of `expect_column_values_to_match_regex` on `USER_EMAIL` column for PII data related to **customers**, we are getting the following format for `unexpected_index_list` and `unexpected_list` : 

```python
"unexpected_index_list": [
      {
            "__id" : 14997,
            "USER_EMAIL": "john-doe@gmamil.com"
      },
      {
            "__id" : 15600,
            "USER_EMAIL": "johannadeo1988@outlook.cmo"
      },
      ...
],
"unexpected_list": [
      "john-doe@gmamil.com",
      "johannadeo1988@outlook.cmo",
      ...
]
``` 
In our case, the validation store is public (on a AWS S3 bucket), where we can find validation JSON files for both PII and no PII data. So, it's clear that we are facing a PII data leak in this case, that is why we are looking for adding a new parameter in `result_format` to only have only indexes in `unexpected_index_list` and an empty `unexpected_list`, i.e : something like this : 

For the result_format below : 

```python
"result_format": { 
      "result_format": "COMPLETE",
      "partial_unexpected_count": 0,
      "unexpected_index_column_names": ["__id"],
      "include_unexpected_rows": False,
      "UNEXPECTED_LISTS_WITH_VALUES": False,
}
``` 

We get :

```python
"unexpected_index_list": [
      {
            "__id" : [14997, 15600, ...],
      }
],
"unexpected_list": [ ]
```

We would like to know if such a feature could be interesting for you, and how much is it possible to deploy a **new release** supporting this functionality, since we are working on this new implementation and we would gladly create a **Pull Request** for it, if you consider this issue worth addressing ?

Thanks in advance.

**Comment by r34ctor** [comment]
Hi @MMoussabbih, thanks for bringing this up! The ability to better control what data is returned in the validation result is on our roadmap. I'll keep this issue open in case we have more updates for you.

**Comment by MMoussabbih** [comment]
Hi @r34ctor,
Thanks for your answer.
I invite you to see what we have already done to implement this solution : https://github.com/great-expectations/great_expectations/pull/8785. Waiting for your feedback 👍
