### ISSUE TITLE
expect_column_values_to_match_regex looks broken

### ISSUE THREAD

**Issue by gerileka** [great-expectations/great_expectations#8782]
**Describe the bug**
Hopefully I am wrong but isn't this `expect_column_values_to_match_regex` failing here ? 

**To Reproduce**
Using the pyspark table below :
```python
mock_orders =[
            {
                "concept_id": "5da593fa-a3ce-4a1f-84cc-9b4f76ddb5e5",
                "country": "UK",
                "id": "Ligne 1",

            },
            {
                "concept_id": 1,
                "country": "UK",
                "id":"Ligne 2",
            },
]

spark = SparkSession.builder.getOrCreate()
orders_reference = spark.createDataFrame(data = mock_orders)

table_name = "orders_table"
pyspark_dataframe = orders_reference
"""Create and append validation given schema"""
# Pyspark Connection
context = gx.get_context()
datasource = context.sources.add_or_update_spark(name="spark_data_source")
data_asset = datasource.add_dataframe_asset(name=table_name)
batch_request = data_asset.build_batch_request(dataframe=pyspark_dataframe)

# Create expectations
context.add_or_update_expectation_suite("spark_data_validation")

# Create a validator
validator = context.get_validator(
    batch_request=batch_request, expectation_suite_name="spark_data_validation"
)

validator.expect_column_values_to_match_regex("concept_id",regex_pattern="^[0-9a-fA-F]{8}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{4}\b-[0-9a-fA-F]{12}$",
                                             mostly=1.0)


```

I am getting this results:
```shell
{
  "success": true,
  "result": {
    "element_count": 2,
    "unexpected_count": 0,
    "unexpected_percent": 0.0,
    "partial_unexpected_list": [],
    "missing_count": 0,
    "missing_percent": 0.0,
    "unexpected_percent_total": 0.0,
    "unexpected_percent_nonmissing": 0.0
  },
  "meta": {},
  "exception_info": {
    "raised_exception": false,
    "exception_traceback": null,
    "exception_message": null
  }
}
```

**Expected behavior**
It should be a fail since the column concept_id doesn't has a problem in the second row. 

**Environment (please complete the following information):**
 - Operating System: [MacOS]
 - Great Expectations Version: ['0.17.19']
 - Data Source: [Pyspark]
 - Cloud environment: [AWS]

**Comment by r34ctor** [comment]
Hi @gerileka, thanks for raising this! We've captured this for review and will investigate.

**Comment by gerileka** [comment]
@r34ctor great thanks. We switched to `expect_column_values_to_match_regex_list` for the time being

**Comment by molliemarie** [comment]
Hello @gerileka. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
