### ISSUE TITLE
Unable to run context.convert_to_file_context() when using a Data Docs site on \$web container

### ISSUE THREAD

**Issue by LvffY** [great-expectations/great_expectations#8843]
**Describe the bug**

Unable to run `context.convert_to_file_context()` when using Azure data site on `\$web` container.

It fails with the error : 

![image](https://github.com/great-expectations/great_expectations/assets/37327656/818f43a9-3d9c-47f8-ab3d-338672bbc1b4)

**To Reproduce**

Run the following commands : 

```python
import great_expectations as gx
from great_expectations.checkpoint import Checkpoint
context_root_dir = "/dbfs/FileStore/foobar"
context = gx.get_context(context_root_dir=context_root_dir)
## Here the context.convert_to_file_context() works
context.add_data_docs_site(
    "az_site",
    {
        "class_name": "SiteBuilder",
        "store_backend": {
            "class_name": "TupleAzureBlobStoreBackend",
            "container": "\$web",
            "connection_string": azure_connection_string,
        },
    },
)
context.convert_to_file_context() ## This doesn't work.
```

**Expected behavior**

Being able to convert to file context even with `\$web` variable in configuration.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.17.22
 - Data Source: Spark DataFrame
 - Cloud environment: Azure Databricks

**Additional context**

**Comment by HaebichanGX** [comment]
Hi @LvffY thank you for raising this issue. We'll put it into back for engineering review.

**Comment by molliemarie** [comment]
Hello @LvffY. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
