### ISSUE TITLE
Be able to store metrics data over time in site

### ISSUE THREAD

**Issue by LvffY** [great-expectations/great_expectations#8844]
**Is your feature request related to a problem? Please describe.**

We'd like to be able to track the issues overtime of multiple suites. To do so, we'd like to be able to : 

- have multiple suites in our data site that are not necesseraliy part of the great expectations run. This would allow multiple projects to have the same data site and track their data quality issues together (and avoid OPS teams to generate multiple Azure storage accounts to store each website)
- for each suite : being able to have multiple runs stored and printed whenever the site is generated.

      May be I missed some documentation about this. I've already set up an expectations and validations store, but may be I need to configure some other external stores ?

**Describe the solution you'd like**

I'd like to be able to have some kind of shared backend databases that would be used to regenerate the site each time we generate it. This way, we could have some kind of historic website and be able to compare when an issues have been resolved of appeared for example.

**Comment by HaebichanGX** [comment]
Hi @LvffY this is a great idea and thank you for this request. I'll log this as Feature Request and close out the issue as it's captured internally in our system.
