### ISSUE TITLE
query must start with 'SELECT' followed by a whitespace. (type=value_error)"

### ISSUE THREAD

**Issue by amruth301** [great-expectations/great_expectations#8853]
**Describe the bug**
We see error when creating query asset with snowflake db if query does not start with  SELECT.  like query = ("WITH max_created AS (SELECT MAX(created_at) mx_cr FROM table_name) SELECT " "DATEDIFF(day,mx_cr,CURRENT_TIMESTAMP()) AS diffFROM max_created"). Getting error as  "File /venv/lib/python3.11/site-packages/great_expectations/datasource/fluent/sql_datasource.py", line 1136, in add_query_asset
    asset = self._QueryAsset(
            ^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for QueryAsset
query
  query must start with 'SELECT' followed by a whitespace. (type=value_error)".

**To Reproduce**
Create a data asset with query. Query should not start with SELECT
**Expected behavior**
Should be able to create data asset with any working query since snowflake accepts query with any format.

**Environment (please complete the following information):**

**Additional context**

**Comment by HaebichanGX** [comment]
Hi @amruth301 this isn't so much of a bug more so expected format that we defined for the **add_query_asset**. Can you change your query to something like 

`SELECT DATEDIFF(day, (SELECT MAX(created_at) FROM table_name), CURRENT_TIMESTAMP()) AS diff;
`

And use that for the **query** parameter?

**Comment by HaebichanGX** [comment]
Closing this ticket out due to no response for a week

**Comment by jsantangelo-rl** [comment]
It's really easy to write a query that needs to be rewritten with [CTEs](https://docs.snowflake.com/en/user-guide/queries-cte) in order for it to readable. For example, anything with joins to subqueries. It would be nice if `WITH my_cte AS (...) SELECT ...` was supported.
