### ISSUE TITLE
If checkpoint batch request  has options provided :  getting error as great_expectations.exceptions.exceptions.InvalidBatchRequestError: BatchRequest should have form:"  {'batch_slice': None,  'data_asset_name': 'accounts',  'datasource_name': 'snowflake_test_datasource',  'options': {}} but actually has form: {'batch_slice': None,  'data_asset_name': 'accounts',  'datasource_name': 'snowflake_test_datasource',  'options': {'number': '3AAA13513', 'code': '3AAALB'}}.

### ISSUE THREAD

**Issue by amruth301** [great-expectations/great_expectations#8854]
If checkpoint batch request  has options provided :  getting error as 
```python
great_expectations.exceptions.exceptions.InvalidBatchRequestError: BatchRequest should have form:
{
 'batch_slice': None,
 'data_asset_name': 'accounts', 
 'datasource_name': 'snowflake_test_datasource',
 'options': {}
}
 but actually has form:
{
 'batch_slice': None,
 'data_asset_name': 'accounts',
 'datasource_name': 'snowflake_test_datasource',
 'options': {
     'number': '3AAA13513', 'code': '3AAALB'
  }
}.
```

**To Reproduce**
```python
ontext.add_or_update_checkpoint(
    name="no_nesting1",
    run_name_template="%Y-%M-foo-bar-template-$VAR",
    validations=[
        {
            "batch_request": {
                "datasource_name": "snowflake_test_datasource",
                "data_asset_name": "accounts",
                "options": {"code": "3AAALB", "number": "3AAA13513"},
            },
            "expectation_suite_name": "my_onboarding_assistant_suite",
            "action_list": [
                {
                    "name": "store_validation_result =",
                    "action": {"class_name": "StoreValidationResultAction"},
                },
                {
                    "name": "store_evolution_params",
                    "action": {"class_name": "StoreEvaluationParametersAction"},
                },
                {
                    "name": "update_data_docs",
                    "action": {"class_name": "UpdateDataDocsAction"},
                },
                {
                    "name": "slack_notification",
                    "action": {
                        "class_name": "SlackNotificationAction",
                        "slack_webhook": "https://hooks.slack.com/services/",
                        "notify_on": "all",
                        "renderer": {
                            "module_name": "great_expectations.render.renderer.slack_renderer",
                            "class_name": "SlackRenderer"
                        }
                    }
                }
            ],
        }
    ],
    evaluation_parameters={"GT_PARAM": 1000, "LT_PARAM": 50000},
    runtime_configuration={
        "result_format": {"result_format": "BASIC", "partial_unexpected_count": 20}
    },
).    
```

**Expected behavior**
Check should be created with options as well. 

But got the error as mentioned above

**Comment by Slaiby** [comment]
Same issue @amruth301

**Comment by molliemarie** [comment]
Hello @amruth301. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
