### ISSUE TITLE
Send validation result to Datahub not work

### ISSUE THREAD

**Issue by irisywy6201** [great-expectations/great_expectations#8856]
**Describe the bug**
Send validation result to Datahub not work

**To Reproduce**
python version = 3.8
1. setup mariadb on localhost:49153 & datahub on localhost:9002/
2. save datasource
```
import great_expectations as ge
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.checkpoint import SimpleCheckpoint
from great_expectations.cli.datasource import sanitize_yaml_and_save_datasource

t = 'mysql+pymysql://root:root@127.0.0.1:49153/demo'
context = ge.get_context()
config = f"""
  name: my_sqlite_datasource
  class_name: Datasource
  execution_engine:
    class_name: SqlAlchemyExecutionEngine
    connection_string: mysql+pymysql://root:root@127.0.0.1:49153/demo
  data_connectors:
    default_runtime_data_connector_name:
      class_name: RuntimeDataConnector
      module_name: great_expectations.datasource.data_connector
      batch_identifiers:
        - default_identifier_name
    default_inferred_data_connector_name:
      class_name: InferredAssetSqlDataConnector
      module_name: great_expectations.datasource.data_connector
      include_schema_name: True
  """
context.test_yaml_config(
    yaml_config=config
)
sanitize_yaml_and_save_datasource(context, config, overwrite_existing=True)
```

3. create expectation suite
```
from great_expectations.checkpoint import SimpleCheckpoint
from great_expectations.cli.datasource import sanitize_yaml_and_save_datasource

t = 'mysql+pymysql://root:root@127.0.0.1:49153/demo'
context = ge.get_context()
config = f"""
  name: my_sqlite_datasource
  class_name: Datasource
  execution_engine:
    class_name: SqlAlchemyExecutionEngine
    connection_string: mysql+pymysql://root:root@127.0.0.1:49153/demo
  data_connectors:
    default_runtime_data_connector_name:
      class_name: RuntimeDataConnector
      module_name: great_expectations.datasource.data_connector
      batch_identifiers:
        - default_identifier_name
    default_inferred_data_connector_name:
      class_name: InferredAssetSqlDataConnector
      module_name: great_expectations.datasource.data_connector
      include_schema_name: True
  """
context.test_yaml_config(
    yaml_config=config
)
sanitize_yaml_and_save_datasource(context, config, overwrite_existing=True)
```
4. create batch request
```
batch_request = RuntimeBatchRequest(
    datasource_name="my_sqlite_datasource",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="demo.users",
    runtime_parameters={
        "query": "select * from demo.users",
    },
    batch_identifiers={"default_identifier_name": "default_identifier_name"},
    batch_spec_passthrough={"create_temp_table": False},
)
```
5. create checkpoint and run
```
checkpoint = context.add_or_update_checkpoint(
    name="my_checkpoint",
    validations=[
        {
            "batch_request": batch_request,
            "expectation_suite_name": "my_suite",
        },
    ],
    action_list=[
        {
            "name": "datahub_action",
            "action": {
                "module_name": "datahub.integrations.great_expectations.action",
                "class_name": "DataHubValidationAction",
                "server_url": "http://localhost:9002"
            },
        },
    ]
)

checkpoint_result = checkpoint.run()
```
the result output is: 
`Enable parse_table_names_from_sql in DatahubValidationAction config                            to try to parse the tables being asserted from SQL query
Metadata not sent to datahub. No datasets found.`
and there is no validation result in datahub.

**Expected behavior**
see the validation result in datahub

**Screenshots**
<img width="773" alt="image" src="https://github.com/datahub-project/datahub/assets/20381545/9394a1b4-9f33-4390-b975-661cd084c505">

**Desktop (please complete the following information):**
 - OS: windows

**Comment by umawani** [comment]
This might not be the answer to your issue but when I was implementing the Datahub action in my case, I had to also include another input called 'platform_instance_map'. This map is used to map your current Checkpoint execution's data asset to the dataset with the correct platform instance (i.e, postgres-2).

Here is an example of how I use it:

```
name: checkpoint-test
module_name: great_expectations.checkpoint
class_name: Checkpoint
action_list:
  - name: datahub_action
    action:
      module_name: datahub.integrations.great_expectations.action
      class_name: DataHubValidationAction
      server_url: ${dh_url_env}
      platform_instance_map:
        test_db: postgres-2
      token: ${dh_token_env}
runtime_configuration: {
  "result_format": {
    "result_format": "SUMMARY",
    "return_unexpected_index_query": True,
    "partial_unexpected_count": 3,
    "include_unexpected_rows": True
  }
}
```

Over here, the 'test_db' is the equivalent of 'my_sqlite_datasource' in your configuration

Hope this helps! :)

**Comment by HaebichanGX** [comment]
Hi @irisywy6201 you're implementing a previous version of GX, which uses block configs (Data connectors and RuntimeBatchRequest). Can you please update your code to the latest version of GX, the Fluent Data Source (FDS)? You can use this flowchart to understand how all the visual components intersect https://miro.com/app/board/uXjVMsCjbE0=/

**Comment by HaebichanGX** [comment]
closing this out due to no response for a week

**Comment by kpmg-rvangenechten** [comment]
> Hi [@irisywy6201](https://github.com/irisywy6201) you're implementing a previous version of GX, which uses block configs (Data connectors and RuntimeBatchRequest). Can you please update your code to the latest version of GX, the Fluent Data Source (FDS)? You can use this flowchart to understand how all the visual components intersect https://miro.com/app/board/uXjVMsCjbE0=/

does this even work with datahub_action seems like it still expects runtime_parameters

'BatchRequest' object has no attribute 'runtime_parameters'
