### ISSUE TITLE
unexpected_index_query use temp table with RuntimeBatchRequest

### ISSUE THREAD

**Issue by a-chumagin** [great-expectations/great_expectations#8860]
If I set GX with  block config method and RuntimeBatchRequest then unexpected_index_query returns query to temp table 

**To Reproduce**
I use the next params: 
```
datasource_config = {
    "name": "my_mysql_datasource",
    "class_name": "Datasource",
    "execution_engine": {
        "class_name": "SqlAlchemyExecutionEngine",
        "connection_string": "mysql+pymysql://root:root@0.0.0.0:3306/test_db",
    },
    "data_connectors": {
        "default_runtime_data_connector_name": {
            "class_name": "RuntimeDataConnector",
            "batch_identifiers": ["default_identifier_name"],
        },
        "default_inferred_data_connector_name": {
            "class_name": "InferredAssetSqlDataConnector",
            "include_schema_name": True,
        },
    },
}
context.add_datasource(**datasource_config)

from great_expectations.core.batch import BatchRequest, RuntimeBatchRequest

batch_request = RuntimeBatchRequest(
    datasource_name="my_mysql_datasource",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="default_name",
    runtime_parameters={"query": "SELECT * from test_db.students"},
    batch_identifiers={"default_identifier_name": "default_identifier"},
)

result_format: dict = {
    "result_format": "COMPLETE",
    "unexpected_index_column_names": ["id"],
    "return_unexpected_index_query": True
}
result = checkpoint.run(result_format=result_format)
```
```
"unexpected_index_query": "SELECT id, first_name \nFROM gx_temp_0286f299 \nWHERE first_name IS NULL;"
```

**Expected behavior**
unexpected_index_query should use a table from runtime_parameters but not temp

**Environment (please complete the following information):**
 - Operating System: MacOS 
 - Great Expectations Version: 0.17.23
 - Data Source: MySql

**Additional context**
Fluent data source with asset works fine

**Comment by HaebichanGX** [comment]
Hey @a-chumagin as you're pointed out, the compatibility among those sub-products is meant for FDS, not block configs. We've fully moved on from this method, so we aren't able to work on this issue. It might also be a compatibility thing. We'll close this issue for now, but feel free to reopen in case there's something we're missing. THanks!

**Comment by a-chumagin** [comment]
@HaebichanGX thank you for your response. I think is a good idea to add this in the documentation/ Because it really confuses users.
