### ISSUE TITLE
AWS Athena regex

### ISSUE THREAD

**Issue by Pim-Claessens** [great-expectations/great_expectations#8875]
**Is your feature request related to a problem? Please describe.**
Currently, trying something like 'expect_column_values_to_match_regex' fails with the dialect not implemented error. But the regex expressions do have support for trino.

**Describe the solution you'd like**
Given that Trino and AWS Athena are basically the same in this regard (and probably across the board for most cases). Can AWS Athena and Trino be treated similar? I'm not sure how that will break other stuff, but most of the basic regex matching and stuff is exactly the same

**Comment by HaebichanGX** [comment]
Thank you for your feature request! I've recorded this in our backlog and will close this out.
