### ISSUE TITLE
Support table sampling in fluent configuration

### ISSUE THREAD

**Issue by YoitoFes** [great-expectations/great_expectations#8890]
Fluent configuration does not support for sampling tables.

It would be great if sampling tables was supported in fluent configuration as well as splitting table.

Thank you.

**Comment by HaebichanGX** [comment]
Hi @YoitoFes to sample tables, you can use a validator object in our fluent data source method. for splitting tables, you can do `asset.add_splitter` method for SQL databases, or run `batching_regex` for filesystem datasource. You can use this flowchart for visual workflow: https://miro.com/app/board/uXjVMsCPLaM=/

We have public docs on this as well: https://docs.greatexpectations.io/docs/guides/connecting_to_your_data/fluent/data_assets/how_to_organize_batches_in_a_sql_based_data_asset/#3-add-a-splitter-to-the-data-asset

**Comment by Kirill-Ulich** [comment]
Ok. How to split single file data to several batches?

**Comment by HaebichanGX** [comment]
Hi @Kirill-Ulich can you please go to our gx-community-channel in slack to answer this question? We'll have dedicated developer relations team to answer your question, as it's a better platform to engage in these discussions. I'll close out this PR for now.

**Comment by YoitoFes** [comment]
@HaebichanGX Thank you for your answer.

In block-style configuration, `sampling_method`s (e.g. `sample_using_random`) are available
- https://docs.greatexpectations.io/docs/0.15.50/guides/connecting_to_your_data/advanced/how_to_configure_a_dataconnector_for_splitting_and_sampling_tables_in_sql/

... and I requested to make  `sampling_method`s available in fluent configuration. Sorry for the description is unclear.
