### ISSUE TITLE
Why GX has notebook as a dependency?

### ISSUE THREAD

**Issue by alejandrofm** [great-expectations/great_expectations#8897]
**Is your feature request related to a problem? Please describe.**
Installing notebook gets many dependencies attached, which when used without notebooks are not needed and generate overhead.

**Describe the solution you'd like**
Clarify if notebook/Ipython are needed or give an option to avoid full installation

Thats, it
Thanks!

**Comment by tb102122** [comment]
So far lazy imports and pip install with different scopes is not supported.

**Comment by HaebichanGX** [comment]
thanks @alejandrofm appreciate this feature request. Please take a look at @tb102122 's comment above. I'll capture this information internally and close out this ticket.
