### ISSUE TITLE
Example tests not passing on version 0.18.0

### ISSUE THREAD

**Issue by dmitriy-p-petrov** [great-expectations/great_expectations#8909]
**Describe the bug**
Hey, man. It seems like the example cases aren't working properly on the newest version whenever you try to create a custom expectation. Haven't looked too deep into it as i'm currently at work.

**To Reproduce**
The config should be the basic one, since i only ran `great_expectations init` and put my expectation template in /plugins/expectations/

Just copy everything from this page:

https://docs.greatexpectations.io/docs/guides/expectations/creating_custom_expectations/how_to_create_custom_column_pair_map_expectations#add-example-cases

until you reach the positive/negative example and try running. In my case it says `failing: -all` and if i enable the debug logger i see the following message:

`(generate_expectation_tests) PROBLEM with get_test_validator_with_data in backend pandas for expect_column_not_blank_when_another_column_equals_specific_value from data (no data_alt to try) ValueError('Provided mode ephemeral returned context of type FileDataContext instead of EphemeralDataContext; please check your input arguments.')`

Not sure if i do something wrong, tho, so apologies if this is the case.

**Expected behavior**
Well, the expected behaviour should be all tests passing properly as they do on version 0.16.16.

**Environment (please complete the following information):**
 - Operating System: Win 10
 - Great Expectations Version: 0.18.0
 - Data Source: N/A?
 - Cloud environment: N/A?

**Comment by bryanlusse** [comment]
I run into the exact same issue.
Will this be picked up at some point?

Environment (please complete the following information):

Operating System: MacOS 14.1
Great Expectations Version: 0.18.10
Data Source: N/A?
Cloud environment: N/A?

**Comment by jjgong7** [comment]
Having the same issue: 

**Environment (please complete the following information):**

Operating System: MacOS 14.4.1
Great Expectations Version: 0.18.13
Data Source: N/A?
Cloud environment: N/A?

```python
2024-05-01T17:23:22 - DEBUG - Constructing RuntimeDataConnector "runtime_data_connector".
2024-05-01T17:23:22 - DEBUG - UsageStatsException:  type: <class 'AssertionError'>
2024-05-01T17:23:22 - ERROR - (generate_expectation_tests) PROBLEM with get_test_validator_with_data in backend pandas for expect_column_aggregate_to_match_some_criteria from data (no data_alt to try) ValueError('Provided mode ephemeral returned context of type FileDataContext instead of EphemeralDataContext; please check your input arguments.')
2024-05-01T17:23:22 - DEBUG - (_get_test_results) validator_with_data failure for pandas--expect_column_aggregate_to_match_some_criteria
0 2 1 False
2024-05-01T17:23:22 - DEBUG - (run_diagnostics) coverage_score: 0.5 for expect_column_aggregate_to_match_some_criteria
=== all (pandas) ===

================================================================================

Completeness checklist for ExpectColumnAggregateToMatchSomeCriteria (Maturity.EXPERIMENTAL):
   Has a valid library_metadata object
      No library_metadata attribute found
   Has a docstring, including a one-line short description that begins with "Expect" and ends with a period
      "Expect the maximum value in the column to be less than or equal to 5"
   Has at least one positive and negative example case, and all test cases pass
   Has core logic and passes tests on at least one Execution Engine
 ✔ Has basic input validation and type checking
    ✔ Custom 'assert' statements in validate_configuration
 ✔ Has both statement Renderers: prescriptive and diagnostic
   Has core logic that passes tests for all applicable Execution Engines and SQL dialects
      Only 0 / 1 tests for pandas are passing
        - Failing: all
   Has a full suite of tests, as determined by a code owner
   Has passed a manual review by a code owner for code standards and style guides
```

**Comment by bryanlusse** [comment]
I was able to (semi nicely) fix this by doing:

```python
from great_expectations.data_context import EphemeralDataContext
from great_expectations.data_context.types.base import DataContextConfig, InMemoryStoreBackendDefaults

....
{custom expectation logic}
....

if __name__ == "__main__":
    project_config = DataContextConfig(store_backend_defaults=InMemoryStoreBackendDefaults())
    context = EphemeralDataContext(project_config=project_config)  # type: ignore[attr-defined]
    debug_logger = logging.getLogger("test")
    diagnostics = YourCustomExpectationName().run_diagnostics(
        debug_logger=debug_logger, only_consider_these_backends=["spark"], context=context
    )
    for test in diagnostics.tests:
        if test.test_passed is False:
            print(f"=== {test.test_title} ({test.backend}) ===\n")
            print(f"{80 * '='}\n")

    checklist: str = diagnostics.generate_checklist()
    print(checklist)
```

What this effectively does is:
- Explicitly create a fresh data context
- Go 1 layer into the `print_diagnostic_checklist` function in order to give the context to the tests

Note that `YourCustomExpectationName` should be changed by the name of your custom expectation.

**Comment by jjgong7** [comment]
@bryanlusse thanks for the suggestion! That works
