### ISSUE TITLE
Query Asset not able to run rules

### ISSUE THREAD

**Issue by akshay-kokate-06** [great-expectations/great_expectations#8916]
When using `add_query_asset` the RuleBasedProfiler is not able to generate expectations for numeric fields. But when using `add_table_asset` it is able to generate the expectations suite as expected.
We are using Ephemeral Data Context.

Working file with Table Asset
```
project_config = DataContextConfig(
        store_backend_defaults=InMemoryStoreBackendDefaults()
    )
context = EphemeralDataContext(project_config=project_config)

context.sources.add_sql(name=source_store_name, connection_string=<connection-string-1>)

source = context.get_datasource(source_store_name)
source.add_table_asset(name=self.get_asset_name(), table_name=self.entity, schema_name=schema_name)

print(self.profiler_config)
profiler = RuleBasedProfiler(name=self.profiler_config['name'],
                             config_version=self.profiler_config['config_version'],
                             rules=self.profiler_config['rules'],
                             variables=self.profiler_config['variables'],
                             data_context=self.context
                             )

source_data_asset = context.get_datasource(source_store_name).get_asset(self.get_asset_name())
source_batch_request = source_data_asset.build_batch_request()

profiler_result = profiler.run(
            batch_request=source_batch_request
        )
expectation_suite_profile = profiler_result.get_expectation_suite(
            expectation_suite_name=self.expectation_suite_name)

```

Not Working Fine
```
project_config = DataContextConfig(
        store_backend_defaults=InMemoryStoreBackendDefaults()
    )
context = EphemeralDataContext(project_config=project_config)

context.sources.add_sql(name=source_store_name, connection_string=<connection-string-1>)

source = context.get_datasource(source_store_name)
source.add_query_asset(name='some-asset', table_name='table', schema_name='schema')

profiler = RuleBasedProfiler(name=self.profiler_config['name'],
                             config_version=self.profiler_config['config_version'],
                             rules=self.profiler_config['rules'],
                             variables=self.profiler_config['variables'],
                             data_context=self.context
                             )

source_data_asset = context.get_datasource(source_store_name).get_asset(self.get_asset_name())
source_batch_request = source_data_asset.build_batch_request()

profiler_result = profiler.run(
            batch_request=source_batch_request
        )
expectation_suite_profile = profiler_result.get_expectation_suite(
            expectation_suite_name=self.expectation_suite_name)

```
```

Is this behaviour expected ?

**Comment by molliemarie** [comment]
Hello @akshay-kokate-06. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
