### ISSUE TITLE
unexpected_index_column_names not present in expect_column_values_to_not_be_null checkpoint result

### ISSUE THREAD

**Issue by cookepm** [great-expectations/great_expectations#8928]
**Describe the bug**
For `expect_column_values_to_not_be_null` (for Spark datasource), when I run a checkpoint with kwargs `result_format='COMPLETE'` and `unexpected_index_column_names=['some col']` I am not getting back any `unexpected_index_column_names` key in the checkpoint/validation results.

**To Reproduce**

```{python}
from great_expectations import get_context


context = get_context()
datasource = context.sources.add_or_update_spark('default')
data_asset = datasource.add_dataframe_asset('test-df')

df = spark.createDataFrame([[1, 'a'], [2, None], [3, 'c']], schema=['ix', 'val'])
batch_request = data_asset.build_batch_request(dataframe=df)
validator = context.get_validator(batch_request=batch_request)

validator.expect_column_values_to_be_between(column="val", min_value=0, max_value=3)
validator.expect_column_values_to_not_be_null(column="val")
validator.save_expectation_suite(discard_failed_expectations=False)

checkpoint = context.add_or_update_checkpoint(
    name='test-checkpoint',
    validator=validator,
)

checkpoint_results = checkpoint.run(
    result_format={
        'result_format': 'COMPLETE',
        'unexpected_index_column_names': ['ix'],
        'return_unexpected_index_query': True,
    },
)
validation_results = list(checkpoint_results['run_results'].values())[0]['validation_result']['results']
print(validation_results[0]['result']['unexpected_index_column_names'])
validation_results[1]['result']['unexpected_index_column_names']
```

The print statement corresponding to the `expect_column_values_to_be_between` expectation above executes okay, returning `['ix']` but I get the following traceback for the final line corresponding to the `expect_column_values_to_not_be_null` expectation:

> KeyError                                  Traceback (most recent call last)
>   Cell In [37], line 30
>        28 validation_results = list(checkpoint_results['run_results'].values())[0]['validation_result']['results']
>        29 print(validation_results[0]['result']['unexpected_index_column_names'])
>   ---> 30 validation_results[1]['result']['unexpected_index_column_names']
> 
> KeyError: 'unexpected_index_column_names'

**Expected behavior**
I expect the last line to return `['ix']` as per the `expect_column_values_to_be_between` expectation.

**Environment (please complete the following information):**
 - Operating System: Ubuntu 18.04
 - Great Expectations Version: 0.17.22
 - Data Source: Spark
 - Cloud environment: [Azure Synapse](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-33-runtime)

**Comment by molliemarie** [comment]
Hello @cookepm86. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
