### ISSUE TITLE
unexpected_index_query references internal function for expect_column_values_to_match_strftime_format expectation

### ISSUE THREAD

**Issue by cookepm** [great-expectations/great_expectations#8929]
**Describe the bug**
`unexpected_index_query ` for the `expect_column_values_to_match_strftime_format ` references an internal GX function [is_parseable_by_format](https://github.com/great-expectations/great_expectations/blob/3ad71a7d12956f9fbcb0668c4eb38b83a5d7ca2d/great_expectations/dataset/sparkdf_dataset.py#L1053).

**To Reproduce**
```{python}
from great_expectations import get_context


context = get_context()
datasource = context.sources.add_or_update_spark('default')
data_asset = datasource.add_dataframe_asset('test-df')

df = spark.createDataFrame([['2023-01-01'], ['2023-01-02'], ['20230101']], schema=['val'])
batch_request = data_asset.build_batch_request(dataframe=df)
validator = context.get_validator(batch_request=batch_request)

validator.expect_column_values_to_match_strftime_format(column="val", strftime_format='%Y-%m-%d')
validator.save_expectation_suite(discard_failed_expectations=False)

checkpoint = context.add_or_update_checkpoint(
    name='test-checkpoint',
    validator=validator,
)

checkpoint_results = checkpoint.run(
    result_format={
        'result_format': 'COMPLETE',
        'return_unexpected_index_query': True,
    },
)
validation_results = list(checkpoint_results['run_results'].values())[0]['validation_result']['results']
query = validation_results[0]['result']['unexpected_index_query']
query
```
returns `'df.filter(F.expr((val IS NOT NULL) AND (NOT is_parseable_by_format(val))))'`. This seems to reference [this function](https://github.com/great-expectations/great_expectations/blob/3ad71a7d12956f9fbcb0668c4eb38b83a5d7ca2d/great_expectations/dataset/sparkdf_dataset.py#L1053) and [even assuming any syntax issues are resolved](https://github.com/great-expectations/great_expectations/issues/8407) will not be executable by the user as a result.

**Expected behavior**
A valid ([up to the known syntax issues](https://github.com/great-expectations/great_expectations/issues/8407)) PySpark expression which a user can evaluate to return the failing rows.

**Environment (please complete the following information):**
 - Operating System:  Ubuntu 18.04
 - Great Expectations Version: 0.17.22
 - Data Source: Spark
 - Cloud environment: [Azure Synapse](https://learn.microsoft.com/en-us/azure/synapse-analytics/spark/apache-spark-33-runtime)

**Comment by molliemarie** [comment]
Hello @cookepm86. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
