### ISSUE TITLE
Unable to get the list of expectations from Expectation Gallery. Gallery is blank. 

### ISSUE THREAD

**Issue by nikitammahale** [great-expectations/great_expectations#8933]
**Describe the bug**
Unable to get the list of expectations from Expectation Gallery. Gallery is blank. 

**To Reproduce**
Navigate from browser to https://greatexpectations.io/expectations/
Also tried navigating from Great expecations (https://docs.greatexpectations.io/docs/) -> Resources tab -> Expecatation Gallery

**Expected behavior**
User should be able to see a complete list of expectations in the gallery.

**Environment 
 - Operating System: Windows
 - Great Expectations Version: 0.18.1
 - Data Source: [e.g. Pandas, Snowflake] - NA
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP] - NA

**Additional context**

Screenshot of page - 

<img width="916" alt="Screenshot 2023-11-06 182925" src="https://github.com/great-expectations/great_expectations/assets/150032944/49003f20-bac5-45a6-be2c-2e4ca85c6959">

**Comment by molliemarie** [comment]
Hello @nikitammahale. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
