### ISSUE TITLE
[GX Cloud] Broken URL for validation results in Slack notification

### ISSUE THREAD

**Issue by babjiloganda** [great-expectations/great_expectations#8943]
**Describe the bug**
Getting 404 error on the Validation results URL shared in slack notification.

**To Reproduce**
Setup slack web hook notification for validation runs in GX Cloud. {Screenshots attached
[GX_Slack_URL.zip](https://github.com/great-expectations/great_expectations/files/13291307/GX_Slack_URL.zip)
}

**Expected behavior**
The Validation result should contain a valid URL to the Data asset/run.

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: 0.17.x
 - Data Source: Spark
 - Cloud environment: Databricks

**Comment by molliemarie** [comment]
Hello @babjiloganda. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
