### ISSUE TITLE
Multiple requests to Azure Keyvault while getting the local file context using get_context()

### ISSUE THREAD

**Issue by sudiv** [great-expectations/great_expectations#8947]
**Describe the bug**
When getting local file context with get_context() method, in which the local context's  config_variables.yml is reading secrets from Azure Key Vault using the following signature  (Azure client credentials are stored in environment variables)

secret|https://yourvaultname.vault.azure.net/secrets/yoursecret
(or)
secret|https://yourvaultname.vault.azure.net/secrets/yourjsonsecret|yourjsonkey

getting context is stuck for couple of minutes, on checking the code in debug mode reveals that there are multiple requests (More than 60) to AZ Key Vault.

**To Reproduce**
1) Create a new local file context
2) Setup a secret in Azure key vault , and register an app/get client id and secret of an app which has access to read the secret from the key vault. 
3) Include following line in uncommited/config_variables.yml 
secret|https://YourVaultName.vault.azure.net/secrets/yoursecretname
4) Run the following code

import great_expectations as gx
import logging,os

logging.basicConfig(filename='apptest_simple.log', level=logging.DEBUG,
                    format='%(asctime)s [%(levelname)s] - %(message)s')
                    
path_to_context_root_folder="path to your context"

os.environ["AZURE_CLIENT_ID"] = "your client id"
os.environ["AZURE_CLIENT_SECRET"] = "your secret"
os.environ["AZURE_TENANT_ID"] = "your tenant id"

print("Trying to get the GX context at %s"%path_to_context_root_folder)
context = gx.get_context(context_root_dir=path_to_context_root_folder)
print("Acquired GX context at %s"%path_to_context_root_folder) 

**Expected behavior**
The context should be acquired with in seconds and key vault should have been accessed only once to get the secret

**Environment (please complete the following information):**
 - Operating System: Tested in Windows 10 and AKS Kube Pod
 - Great Expectations Version: Tested in 0.17.22 and 0.18.1
 - Data Source: [e.g. Pandas, Snowflake]: NA , Tested with azure-identity 1.14.0 and 1.15.0
 - Cloud environment: NA

**Additional context**
In the log could be able to see on the first call itself the azure-identity could be able to get the secret provided all the access is correct. Still there are multiple calls happening to key vault blocking the execution of get_context.

**Comment by molliemarie** [comment]
Hello @sudiv. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
