### ISSUE TITLE
Ruamel yaml load errors in multithreading

### ISSUE THREAD

**Issue by Kirill-Ulich** [great-expectations/great_expectations#8957]
**Describe the bug**
Description of my problem [here](https://github.com/PrefectHQ/prefect/issues/8142)

**To Reproduce**
The code and stack trace of error can be seen at the link above.

**Expected behavior**
I expect that reading data from GX yml config files will work without errors.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.15.41, 0.18.1
 - Data Source: Pandas, SqlAlchemy
 - Cloud environment: Prefect

**Additional context**
I think that the problem is the inability of ruamel to read one file with multithreading.

**Comment by jhanm12** [comment]
Facing a similar issue.

**Comment by molliemarie** [comment]
Hello @Kirill-Ulich. With the upcoming launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
