### ISSUE TITLE
expect_column_values_to_be_in_set thowing NoneType is not iterable

### ISSUE THREAD

**Issue by microcassidy** [great-expectations/great_expectations#8960]
**Describe the bug**

I am running into this error several times over for mssql sources. The expectation was generated by the onboarding assistant. Other expectations that indicate a non-empty set are passing (see screenshot).

`expect_column_values_to_be_in_set raised an exception:
'NoneType' object is not iterable`

![image](https://github.com/great-expectations/great_expectations/assets/7576025/baccc983-10ee-4ef6-81f9-783cc3160087)

**To Reproduce**
Please include your great_expectations.yml config, the code you’re executing that causes the issue, and the full stack trace of any error(s).

```python 
expectation_configuration = ExpectationConfiguration(**{
  "expectation_type": "expect_column_values_to_be_in_set",
  "kwargs": {
    "column": "redacted",
    "mostly": 1.0,
    "value_set": [
      "2",
      "3",
      "1"
    ]
  },
  "meta": {
    "profiler_details": {
      "metric_configuration": {
        "domain_kwargs": {
          "column": "redacted"
        },
        "metric_name": "column.distinct_values",
        "metric_value_kwargs": None
      },
      "num_batches": 1,
      "parse_strings_as_datetimes": False
    }
  }
})
suite.add_expectation(expectation_configuration=expectation_configuration)
```

```stderr
expect_column_values_to_be_in_set raised an exception:
'NoneType' object is not iterable
Show exception traceback...

Traceback (most recent call last):
File "/home/cass/repos/great_expectations/venv/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 548, in _process_direct_and_bundled_metric_computation_configurations
] = metric_computation_configuration.metric_fn( # type: ignore[misc] # F not callable
File "/home/cass/repos/great_expectations/venv/lib/python3.10/site-packages/great_expectations/expectations/metrics/map_metric_provider/map_condition_auxilliary_methods.py", line 501, in _sqlalchemy_map_condition_query
query_as_string: str = sql_statement_with_post_compile_to_string(
File "/home/cass/repos/great_expectations/venv/lib/python3.10/site-packages/great_expectations/expectations/metrics/util.py", line 1216, in sql_statement_with_post_compile_to_string
params = (repr(compiled.params[name]) for name in compiled.positiontup)
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/home/cass/repos/great_expectations/venv/lib/python3.10/site-packages/great_expectations/validator/validation_graph.py", line 285, in _resolve
self._execution_engine.resolve_metrics(
File "/home/cass/repos/great_expectations/venv/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 283, in resolve_metrics
return self._process_direct_and_bundled_metric_computation_configurations(
File "/home/cass/repos/great_expectations/venv/lib/python3.10/site-packages/great_expectations/execution_engine/execution_engine.py", line 552, in _process_direct_and_bundled_metric_computation_configurations
raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: 'NoneType' object is not iterable
```

**Expected behavior**

The expectation should pass or fail without throwing an execution error.

**Environment (please complete the following information):**
 - Windows WSL
 - Great Expectations Version: 0.17.23
 - Data Source: MSSQL
 - Cloud environment: N/A

**Comment by IgorShcherbakov** [comment]
Good afternoon!
I have the same problem. Did you manage to fix it?

**Comment by molliemarie** [comment]
Hello @microcassidy. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗

**Comment by microcassidy** [comment]
It was the most recent version when I opened the issue...Suggesting that I reopen the issue is a bit ridiculous 9months later. If it's still an issue feel free to open it yourself.
