### ISSUE TITLE
Wrong initialization of context if files are on GIT

### ISSUE THREAD

**Issue by kbraniewski** [great-expectations/great_expectations#8994]
**Describe the bug**
In our project we use several great expectations configurations, the configuration files are located in directories with different names. The directories are located in the GIT repository.
Example:
- gx_configs
	- config_1
		- checkpoints
		- expectations		
		...
		- great_expectations.yml
	- config_2
		- checkpoints
		- expectations		
		...
		- great_expectations.yml

In each directory there is an 'uncommitted' folder and a .gitignore file that contains the 'uncommitted' directory. 
Downloading the configuration from GIT by another person downloads the configuration without the 'uncommitted' directory.
When you try to initialize a context with a path pointer to the configuration, a configuration template is created in new "gx" directory and the configuration from the correct directory, e.g. config_1, is loaded into the file context.
The created uncommitted directory and its subdirectories should be created in the directory where the great_expectations.yml file is located and not in a new directory named "gx".

**To Reproduce**
1 Context initialization:
> gx = great_expectations.get_context(context_root_dir="gx_example/config_1")

2. rename the directory gx_example/gx to gx_example/config_1

3 Re-initialize the context:
> gx = great_expectations.get_context(context_root_dir="gx_example/config_1")

**Expected behavior**
In the _scaffold method (great_expectations/data_context/data_context/serializable_data_context.py), instead of a constant value from GX_DIR, the name of the directory where the great_expectations.yml file is located should be retrieved.

**Environment (please complete the following information):**
 - Operating System: Windows, Python 3.10.4
 - Great Expectations Version: 0.18.3
 - Data Source: N/A
 - Cloud environment: N/A

**Comment by molliemarie** [comment]
Hello @kbraniewski. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
