### ISSUE TITLE
Date to be between 2 date ranges

### ISSUE THREAD

**Issue by pmohancos** [great-expectations/great_expectations#8996]
### Discussed in https://github.com/great-expectations/great_expectations/discussions/4276

<div type='discussions-op-text'>

<sup>Originally posted by **kyleaton** February 25, 2022</sup>
Hello! 

It will be great to have an expectation that checks a date column to be between  2 date ranges.

</div>

**Comment by Chr96er** [comment]
This should be possible using the `expect_column_values_to_be_between` expectation: https://greatexpectations.io/expectations/expect_column_values_to_be_between

You might have to set `parse_strings_as_datetimes=True`.

**Comment by nicholaskebut1** [comment]
> This should be possible using the `expect_column_values_to_be_between` expectation: https://greatexpectations.io/expectations/expect_column_values_to_be_between
> 
> You might have to set `parse_strings_as_datetimes=True`.

I places parse_string_as_datetimes = True and it errors out. Is parse strings as date time deprecated or is it currently supported?

**Comment by pmohancos** [comment]
Same here, it is giving me an error message - could not convert string to float.

**Comment by nicholaskebut1** [comment]
> Same here, it is giving me an error message - could not convert string to float.

Which version of great expectations are you using?

**Comment by pmohancos** [comment]
Sorry, for the late reply. I am using the version 0.18.3. I have written a custom expectation for this and is fulfilling my need now.

**Comment by Kladderadatasch** [comment]
Would you mind sharing your custom expectation with which you solved that @pmohancos ?
