### ISSUE TITLE
Validation results

### ISSUE THREAD

**Issue by eli-vlahos** [great-expectations/great_expectations#9001]
Hello,
Some of the validation results for some great expectation tests appear to be not working correctly. I pass in a csv file as a data source and try to validate it against another csv file. The expectations are set up so that all differences between the csv files will be flagged, specifically number and name of columns and expected values within columns. However as seen below sometimes the value in the csv file can be correct, but it will flag it as having failed. How do I fix that?

![image](https://github.com/great-expectations/great_expectations/assets/64896247/7ca076e1-851a-448e-9404-0774889f2469)

**Comment by molliemarie** [comment]
Hello @eli-vlahos. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
