### ISSUE TITLE
[BUG] GX version >= 0.17.6 having issues with expect_column_sum_to_be_between

### ISSUE THREAD

**Issue by data-han** [great-expectations/great_expectations#9082]
**Describe the bug**
I ran through the versions and found that after 0.17.6 (up till the latest 0.18.3), when using the expectations, the following error is shown:

<img width="1038" alt="image" src="https://github.com/great-expectations/great_expectations/assets/51312880/338787d3-93ec-442c-aa79-db6a0836220a">

 metric_name: metrics[metric_configuration.id]
KeyError: ('column.sum', '0a0c9fb06c26695917c1db81140aad77', ())

However, before 0.17.5 it is working fine

**To Reproduce**
Please include your great_expectations.yml config, the code you’re executing that causes the issue, and the full stack trace of any error(s).

My checks:
<img width="608" alt="image" src="https://github.com/great-expectations/great_expectations/assets/51312880/e1a5dafa-e03b-4db4-875f-2428d50c6a10">

**Expected behavior**
The checkpoint should have ran

**Environment (please complete the following information):**
 - Operating System: MacOS
 - Great Expectations Version: >= 0.17.6
 - Data Source: Spark
 - Cloud environment: AWS

**Additional context**

**Comment by rachhouse** [comment]
Hi @data-han, thanks for reporting this issue - I'm trying to reproduce the behavior but have been unable to replicate your error. Could you please include the full code that reproduces this error in your environment?

**Comment by data-han** [comment]
Hi @rachhouse , thanks for checking on this.  I have 2 scripts, one is running the main validation, while the others provide some re-usability.

main validation:
```
# Primary Entry point for GX deployment
            context = gx.get_context()

            # Extraction of variables
            table, exp_suite_name, chk_name = self.cm._get_variables(self.schema, self.target_table)

            # Create DF and Expectations
            df_main = self.create_dataframe(table)

            validator, batch_request = self.cm._create_gx_components(context, self.target_table, df_main, exp_suite_name)

            batch_request = self.create_expectations(df_main, validator, batch_request, exp_suite_name)

            # Create Checkpoint
            self.cm._create_checkpoint(context, self.slack_noti, chk_name, exp_suite_name)
            checkpoint_result = self.cm._run_checkpoint(context, batch_request, chk_name, self.project, self.target_table, exp_suite_name)

 def create_expectations(self, df_main, validator, batch_request, exp_suite_name):
        """
 
        """
        self._logger.info(f"Creating Expectations {exp_suite_name}")
          
        # Check if the count across env is roughly the same
        val_count_test = float(df_main.select(F.sum('count_test')).collect()[0][0])
        val_count_prod = float(df_main.select(F.sum('count_prod')).collect()[0][0])

        validator.expect_column_sum_to_be_between(
            column= 'count_dev',
            min_value= 0.9 * val_count_test , strict_min = True,
            max_value = 1.1 * val_count_test , strict_max = True,
            result_format="COMPLETE", include_unexpected_rows=True,
            meta={'notes': 'xxx'}
        )


        validator.save_expectation_suite(discard_failed_expectations=False)

        return batch_request

```

Common script

```
def _get_variables(self, schema, target_table):

        table = schema + '.' + target_table
        exp_suite_name = f'SUITE_{target_table}'
        chk_name = f'CP_{target_table}'
        # chk_path = os.path.join(os.path.dirname(__file__), f'../checkpoints/{chk_name}.yml')

        return table, exp_suite_name, chk_name


    def _create_gx_components(self, context, target_table, df_combined, exp_suite_name):
       
        self._logger.info("Setting up GX components")
        ##############################
        # GX Set-up
        ##############################
        # 1) Set-up GX using Fluent datasource - Spark data source
        spark_datasource = context.sources.add_or_update_spark(name=f"{target_table}")
        # 2) Add Data Asset (records) to Data Source (using df created above)
        spark_asset = spark_datasource.add_dataframe_asset(name=f"{target_table}", dataframe = df_combined)
        # 3) Add Batch Request (retrieving data from asset)
        batch_request = spark_asset.build_batch_request()

        # 4) Set-up Expectations suite (collection of verifiable assertions about data)
        context.add_or_update_expectation_suite(
            expectation_suite_name = exp_suite_name
        )

        # 5) Create Validator (run Expectation suite against data)
        validator = context.get_validator(
            batch_request = batch_request,
            expectation_suite_name = exp_suite_name
        )

        return validator, batch_request

    def _create_checkpoint(self, context, slack_noti, chk_name, exp_suite_name):
    
        self._logger.info(f"Overwriting Checkpoint {chk_name}")

        action_store = {
            "name": "store_validation_result",
            "action": {"class_name": "StoreValidationResultAction"},
        }
        action_params = {
            "name": "store_evaluation_params",
            "action": {"class_name": "StoreEvaluationParametersAction"},
        }
        action_update = {
            "name": "update_data_docs",
            "action": {"class_name": "UpdateDataDocsAction"},
        }
        action_slack = {
            "name": "send_on_result",
            "action": {
                "class_name": "SlackNotificationAction",
                "slack_webhook": f"${self.validation_notification_slack_webhook}",
                "notify_on": "failure",
                "notify_with": ["s3_site"],
                "renderer": {
                    "module_name": "great_expectations.render.renderer.slack_renderer",
                    "class_name": "SlackRenderer",
                },
            },
        }

        runtime_configuration = {
            "result_format": {
                "result_format": "COMPLETE",
                "unexpected_index_column_names": ["ID"]
            }
        }

        if slack_noti == 'Y':
            self._logger.info("Adding slack notification")
            action_list = [action_store, action_params, action_update, action_slack]
        else:
            action_list = [action_store, action_params, action_update]

        context.add_or_update_checkpoint(
            name = f"{chk_name}",
            expectation_suite_name = f"{exp_suite_name}",
            config_version = 1,
            class_name = "Checkpoint",
            action_list = action_list,
            runtime_configuration = runtime_configuration
        )

```

**Comment by data-han** [comment]
Error code:

Traceback (most recent call last):
  File "/src/great_expectations/code/gx_checks/io/gx_test.py", line 230, in <module>
    gxtests.main()
  File "/src/great_expectations/code/gx_checks/io/gx_test.py", line 67, in main
    batch_request = self.create_expectations(df_main, validator, batch_request, exp_suite_name)
  File "

/src/great_expectations/code/gx_checks/io/gx_test.py", line 213, in create_expectations
    validator.expect_column_sum_to_be_between(
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/validator/validator.py", line 591, in inst_expectation
    raise err
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/validator/validator.py", line 554, in inst_expectation
    validation_result = expectation.validate(
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/expectations/expectation.py", line 1287, in validate
    ] = validator.graph_validate(
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/validator/validator.py", line 1090, in graph_validate
    raise err
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/validator/validator.py", line 1074, in graph_validate
    result = configuration.metrics_validate(
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/core/expectation_configuration.py", line 1494, in metrics_validate
    return expectation_impl(self).metrics_validate(
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/expectations/expectation.py", line 1061, in metrics_validate
    _validate_dependencies_against_available_metrics(
  File "opt/anaconda3/lib/python3.9/site-packages/great_expectations/expectations/expectation.py", line 3739, in _validate_dependencies_against_available_metrics
    raise InvalidExpectationConfigurationError(
great_expectations.exceptions.exceptions.InvalidExpectationConfigurationError: Metric ('column.sum', '0a0c9fb06c26695917c1db81140aad77', ()) is not available for validation of {
  "kwargs": {
    "column": "count_dev",
    "min_value": xxx,
    "strict_min": true,
    "max_value": xxx,
    "strict_max": true,
    "result_format": "COMPLETE",
    "include_unexpected_rows": true,
    "batch_id": "xx"
  },
  "expectation_type": "expect_column_sum_to_be_between",
  "meta": {
    "notes": "xxx"
  }
}. Please check your configuration.

**Comment by rachhouse** [comment]
@data-han Thanks! Also, what specific conda version and python version are you running?

**Comment by data-han** [comment]
@rachhouse  I tried both Python **3.9.12** and **3.11.4** with conda **22.9.0**. Both don't work

**Comment by rachhouse** [comment]
Hey @data-han, thanks for the environment versions. I'm still unable to reproduce this error - it's working as expected for me across GX and conda versions. Here's a few more questions:
* What is the spark data type of the column `count_dev` that you're trying to validate?
* You listed the associated cloud environment as AWS, where is the source data for the dataframe coming from?

**Comment by rachhouse** [comment]
Hi @data-han, just to keep you in the loop, I'll be out of office for the next few weeks. I've passed this issue along to Engineering, depending on their bandwidth (things are slow this time of year due to the US winter holidays) you may get some follow up questions in the meantime to help with investigation & reproduction.

**Comment by data-han** [comment]
@rachhouse  thanks. I have also tried virtual environment. It's the same for me. Count is nothing but a count(*) in sql

<img width="123" alt="image" src="https://github.com/great-expectations/great_expectations/assets/51312880/e4a1ecdf-241c-402d-b972-73dccdc6af3e">

my base requirements

boto3==1.26.10
botocore==1.29.10
certifi==2022.12.7
cffi==1.15.0
cryptography==38.0.0
idna==3.3
jmespath==0.10.0
numpy==1.24.2
pandas==1.5.3
pillow==9.3.0
pyarrow==10.0.1
py4j==0.10.9.5
pycparser==2.20
pyspark==3.2.2
pytz==2021.3
requests==2.26.0
setuptools==65.5.1
six==1.16.0
snowflake-connector-python==3.0.1
urllib3==1.26.7
zipp==3.7.0

**Comment by rachhouse** [comment]
Hi @data-han, I see there was no movement on this issue over the holidays. I dug into it again today and I still cannot reproduce your error - `expect_column_sum_to_be_between` behaves as expected across all environments, package versions, and spark dataframes I have tried.

If you'd like to continue to troubleshoot this issue, I think what would be most helpful would be for you to containerize and share your current setup, to the extent possible, so that we can run it on our side and replicate the error. A repo that contains your GX workflow code, representative sample data, and containerized environment (Dockerfile is best) and that enables us to reproduce the error when run will give us a next step to investigate. Thanks!

**Comment by data-han** [comment]
Hi just want to update, i managed to resolve this issue. This is because the column name is not capitalized. Once i've done that, it works.
