### ISSUE TITLE
Runtime Data Connector for GCS data requires AWS S3 components

### ISSUE THREAD

**Issue by mlyonlebo** [great-expectations/great_expectations#9199]
**Describe the bug**

When trying to validate GCS data, I got a `ModuleNotFoundError: AWS S3 connection components are not installed, please 'pip install boto3 botocore'` 

I think this is because the runtime data connector may erroneously infer that the data is on S3 if "s3" occurs in the path value. 

**To Reproduce**

Use a runtime data connector with a GCS path that happens to have `s3` in it: (for example: `gs://this/cool/path/to/file_s3.csv`)

`RuntimeDataConnector.build_batch_spec` seems to return an `S3BatchSpec` if the path in the runtime parameters contains `s3`. It might be safer to check that the path starts with `s3://`.

**Expected behavior**

I expected that the connector for GCS data would not require AWS S3 Connection components.

**Environment (please complete the following information):**
 - Operating System: MacOs
 - Great Expectations Version: 0.18.5
 - Data Source: Pandas
 - Cloud environment: GCP

**Additional context**

**Comment by mlyonlebo** [comment]
Hi, is there any more information I could provide? Unfortunately this issue has recurred.

**Comment by molliemarie** [comment]
Hello @mlyonlebo. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
