### ISSUE TITLE
relax ruamel.yaml pin

### ISSUE THREAD

**Issue by Redoubts** [great-expectations/great_expectations#9210]
Can the version pin for `ruamel.yaml` be relaxed? The issue linked in the requirements file is closed.

**Comment by Kilo59** [comment]
@ Redoubts I suggest just opening a PR with the desired change and explaining why you want to see the change.

**Comment by Kilo59** [comment]
@Redoubts I suggest just opening a PR with the desired change and explaining why you want to see the change.
