### ISSUE TITLE
'NoneType' object is not iterable

### ISSUE THREAD

**Issue by IgorShcherbakov** [great-expectations/great_expectations#9233]
I am running into this error several times over for mssql sources.
**expect_column_values_to_not_be_null raised an exception: 'NoneType' object is not iterable**
![изображение](https://github.com/great-expectations/great_expectations/assets/35165017/fdda28d3-40cd-4be9-b06e-d8aeeb5a1104)
values must never be null.

expect_column_values_to_not_be_null raised an exception:
'NoneType' object is not iterable

Show exception traceback...
Traceback (most recent call last):
File "E:\Projects\GreatExpectations\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 548, in _process_direct_and_bundled_metric_computation_configurations
] = metric_computation_configuration.metric_fn( # type: ignore[misc] # F not callable
File "E:\Projects\GreatExpectations\venv\lib\site-packages\great_expectations\expectations\metrics\metric_provider.py", line 60, in inner_func
return metric_fn(*args, **kwargs)
File "E:\Projects\GreatExpectations\venv\lib\site-packages\great_expectations\expectations\metrics\table_metrics\table_columns.py", line 43, in _sqlalchemy
return [col["name"] for col in column_metadata]
TypeError: 'NoneType' object is not iterable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "E:\Projects\GreatExpectations\venv\lib\site-packages\great_expectations\validator\validation_graph.py", line 285, in _resolve
self._execution_engine.resolve_metrics(
File "E:\Projects\GreatExpectations\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 283, in resolve_metrics
return self._process_direct_and_bundled_metric_computation_configurations(
File "E:\Projects\GreatExpectations\venv\lib\site-packages\great_expectations\execution_engine\execution_engine.py", line 552, in _process_direct_and_bundled_metric_computation_configurations
raise gx_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: 'NoneType' object is not iterable

Great Expectations Version: 0.18.7
Data Source: MSSQL

**Comment by IgorShcherbakov** [comment]
The problem was solved by enabling the parameter - create_temp_table=True
Was this intended or is it a bug?

**Comment by Kilo59** [comment]
@IgorShcherbakov this sounds like a bug.
Sorry about that. In a previous release we changed the default parameter of `create_temp_table` from `True` to `False` and didn't catch this issue.

**Comment by IgorShcherbakov** [comment]
@Kilo59 
updated to version 0.18.12, set create_temp_table: false, result:
![изображение](https://github.com/great-expectations/great_expectations/assets/35165017/b776e0f6-5b2d-4f3b-a687-f7542a855d45)

**Comment by molliemarie** [comment]
Hello @IgorShcherbakov. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
