### ISSUE TITLE
Great Expectations and Airflow 2.6.3 Conflict - Click package

### ISSUE THREAD

**Issue by itaise** [great-expectations/great_expectations#9245]
Hi,
We've encountered an issue while attempting to upgrade Apache Airflow from version 2.6.2 to version 2.6.3.

There is a mismatch in the allowed versions of the "click" package between Great Expectations >= 0.17.17 and Airflow 2.6.3.

Airflow 2.6.3 requires click 8.1.4: 
https://raw.githubusercontent.com/apache/airflow/constraints-2.6.3/constraints-3.10.txt

While GE version 0.17.17 and onwards disallow it.
I saw that the cause of it is some MyPy typing bug in click 8.1.4.

We need a quick upgrade of Airflow due to a major bug in Airflow 2.6.2,
And we cannot currently upgrade to later version of Airflow (like 2.7.0). 
So would like to know what can be done regarding it? 
thanks a lot!

**Comment by Kilo59** [comment]
I would suggest trying to get Airflow to change their constraints file
https://click.palletsprojects.com/en/8.1.x/changes/#version-8-1-5

**Comment by Kilo59** [comment]
@itaise, this looks like it was fixed in release `0.18.9`

https://github.com/great-expectations/great_expectations/releases/tag/0.18.9
