### ISSUE TITLE
No provider found for method using SqlAlchemyExecutionEngine for json-related expectations

### ISSUE THREAD

**Issue by leeroyaus** [great-expectations/great_expectations#9291]
**Describe the bug**
Using json-related expectations `expect_column_values_to_match_json_schema` and `expect_column_values_to_be_json_parseable`

**To Reproduce**

Code to reproduce (raw_data col contains json data as text):
````
{
      "expectation_type": "expect_column_values_to_be_json_parseable",
      "kwargs": {
        "column": "raw_data"
      },
      "meta": {
        "notes": {
          "content": "Check that column is json parseable",
          "format": "markdown"
        }
      }
    }
````

Full stack traceback below:
````
No provider found for column_values.json_parseable.unexpected_count using SqlAlchemyExecutionEngine
Show exception traceback...

Traceback (most recent call last):
File "/workspace/pisa2025-api-etl/.venv/lib/python3.10/site-packages/great_expectations/expectations/registry.py", line 304, in get_metric_provider
return metric_definition["providers"][type(execution_engine).__name__]
KeyError: 'SqlAlchemyExecutionEngine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/workspace/pisa2025-api-etl/.venv/lib/python3.10/site-packages/great_expectations/validator/validator.py", line 1143, in _generate_metric_dependency_subgraphs_for_each_expectation_configuration
graph=self._metrics_calculator.build_metric_dependency_graph(
File "/workspace/pisa2025-api-etl/.venv/lib/python3.10/site-packages/great_expectations/validator/metrics_calculator.py", line 208, in build_metric_dependency_graph
graph.build_metric_dependency_graph(
File "/workspace/pisa2025-api-etl/.venv/lib/python3.10/site-packages/great_expectations/validator/validation_graph.py", line 130, in build_metric_dependency_graph
) = self.set_metric_configuration_default_kwargs_if_absent(
File "/workspace/pisa2025-api-etl/.venv/lib/python3.10/site-packages/great_expectations/validator/validation_graph.py", line 174, in set_metric_configuration_default_kwargs_if_absent
metric_impl_klass, metric_provider = get_metric_provider(
File "/workspace/pisa2025-api-etl/.venv/lib/python3.10/site-packages/great_expectations/expectations/registry.py", line 306, in get_metric_provider
raise gx_exceptions.MetricProviderError(
great_expectations.exceptions.exceptions.MetricProviderError: No provider found for column_values.json_parseable.unexpected_count using SqlAlchemyExecutionEngine
````

**Expected behavior**
Expectations to run without error

**Environment (please complete the following information):**
 - Operating System: Linux via Docker Desktop for Windows
 - Great Expectations Version: 0.18.3
 - Data Source: PostgreSQL tables
 - Cloud environment: N/A (PostgreSQL db hosted on docker network)

**Additional context**
Seems to be an issue parsing any JSON data, so not sure if it's related to my set up (but please let me know if you need more information)

**Comment by Kilo59** [comment]
@leeroyaus is `sqlalchemy` installed?
By default, we don't require it when `great_expectations` is installed.

**Comment by molliemarie** [comment]
Hello @leeroyaus. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
