### ISSUE TITLE
AWS RDS Data source Secrets - Assume role support

### ISSUE THREAD

**Issue by TejjeT** [great-expectations/great_expectations#9387]
**Is your feature request related to a problem? Please describe.**
At present the Open source GX allows users to read secrets from aws secrets. However this wont allow us to assume the role and read the secrets. We have use cases where we would need to assume role both for postgres and Athena and we are unable to acheive this just with config.

**Describe the solution you'd like**
I should be able to assume role for specific data source , allowing me to be able to the retrieve the passwords from cross account.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by molliemarie** [comment]
Hello @TejjeT. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
