### ISSUE TITLE
Expect_compound_columns_to_be_unique does not show SQL query neither in DataDocs nor in JSON

### ISSUE THREAD

**Issue by 0lgaZv** [great-expectations/great_expectations#9389]
**Describe the bug**
The result of expect_compound_columns_to_be_unique does not show the SQL query in DataDocs with result format market as 'Complete'. The sql query could not be found in json with the result of the validation. 

**To Reproduce**
To run the checkpoint and the suite with the same structure. Removing row_condition does not help

Expectation:

` {
      "expectation_type": "expect_compound_columns_to_be_unique",
      "kwargs": {
        "column_list": [
          "a",
          "b",
           "c"
        ],
		"condition_parser": "great_expectations__experimental__",
        "row_condition": "col(\"d\")==\"e\""
      },
     "meta": {"note": "f"}
      }`

Checkpoint:
`runtime_configuration: {
  "result_format": {
            "result_format": "COMPLETE",
            "unexpected_index_column_names": ["a", "b", "c", "d"],
            "return_unexpected_index_query": True,
            "partial_unexpected_count": 100
    }
}
validations:
  - batch_request:
      datasource_name: ***
      data_connector_name: default_runtime_data_connector_name
      data_asset_name: QWER
      runtime_parameters:
       query: "           
            SELECT 
                a,
                b,
                c,
                d
            FROM QWER   
        "
      batch_identifiers:
        default_identifier_name: default_identifier`

**Expected behavior**
SQL query in format in form to be performed on the basis of batch should appear in datadocs and in JSON file. 

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: great_expectations[sqlalchemy] 0.18.6, SQLAlchemy 2.0.0
 - Data Source: MS SQL Server
 - Cloud environment: Azure

**Comment by molliemarie** [comment]
Hello @0lgaZv. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
