### ISSUE TITLE
UserConfigurableProfiler skips date/decimal columns

### ISSUE THREAD

**Issue by mishbahr** [great-expectations/great_expectations#9420]
**Describe the bug**

When passing a Pandas dataframe containing date and decimal columns to the UserConfigurableProfiler, the expected output should include the "expect_column_values_to_be_in_type_list" expectation for every column. However, the expectation is skipped for the "date" and "decimal" columns.

**To Reproduce**

1. Create a Pandas dataframe with date and decimal columns.

```python
data = {
    "user_id": [1],
    "name": ["Clark Kent"],
    "dob": ["1980-05-06"],
    "is_hero": [True],
    "height": [6.1],
    "last_login": [pd.Timestamp("2023-01-01 08:00:00")],
    "balance": [Decimal("150.00")],
}
df = pd.DataFrame(data)
df["dob"] = pd.to_datetime(df["dob"]).dt.date
```
2. Pass the dataframe to the UserConfigurableProfiler.

**Expected behavior**

The UserConfigurableProfiler should include the "expect_column_values_to_be_in_type_list" expectation for every column in the dataframe.

**Environment (please complete the following information):**
 - Operating System: Linux
 - Great Expectations Version: 0.18.8
 - Data Source: Pandas
 - Cloud environment: N/A

**Comment by austiezr** [comment]
Hey @mishbahr; thanks for raising this. The User Configurable Profiler is no longer in active development for the latest versions of GX, and will likely not be prioritized in the near future. Closing this out for now, but feel free to leave further feedback on this issue, which will inform development choices as we continue to develop Great Expectations.
