### ISSUE TITLE
Deprecation: Quickly explore Expectations in a notebook

### ISSUE THREAD

**Issue by Nathan-Kr** [great-expectations/great_expectations#9495]
Hi, I would want to use great expectation in my jupyter notebook.

I found this in legacy documentation: https://github.com/great-expectations/great_expectations/blob/develop/docs_rtd/guides/tutorials/explore_expectations_in_a_notebook.rst

I've tested it and it still work in the latest release (0.18.9). 

Is it planned to deprecate it ? 
Is it not recommended anymore ?

If anyone could clarify on that.
Thank you

**Comment by austiezr** [comment]
Hey @Nathan-Kr! Thanks for reaching out.

While that specific documentation will eventually be deprecated, GX is still very much compatible with Jupyter Notebooks. Take a look at [our Python quickstart](https://docs.greatexpectations.io/docs/oss/tutorials/quickstart/), which should work well within a Jupyter environment.
