### ISSUE TITLE
Docs page in Firefox says "this page crashed: too much recursion"

### ISSUE THREAD

**Issue by zsol** [great-expectations/great_expectations#9528]
When loading the main docs at https://docs.greatexpectations.io/docs/home/ in Firefox 123.0 on Windows, I see the following:

![image](https://github.com/great-expectations/great_expectations/assets/66740/fcce5c95-bfd4-46e0-aaca-45e595780a27)

JS console shows large stacktraces involving `index.ts` and `posthog-core.ts` as well as:
```
[PostHog.js] PostHog library has already been downloaded at least once.
```
Happy to get the entire stack trace if it's helpful (it's minified).

Chrome seems to be working fine.

**Comment by BenniKur** [comment]
can report the same on firefox from a Mac

**Comment by joshzzheng** [comment]
Thanks for raising this @zsol @BenniKur, should be fixed. Feel free to reopen if it's still an issue for you.
