### ISSUE TITLE
How to split the pandas df data into multiple batches  based on a column('date') ?

### ISSUE THREAD

**Issue by jagadeesanmuthuvel** [great-expectations/great_expectations#9556]
**Describe the bug**
I have created a batchrequest from pandas dataframe using below code
 
```python
def get_batch_request(context,data_asset_name,source_name,df):
    data_asset = context.sources.add_or_update_pandas(name=source_name).\
        add_dataframe_asset(name=data_asset_name,dataframe=df)
    return data_asset.build_batch_request(),data_asset
```

How to split the pandas df data into multiple batches  based on a column('date') ?

I could see some of this implementation in GE api v2 documentantion. But i am not sure abt it for v3?
https://legacy.docs.greatexpectations.io/en/latest/autoapi/great_expectations/execution_engine/split_and_sample/pandas_data_splitter/index.html

**To Reproduce**
Please include your great_expectations.yml config, the code you’re executing that causes the issue, and the full stack trace of any error(s).

**Expected behavior**

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]
 - Data Source: [e.g. Pandas, Snowflake]
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]

**Additional context**

**Comment by molliemarie** [comment]
Hello @jagadeesanmuthuvel. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
