### ISSUE TITLE
Result JSON: SQL without RWI list

### ISSUE THREAD

**Issue by lenok2018** [great-expectations/great_expectations#9593]
Hello team.
Our team faces an unpleasant experience, using "expect_column_values_to_not_be_null" check with Prod data.
Prod DB tables contain a lot of null values now, so running GE test suits we obtain result JSON with thousands RWI in section Result format--> unexpected_list with COMPLETE setting.
We know that its an expected behavior of Complete setting, but this affects out result json significantly.
So, we are asking for new feature to provide the SQL without all this unexpected list rows. 
Maybe it could be an additional Keyword argument, which can switch off Unexpected list specification or some other decision.

Please, review the example of our json file - there are more than 40000 RWI in unexpected list:

![image](https://github.com/great-expectations/great_expectations/assets/39565023/628aeb5d-9285-4683-89e9-9cae504d9978)

**Comment by austiezr** [comment]
Hey @lenok2018 ! Thanks for raising this feature request -- we've captured this feedback for our internal backlog. I've leave this issue open for the next week if you have any additional context you'd like to provide. 🙇

**Comment by kujaska** [comment]
+100500 we need this tooooooooooooooo!

**Comment by 0lgaZv** [comment]
Please resolve it!

**Comment by vasilijyaromenka** [comment]
Please fix it as soon as you can. It causes issues for our team as well ((
this list might be converted to a set

**Comment by unkind58** [comment]
Will be brilliant to have some kind of a toggle for **Unexpected list**

**Comment by molliemarie** [comment]
Hello @lenok2018. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
