### ISSUE TITLE
Simplify package installation for developing and running expectations

### ISSUE THREAD

**Issue by mateocolina** [great-expectations/great_expectations#9695]
**Is your feature request related to a problem? Please describe.**
When developing expectations, one can use multiple ways to do so. Whether you would like to use JupyterLab is up to you. For running expectations in GX, a lot of packages are not required and it blows the environment (local, Docker, K8s etc.) unnecessarily (last I checked after installing GX with acryl-datahub, the Docker image had a size of 1.1 GB). We distinguish between developing expectations and running them in our daily pipeline, thus the setup is also different.

**Describe the solution you'd like**
If running `pip install great-expectations` it should install all packages related to GX. But `pip install "great-expectations[ops]"` should only install packages to successfully run expectations in the environment.

**Describe alternatives you've considered**
Uninstalling packages after the Docker image has been built, but with each release the packages are installed again.

**Additional context**
Add any other context, screenshots, or code samples about the feature request here.

**Comment by molliemarie** [comment]
Hello @mateocolina. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
