### ISSUE TITLE
Issue with ignore_row_if argument in certain expectations

### ISSUE THREAD

**Issue by NehaNRane** [great-expectations/great_expectations#9748]
I've encountered a problem with the `ignore_row_if` argument in three expectations: `expect_column_pair_values_a_to_be_greater_than_b`, `expect_multicolumn_sun_to_equal`, and `expect_compound_columns_to_be_unique`. While the argument works as expected when `either_value_is_missing` or `any_value_is_missing` is passed, it behaves unexpectedly when `both_values_are_missing` / `all_values_are_missing` or `neither` / `never` is used.
 
Specifically, when using  `both_values_are_missing` / `all_values_are_missing` or `neither` / `never` in the `ignore_row_if` argument, the following metrics are incorrect:
- unexpected_count
- unexpected_percent
- partial_unexpected_list
- unexpected_percent_total
- unexpected_percent_nonmissing
 
This issue impacts the accuracy of the expectations and could lead to incorrect interpretations of data quality.
 
**Steps to Reproduce:**
1. Use the affected expectations (`expect_column_pair_values_a_to_be_greater_than_b`, `expect_multicolumn_sun_to_equal`, `expect_compound_columns_to_be_unique`).
2. Pass  `both_values_are_missing` / `all_values_are_missing` or `neither` / `never` in the `ignore_row_if` argument.
3. Observe the incorrect values for the mentioned metrics.
 
Expected Behavior:
The `ignore_row_if` argument should accurately handle the specified conditions ( `both_values_are_missing` / `all_values_are_missing` or `neither` / `never`) and produce correct metrics for the affected expectations.
 
Additional Context:
- Great Expectations version: 0.18.12
- Python version: 3.9.6
- snowflake-connector-python: 3.8.1
- snowflake-sqlalchemy: 1.5.1

**Comment by molliemarie** [comment]
Hello @NehaNRane. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
