### ISSUE TITLE
great_expectations datasource new 

### ISSUE THREAD

**Issue by DataWanderer** [great-expectations/great_expectations#9873]
**Describe the bug**
`great_expectations datasource new`
The command `datasource` does not exist.
Please use one of: ['checkpoint', 'datasource', 'docs', 'init', 'project', 'store', 'suite']

**To Reproduce**
`great_expectations datasource new`

**Expected behavior**
Able to create a data source

**Environment (please complete the following information):**
 - Mac
 - great_expectations, version 0.18.13

**Comment by rachhouse** [comment]
Hi @DataWanderer, thanks for your issue!

The use of the `great_expectations` CLI is deprecated. To create new Data Sources with `0.18.x`, you'll want to use our current Fluent Data Source approach. Here's a few links to help you get started:
* GX OSS Quickstart: https://docs.greatexpectations.io/docs/oss/tutorials/quickstart
* Connecting to a SQL Data Source: https://docs.greatexpectations.io/docs/oss/guides/connecting_to_your_data/fluent/database/connect_sql_source_data
* Connecting to an in-memory Data Source (notably, pandas/Spark dataframes): https://docs.greatexpectations.io/docs/oss/guides/connecting_to_your_data/fluent/in_memory/connect_in_memory_data

If you have general usage questions around GX OSS as you get into it, please reach out on [our Discourse forums](https://discourse.greatexpectations.io/). (Specific bugs and feature requests can still be submitted to this repo as GitHub issues).
