### ISSUE TITLE
Error: [psycopg2.errors.SyntaxError] syntax error at or near “(”\nLINE 2: FROM (SELECT b1 as( select 'pt_lat_value' as type, count(*) …\n ^\n\n

### ISSUE THREAD

**Issue by rishabtomards** [great-expectations/great_expectations#9882]
i am trying to read a query as a batchrequest using runtimebatchrequest class and the query is using a with clause, and this is giving me syntax error but the query is perfectly working fine.

**To Reproduce**

**this is the combined_query**   # You can use any query using a with clause.

combined_query = WITH data_table_1 AS (SELECT ‘category_1’ AS type, COUNT() AS cnt FROM table_1_union UNION SELECT ‘category_2’ AS type, COUNT() AS cnt FROM table_2_union),
data_table_2 AS (SELECT ‘category_1’ AS type, COUNT() AS cnt FROM table_1_values UNION SELECT ‘category_2’ AS type, COUNT() AS cnt FROM table_2_values)
SELECT COUNT(d.diff) FROM (SELECT dt1.type, ABS(dt1.cnt - dt2.cnt) AS diff
FROM data_table_1 dt1 JOIN data_table_2 dt2 ON dt1.type = dt2.type) d
WHERE d.diff > 0

**runtimebatchrequest**

batch = RuntimeBatchRequest(
datasource_name=“my_postgres_datasource”,
data_connector_name=“default_runtime_data_connector_name”,
data_asset_name=“default_name”, # this can be anything that identifies this data
runtime_parameters={“query”: combined_query},
batch_identifiers={“default_identifier_name”: “default_identifier”},
)

**this is the validator**
validator_query = self.gx_context.get_validator(batch_request = batch)

**Expected behavior**
Returns a queried data on which we can apply the expectations.

**Environment**
 - Operating System: [ Windows]
 - Great Expectations Version: [0.13.2]
 - Data Source: [PostgreSQL]

**Comment by rachhouse** [comment]
Hey @Rishab12023, I see this GitHub issue is duplicated by your Discourse post here: https://discourse.greatexpectations.io/t/facing-a-syntax-error-with-psycopg2-while-trying-to-read-data-using-a-query-involving-a-with-statement/1730

I've responded on the Discourse post and am going to close out this issue so that we can consolidate the conversation in Discourse.
