### ISSUE TITLE
unexpected json.decoder.JSONDecodeError 

### ISSUE THREAD

**Issue by angelika233** [great-expectations/great_expectations#9883]
**Describe the bug**
Hi! I'm writting this issue because all my great expectations stopped working in the previous week. They're run on pandas dataframe and json files used to work fine, but since last week each of them gives the same error. `Extra data: line 1 column 8 (char 7)`. I have not made any changes to my environment and have even tried running it on different ge  versions, but the issue persists. Could you please help me resolve this? Thank you!

**To Reproduce**
```
  {
    "data_asset_type": null,
    "expectation_suite_name": "my_data.demo",
    "expectations": [
      {
        "expectation_type": "expect_column_max_to_be_between",
        "kwargs": {
          "column": "updated_at",
          "min_value": 1
        },
        "meta": {}
      },
      {
        "expectation_type": "expect_column_max_to_be_between",
        "kwargs": {
          "column": "yesterdaycount",
          "min_value": 1
        },
        "meta": {}
      },
      {
        "expectation_type": "expect_table_row_count_to_be_between",
        "kwargs": {
          "min_value": 15000
        },
        "meta": {}
      },
      {
        "expectation_type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "backlog"
        },
        "meta": {}
      },
      {
        "expectation_type": "expect_column_values_to_not_be_null",
        "kwargs": {
          "column": "backlog_1"
        },
        "meta": {}
      }
    ],
    "ge_cloud_id": null,
    "meta": {
      "citations": [],
      "great_expectations_version": "0.14.1"
    }
  }
```
gives an error
```
json.decoder.JSONDecodeError: Extra data: line 1 column 8 (char 7)
```
**Expected behavior**
I except this json file to work and in this case pass expectations

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux]
 - Great Expectations Version: [0.14.1] but other version have the same issue
 - Data Source: [pandas]
 - Cloud environment: [prefect] but for local run is the same

**Additional context**
The problem occured after ge release but I did not upgrade my ge version by then

**Comment by Kilo59** [comment]
@angelika233 can you share the full stacktrace and your installed packages + versions?

**Comment by molliemarie** [comment]
Hello @angelika233. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
