### ISSUE TITLE
Update from old 'cx_Oracle' to 'oracledb'

### ISSUE THREAD

**Issue by cjbj** [great-expectations/great_expectations#9899]
SQLAlchemy 2 supports the latest Oracle Database driver which was renamed to python-oracledb from cx_Oracle a couple of years ago.  The new version is a 'thin' driver so a simple 'pip install oracledb' installs all that is needed to connect to Oracle Database.

The test suite references to cx_Oracle should be updated to the new module name 'oracledb' as appropriate when SQLAlchemy 2 is in use. https://github.com/search?q=repo%3Agreat-expectations%2Fgreat_expectations%20oracle&type=code

The engine creation prefix for Oracle Database is 'oracle+oracledb://'

If you want an Oracle DB container for testing, use https://hub.docker.com/r/gvenzl/oracle-free

**Comment by molliemarie** [comment]
Hello @cjbj. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗

**Comment by cjbj** [comment]
@molliemarie where is the source code for the GX 1.0?
