### ISSUE TITLE
Great Expectations errors out in attempting to write to read only file system

### ISSUE THREAD

**Issue by javier5109** [great-expectations/great_expectations#9911]
**Describe the bug**
When running a MWAA instance when the volume is read only. The current exception only allows permissions errors to continue 

**To Reproduce**
1. spin up mwaa runner https://github.com/aws/aws-mwaa-local-runner
2. edit volume to be read only
3. If there is going to be any update to great_expectations.yml it fails

**Expected behavior**
I expect it to continue just like when the system is not in read only. The code is already set to do it, just need to give it one more additional exception.

**Additional context**
I have fixed this issue by adding OSError to the exception. inline_store_backend.py

    def _save_changes(self) -> None:
        context = self._data_context
        config_filepath = pathlib.Path(context.root_directory) / context.GX_YML

        try:
            with open(config_filepath, "w") as outfile:
                context.config.to_yaml(outfile)
        # In environments where wrting to disk is not allowed, it is impossible to
        # save changes. As such, we log a warning but do not raise.
        except (PermissionError, OSError) as e:
            logger.warning(f"Could not save project config to disk: {e}")

**Comment by Kilo59** [comment]
@javier5109 This was added as part of the `0.18.15` release.
https://github.com/great-expectations/great_expectations/releases/tag/0.18.15

**Comment by Kilo59** [comment]
Note: There still may be other issues with Read Only filesystems

- https://github.com/great-expectations/great_expectations/issues/8697
