### ISSUE TITLE
unable to limit sql asset to top 1000 rows

### ISSUE THREAD

**Issue by MarkAngler** [great-expectations/great_expectations#9917]
**Describe the bug**
There does not seem to be any clear way to limit a table asset to a top 1000 rows. 

**To Reproduce**
```python
import great_expectations as gx
from great_expectations.core.batch import BatchRequest
import sqlalchemy
from azure.keyvault.secrets import SecretClient
from azure.identity import DefaultAzureCredential
import os

# env = os.environ['ENVIRONMENT']
env = 'Dev'

if env == 'Prod':
    keyVaultName = “secrets”
else:
    keyVaultName = “secrets”'

KVUri = f"https://{keyVaultName}.vault.azure.net"

credential = DefaultAzureCredential()
client = SecretClient(vault_url=KVUri, credential=credential)

username = 'bankdwadmin'
password = client.get_secret('bankdw-sql-administrator-login')
password = password.value

context = gx.get_context()
expectation_suite_name_prefix = "ExpectationSuite_BankDW"
expectation_suite = context.add_or_update_expectation_suite(expectation_suite_name=expectation_suite_name_prefix)


dwConnString = f'mssql+pyodbc://{username}:{password}@servername.database.windows.net:1433/BankDW?driver=ODBC+Driver+17+for+SQL+Server'
BankDwEngine = sqlalchemy.create_engine(dwConnString)
datasource = context.sources.add_sql(
    name="BankDW", connection_string=dwConnString
)



asset_tablename = 'Account'
asset_name = f'asset_{asset_tablename}'


datasource.add_table_asset(name=asset_name, table_name=asset_tablename)



# query = f"select top (1000) * from dbo.{asset_tablename}"
# datasource.add_query_asset(name=asset_name, query=query)


# asset = datasource.get_asset(asset_name)



batch_request = datasource.get_asset(asset_name).build_batch_request(batch_slice="[:1001]")

validator = context.get_validator(
    batch_request=batch_request
)

# onboarding
# missingness
data_assistant_onboarding_result = context.assistants.onboarding.run(
    validator=validator,
    exclude_column_names=[],
)


validator.expectation_suite = data_assistant_onboarding_result.get_expectation_suite(
    expectation_suite_name=f"{expectation_suite_name_prefix}_{asset_name}"
)

validator.save_expectation_suite()



checkpoint = context.add_or_update_checkpoint(
    name="CheckPoint_BankDw",
    validator=validator
)

checkpoint_result = checkpoint.run()

context.build_data_docs()
context.open_data_docs()`
```

**Expected behavior**
a key word or api or anything to limit the number of rows to scan. sql query doesnt work, it just errors out.

**Environment (please complete the following information):**
 - Operating System: [e.g. Linux, MacOS, Windows]
 - Great Expectations Version: [e.g. 0.13.2]
 - Data Source: [e.g. Pandas, Snowflake]
 - Cloud environment: [e.g. Airflow, AWS, Azure, Databricks, GCP]

**Additional context**

**Comment by molliemarie** [comment]
Hello @MarkAngler. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
