### ISSUE TITLE
Indexing error when validating expect_column_pair_values_to_be_in_set

### ISSUE THREAD

**Issue by Pbrosten** [great-expectations/great_expectations#9931]
**Describe the bug**
When validating expect_column_pair_values_to_be_in_set on a dataframe with a custom index there is an indexing error which causes the test to be skipped during validation.

**To Reproduce**
Attached is my yml file along with a notebook which recreates the indexing: 
[error_recreation.zip](https://github.com/great-expectations/great_expectations/files/15323132/error_recreation.zip)

**Expected behavior**
The expect_column_pair_values_to_be_in_set should be able to run normally even with custom index.

**Environment (please complete the following information):**
 - Operating System: Windows
 - Great Expectations Version: 0.18.12
 - Data Source: Pandas

**Comment by molliemarie** [comment]
Hello @Pbrosten. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
