### ISSUE TITLE
expect_column_values_to_not_be_null duplicates columns in unexpected values query

### ISSUE THREAD

**Issue by kujaska** [great-expectations/great_expectations#9943]
**Describe the bug**
expect_column_values_to_not_be_null duplicates columns in unexpected values query:

**To Reproduce**
if you have defined checkpoint like this:
a) query as 
Select col1, col2, col3
FROM table1

b) runtime_configuration

runtime_configuration: {
  "result_format": {
            "result_format": "COMPLETE",
            "unexpected_index_column_names": ["col1", 
                                                "col2", 
                                                "col3"
                                                ],
            "return_unexpected_index_query": True,
            "partial_unexpected_count": 20
    }
}

and expectation expect_column_values_to_not_be_null for col1

then you will get this SQL in checkpoint result JSON and DataDocs:

To retrieve all unexpected values...
SELECT col1, col2, col3, **col1**
FROM [#gx_temp_123]
WHERE col1 IS NULL;

- notice 2nd occurrence of col1

**Expected behavior**
unexpected values query does not duplicate columns:

SELECT col1, col2, col3
FROM [#gx_temp_123]
WHERE col1 IS NULL;

**Environment (please complete the following information):**
 - Operating System: Linux (Ubuntu)
 - Great Expectations Version: 0.18.1
 - Data Source: MS SQL
 - Cloud environment: Local virtual machine

**Comment by molliemarie** [comment]
Hello @kujaska. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
