### ISSUE TITLE
How do we disable uploading data to posthog.greatexpectations.io endpoint in GX 1.0.0a4?

### ISSUE THREAD

**Issue by satniks** [great-expectations/great_expectations#9966]
I am trying great-expectations v1.0.0a4 and while executing my existing v0.18.x based code, I got error due to interface change from 0.18.x to v1.x.

AttributeError: 'EphemeralDataContext' object has no attribute 'sources'

But then I was surprised to see following message at the end.
error uploading: HTTPSConnectionPool(host='posthog.greatexpectations.io', port=443): Max retries exceeded with url  : /batch/

How can we disable uploading data to the posthog endpoint used for analytics? I feel it should be disabled by default.

**Comment by satniks** [comment]
I noticed that in the file great_expectations/analytics/config.py, analytics is enabled by default. It should be disabled and whoever needs analytics should enable it.

Anyway, I was able to disable using following code:

from great_expectations.analytics.config import ENV_CONFIG
ENV_CONFIG.gx_analytics_enabled = False

**Comment by molliemarie** [comment]
Hello @satniks. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
