### ISSUE TITLE
Error using EXEC operator

### ISSUE THREAD

**Issue by IgorShcherbakov** [great-expectations/great_expectations#9982]
For example, there is some kind of dynamic query (for simplicity, here is “SELECT 1 AS Result”):
![изображение](https://github.com/great-expectations/great_expectations/assets/35165017/c7c441a8-e6ff-4a22-846b-5fd29c623c41)

The result of the check is an error:
"Error message": "1 validation error for GxConfig\nfluent_datasources -> assets -> 18 -> QueryAsset -> query\n  query must start with 'SELECT' followed by a whitespace. (type=value_error)"

- Operating System: Windows
- Great Expectations Version: 0.18.8

**Comment by molliemarie** [comment]
Hi @IgorShcherbakov. With the launch of Great Expectations Core (GX 1.0), we are closing old issues posted regarding previous versions. Moving forward, we will focus our resources on supporting and improving GX Core (version 1.0 and beyond). If you find that an issue you previously reported still exists in GX Core, we encourage you to resubmit it against the new version. With more resources dedicated to community support, we aim to tackle new issues swiftly. For specific details on what is GX-supported vs community-supported, you can reference our [integration and support policy](https://docs.greatexpectations.io/docs/application_integration_support/).

To get started on your transition to GX Core, check out the [GX Core quickstart](https://docs.greatexpectations.io/docs/core/introduction/try_gx/#test-features-and-functionality) (click “Full example code” tab to see a code example).

You can also join our upcoming community meeting on August 28th at 9am PT (noon ET / 4pm UTC) for a comprehensive rundown of everything GX Core, plus Q&A as time permits. Go to https://greatexpectations.io/meetup and click “follow calendar” to follow the GX community calendar.

Thank you for being part of the GX community and thank you for submitting this issue. We're excited about this new chapter and look forward to your feedback on GX Core. 🤗
